---
title: 公司网络与资产收益
author: ''
date: '2024-10-11'
slug: ''
categories:
  - research
tags:
  - research
---


>公司并不是作为一个独立的实体进行运转。相反，他们之间通过多种多样的关系建立了内在联系，
例如战略联盟，合资企业、研发伙伴、供应链关系。最近的一些研究表明，这些关系可能作为冲击在
公司之间传导的机制潜在影响着资产收益。尽管存在这些证据，但这些冲击传导对资产定价影响的理解
仍然不够。

>因此，本文建立了一个均衡模型来研究源于公司网络特质冲击的传导对资产定价的影响，以及这种冲击
多大程度上定量解释了资本市场现象。该模型有两个特征：一个是公司网络的拓扑结构，另一个是特质冲击传递
的关系倾向。关系倾向假设随时间变动，这种变动捕获了网络关系特征的临时特征，使公司更容易遭受相邻公司的影响。

## 基准模型

>基准模型来自于公司生产决策的抽象，考虑了单一商品经济中企业现金流通过长期网络关系相关关联。

**1.经济环境**

> 本文建立了一种易消耗商品且无限期存在的经济，时间是离散的，通过$t\in \{0,1,2,\dots\}$刻画。在每个时期，单一的商品由$n$个无限存活的公司生产，$n$潜在无限大。
企业的产出，也就是现金流，通过一个长期关系网络联系在一起。由于我们关注公司网络对资产收益的影响，而非
战略网络形成，所以我们假设公司网络关系是外生决定的。除过公司外，有大量同质且无限存活的代表性投资者，他们
持有所有经济中的资产。

**2.公司网络和公司的现金流**


> 公司现金流随着时间变化，由公司层面的总冲击决定。投入劳动、资本被标准化到1。公司$i$在$t$期的现金流如下：


$$
log(\frac{y_{it}}{Y_{t-1}})\equiv \tilde{a}_t+\tilde{z}_{it} , i\in \{1,\dots,n\}
$$

> 其中，$Y_{t-1}$代表经济在$t-1$期的总产出，$\tilde{a}_t\rightarrow i.i.d.N(0,2\sigma^2_a)$ 是$t$时期影响所有公司的冲击，$\tilde{z}_t$ 是$t$时期影响公司$i$的冲击。


> 该模型的关键特征是公司网络决定了公司冲击相关联的结构。在模型中，长期持久的关系有双重性质，一方面，这种关系通过效率提升增加了公司的增长机会；另一方面，随着公司对其相邻公司的依赖性增加，这种网络关系可能会产生额外的后果，这样，增加了企业对负向特质风险的暴露，为了捕获这种对冲关系，$\tilde{z}_{i,t+1}$被定义如下：

$$
\tilde{z}_{i,t}=\alpha_1d_i-\alpha_2\tilde{\epsilon}_{i,t+1}, i \in\{1,\dots,n\}
$$

> 其中，参数$\alpha_1$和$\alpha_2$是非负参数，所有公司都相等。参数$d_i$代表与公司i有直接关系的公司数量。在$\tilde{z}_{i,t+1}$上的不确定性通过伯努利随机变量$\tilde{\epsilon}_{i,t+1}$引入。如果公司$i$遭受特质冲击的直接影响，或者遭受其相邻公司的特质冲击影响，$\tilde{\epsilon}_{i,t+1}=1$，否则，$\tilde{\epsilon}_{i,t+1}=0$。


> 为了简化模型，$\tilde{\epsilon}_{i,t+1}$的分布由随机过程决定，该随机过程从临时的特质冲击的传播抽象所得。在$t=1$期初，每个公司以$0<q<1$的概率面临一个与其他公司独立的负向冲击，公司$i$的负向特质冲击在$t+1$期也会影响公司$j$。当存在连接公司$i$和公司$j$的关系序列，并且该序列中的每个关系传递冲击时，$\tilde{\epsilon}_{i,t+1}=\tilde{\epsilon}_{j,t+1}=1$。如果公司$i$和公司$j$在$t+1$时期没有传递冲击，其将依概率$\tilde{p}_{ij,t}$独立于其他关系。为了简化，这种关系被假设是间接的，$\tilde{p}_{i,jt}=\tilde{p}_{ijt}$，所以，$\tilde{p}_{ij,t+1}$测量了特质冲击从公司$i$传递到公司$j$的关系倾向。

> 在基本层面，$\tilde{p}_{ij,t+1}$值捕获了公司$i$与公司$j$在现金流上的内部依赖性。该内部相依性并不能通过中心节点缓解。$\tilde{p}_{ij,t+1}$值越高，冲击对公司$i$现金流影响的可能性越高。概率$\{\tilde{p}_{ij,t+1}\}_{(i,j)}$来自于参数为$\zeta_{1,t=1}$和$\zeta_{2,t=1}$的Beta分布。


**3.特质冲击的传播**

> 让$G$代表$n$个公司之间的网络关系，其中节点代表公司，边代表连接关系。给定特质冲击如何沿网络传播，$\tilde{\epsilon}_{i,t}$由$G$,$q$和随机转移矩阵$\tilde{p}_t\equiv [\tilde{p}_{ijt}]$。$\tilde{\epsilon{i,t}}$基于条件$\tilde{p}_t$的条件分布为$q$,网络G以及公司i在网络G中的位置。即：

$$
P(\tilde{\epsilon}_{i,t}=1|\tilde{p}_t)=f(q,G,location \space{} of \space{} firm \space{} i \space{} in \space{} G)
$$

> 其中，$P(\tilde{\epsilon}_{i,t}=0|\tilde{p}_t))=1-P(\tilde{\epsilon}_{i,t}=1|\tilde{p}_t)$，$f$是一个由随机过程刻画的映射，由于$\tilde{p}_t$随着时间变化，$f$产生了公司现金流增长的时变相关结构。

> 在$n$非常大的时候，映射$f$很难刻画，但是描述给定的随机分布的性质很容易。首先，在没有关系的情况下，$\forall i$和$\forall t$，$P(\tilde{\epsilon}_{i,t}=1|\tilde{p}_t)=P(\tilde{\epsilon}_{i,t}=1)=q$，所以公司层面的冲击在公司和时间维度上是独立的。第二，如果两个序列之间的关系存在顺序，序列越长，公司之间冲击的关系越小。

**4.冲击传播的临时变化**

> 为了捕获具体关系的临时变化，形状参数$\zeta_{it}={1,2}$也是随时间变动的。形状参数的变化可能是由于企业活动之间互补性的变化或新技术的到来重塑了经济的长期增长前景，具体来说，$\zeta_{it}$取两个值，$\zeta_{iL}$或$\zeta_{iH}$。其中，$\zeta_{iL}<\zeta_{iH}$,并且形状参数向量$\zeta_t \equiv [\zeta_{1t} \zeta_{2t}]$服从四个状态遍历的马尔可夫过程，转换矩阵为$\omega$，状态$\zeta_{LL}\equiv[\zeta_{1L}\zeta_{2L}]$，$\zeta_{LH}\equiv[\zeta_{1L}\zeta_{2H}]$，$\zeta_{HL}\equiv[\zeta_{1H}\zeta_{2L}]$，$\zeta_{HH}\equiv[\zeta_{1H}\zeta_{2H}]$。


## 总消费增长

> 除了总量冲击之外，该模型的两个特征对于理解总量消费增长的分布也很重要，一个是网络结构，另一个是特质冲击如何沿网络传播。在这部分，我们研究这两个特征的变化如何影响总消费增长，进而改变定价核的分布。

> 让$\Delta\tilde{c}_{t+1}\equiv log(\frac{c_{t+1}}{c_t})$和$\Delta\tilde{x}_{t+1}\equiv log(\frac{Y_{t+1}}{Y_t})$分别表示$t+1$年对数消费增长和产出增长。而不是假设总消费是所有投资财富组合的红利。
 
>  我们参考Campbell(1986)和Cecchetti et al.(1993)的研究，做出了更一般的假设，假设股票市场的总红利等于总消费的幂。这样$\Delta\tilde{c}_{t+1}$和$\Delta\tilde{x}_{t+1}$满足：

$$
\Delta\tilde{x}_{t+1}=(\frac{1}{\tau})\Delta\tilde{c}_{t+1}
$$

> 其中，$\tau$是一个常数，这样，代表性的投资者被假设能获得劳动收入。Abel(1999)在论文中提出，$(1/\tau)$表示股票的杠杆率，如果$tau=1$，市场组合是对总财富的索赔。为了简化，让$Y_t\equiv \prod_{i=1}^{n}{y_{i,t}^{1/n}}$，我们可以得到：



$$
\begin{align*}
\Delta\tilde{c}_{t+1}&=\tau\tilde{x}_{t+1}\\
                     &=\tau log\left ( \prod_{i=1}^{n}\big ({\frac{y_{i,t}}{Y_t}\big )^{1/n}}\right)\\
                     &=\tau \left (\tilde{a}_{t+1}+\alpha_1 \big( \frac{1}{n}\sum_{i=1}^{n}d_i \big)-\alpha_2 \big( \frac{1}{n}\sum_{i=1}^{n}\epsilon_{i,t+1} \big) \right)\\
                     &=\tau \left (\tilde{a}_{t+1}+\alpha_1 \bar{d} -\alpha_2 \tilde{W}_{n,t+1} \right)
\end{align*}
$$

> 其中，$\bar{b}$代表在经济中每个公司关联关系的平均数量，而$\tilde{W}_{n,t+1}$表示$t+1$期遭受特质冲击公司的平均数量。这样$\Delta\tilde{c}_{t+1}$的分布取决于$\tilde{W}_{n,t+1}$，给定特质冲击如何沿网络传播，$\Delta\tilde{c}_{t+1}$的分布受概率$\tilde{p}_{t+1}$和网络$G$的拓扑结构的影响。

> 为了理解概率$\tilde{p}_{t+1}$和网络$G$的拓扑结构对$\Delta\tilde{c}_{t+1}$影响的重要性，考虑两种情况。


> **（1）假设公司网络没有相关性**

> 如果公司网络之间没有相关性，那么$\{\tilde{\epsilon}_{i,t+1}\}_i^n$是一个独立二项分布的随机变量序列，并且$n\tilde{W}_{n,t+1}$服从二项分布，根据中心极限定理，随着$n$的增加，$\sqrt{n}(\tilde{W}_{n,t+1}-q)$服从正态分布。此时，$\sqrt{n}\tilde{W}_{n,t+1}$的均值和方差分别为$q$和$\frac{q(1-q)}{n}$。


> **（1）假设每个公司有两个关联关系**

> 假设每个公司有两个关联关系，每个关系有一个不随时间变化的倾向$p$，那么$\{\tilde{\epsilon}_{i,t+1}\}_i^n$是一个相互依赖的二项分布随机变量序列，如果$p$足够小，$n\tilde{W}_{n,t+1}$将服从二项分布。在这种情况下，$p$将影响消费增长的分布，此时，$\tilde{W}_{n,t+1}$的均值和方差分别为$pi$和$\frac{\pi(1-pi)}{n}$,$\pi$可以从以下方程获得:

$$
\pi=q+(1-q)\pi p(\pi p+2[p(1-\pi)+\pi(1-p)])
$$

## 资产定价

> 为了捕获网络结构$G$及其结构变化对资产收益的影响，我将企业网络生成的产出相关性结构嵌入到标准资产定价框架中。为了解释资产定价现象并处理二次效用函数带来的挑战，本文利用Epstein-Zin-Weil递归偏好效用函数来处理该问题。在公司i总收益约束下的资产定价模型如下：

$$
E_t[\tilde{M}_{t+1}\tilde{R}_{i,t+1}]=1
$$

> 其中，$\tilde{M}_{t+1}\equiv \left[\beta(e^{\Delta \tilde{c}_{t+1} }) ^{-\rho}\right]^{\frac{1-\gamma}{1-\rho}}\left[\tilde{R}_{a,t+1}\right]^{\frac{1-\gamma}{1-\rho}-1}$ 表示$t+1$期的定价核，$\tilde{R}_{a,t+1}$ 代表总财富上的总收益。



> 为了解这个模型，我们寻找均衡资产价格，使得价格-红利比率平稳。由于均衡价值是经济状态的时变函数，由状态向量$\zeta$决定，所以，$s\in S \equiv \{LL,LH,HL,HH\}$表示状态向量的当前特征。此时，在当前状态下的期望总收益为：

$$
E(R_a|s)=e^{\tau (\alpha_1d+\tau\sigma_a^2)}\sum_{s^\prime\in S}w_{s,s^\prime}\left(\frac{w_{s^\prime}^a+1}{w_{s^\prime}^a}\right)E\left(e^{-\tau\alpha_2\tilde{W}_{n,t+1}}|s^\prime\right)
$$
> 其中，$w_s^a$是当前总财富的价格，该变量来自于下面系统方程：

$$
w_s^a=\beta e^{\tau(1-\rho)(\tau(1-\gamma)\sigma_a^2+\alpha_1\bar{d})}\left(\sum_{s^\prime \in S}w_{s,s^\prime}E(e^{\tau(1-\gamma)\alpha_2\tilde{W}_{n,t+1}}|s^\prime)(w_{s^\prime}^\alpha+1)^\frac{1-\gamma}{1-\rho}\right)
^\frac{1-\gamma}{1-\rho}
$$
从上面的方程可以看出，期望收益和总财富的价格受总冲击（$\sigma^2_\alpha$）和网络拓扑结构（$G$）影响。

对于无风险资产来说，在下一期将确定会支付一单位消费。用$R_f(s)$代表当前状态下无风险资产的总收益，则$R_f(s)$可以从下面方程解得：

$$
\frac{1}{R_f(s)}=\beta^{\frac{1-\gamma}{1-\rho}}e^{-\tau\gamma(\alpha_1\bar{d}-\tau\gamma\sigma^2_\alpha)}\left(\sum_{s^\prime \in S}w_{s,s^\prime}E(e^{\tau\gamma\alpha_2\tilde{W}_{n,t+1}}|s^\prime)(\frac{w_{s^\prime}^{a}+1}{w_{s^\prime}^{a}})^{\frac{1-\gamma}{1-\rho}}\right)
$$
所以，均衡无风险率也由总冲击和拓扑结构驱动。

现在我们研究横截面资产的期望收益，为了方便起见，我们将网络关系表示为至少两个公司关系序列的集合。如果$G^i_n$公司i属于连接关系集合，则$G_n$可以表示为：
$$
G_n\equiv \bigcup_{i \in G_n}G_n^i
$$

定义如下平均数：

$$
\tilde{W}^i_{n,t+1}\equiv \frac{1}{n}\left(\sum_{j\in G_n^i}\tilde{\epsilon}_{j,t+1}\right)
$$

$$
\tilde{W}^{-i}_{n,t+1}\equiv \frac{1}{n}\left(\sum_{j\in G_n/G_n^i}\tilde{\epsilon}_{j,t+1}\right)
$$

其中，$\tilde{W}^i_{n,t+1}$表示$t+1$期受特质冲击影响的平均公司数量，$\tilde{W}^{-i}_{n,t+1}$表示$G_n^i$外受特质冲击影响的平均公司数量。

如果$\nu_i(s)$代表当前公司$i$的状态价格，则公司$i$的期望收益表示如下：

$$
E(\tilde{R}_{i,t+1}|s)=\frac{e^{(1/\tau)((1/\tau)\sigma_\alpha^2+\alpha_1\bar{d})}}{\nu_i(s)}\left(\sum_{s\prime \in S}w_{s,s^\prime}\nu_i(s)E(e^{-(1/\tau)\alpha\tilde{W}_{n,t+1}}|s^\prime)\right)\\+\left(\sum_{s\prime \in S}w_{s,s^\prime}E(e^{-\alpha_2\tilde{\epsilon}_{i,t+1}}|s^\prime)\right)
$$


因此，公司i的预期收益由于多样化收益而下降。因此，企业的预期收益受到以下因素的影响：（a）企业对影响同一关联成分中其他企业的特质冲击的脆弱性;（B）其他关联成分中的企业受特质冲击影响的频率。