---
title: 因子动量和动量因子
author: 薛英杰
date: '2023-10-23'
slug: factor momentum and  momentum factor
categories:
  - research
tags:
  - research
bibliography: [one.bib]
link-citations: TRUE
bilbio-style: "biomed-central.csl"
editor_options: 
  markdown: 
    wrap: 72
---

### 摘要

> 股票收益的动量与因子收益动量相关。大多数因子存在正的自相关，即在前一年亏损后，
> 因子平均每月获得0.06%的收益，前一年盈利后，平均每月获得0.51%的收益。我们发现动量
> 因子集中在能够解释更多横截面收益的因子中，他并不是偶然的个股动量，中性动量因子呈
> 现了更多的动量。由高特征值主成分构造的动量包含了更多个股动量的形式。我们的结果表
> 明动量不是一个明显的风险因子，他是其他风险因子的择时。

### 研究思路

> 动量因子是一个颇受争议的定价因子，自1993年Jegadeesh和Titman发现动量效应以来，学
> 者们关于动量效应产生的原因以及动量因子是否应该被纳入资产定价模型争论持续了近30年。

> 对于动量效应的解释主要如下：

> 1.  投资者的行为偏差（投资者对信息反应不足）

> 2.  交易摩擦

> 3.  系统性风险

> 针对动量因子是否被应该被纳入资产定价模型，主要观点如下：

> **Fama-French认为动量效应是利用历史信息预测未来收益，这违反了若有效市场假说，因此，动量因子不应该被纳入资产定价模型。而最近一些研究发现，动量反映了时变风险，应该被纳入资产定价模型。由于在许多情况下，不加动量因子，资产定价异象无法被解释，所以动量因子也被Fama逐渐接受。**

> 在这个背景下，本文主要内容如下：

> 1.从大家普遍接受的风险因子出发，提出风险因子具有动量，并认为因子动量反映了与其他因子择时相关的系统性风险

> 2.利用Kozak的模型从理论上解释了为什么会出现因子动量?
> 该理论模型认为，投资者情绪导致的因子反转或动量
> 取决于投资者情绪的持续性，如果投资者情绪持续足够久，这种持续性将会在因子收益上延续。虽然套利者知道因子
> 溢价可以预测，由于他们暴露了因子风险，没有足够的动力去消除因子溢价。总之，动量集中在更多系统因子中。

> 3.  因子收益动量会传递到传递到横截面资产上，也就是说，动量因子是否来源于因子动量。

> 4.  检验了因子动量与目前现有动量因子的关系，并解释了为什么传统风险因子与动量因子之间的相关性很低。

### 文献观点

> 1.动量在时间和各类资产中存在奠定了其作为独立因子的地位，没有动量的模型不能解释动量相关的异象，包含动量的模型只能解释动量[@Famahhv043]。

> 2.  @ehsani2022time
>     研究表明，动量（UMD）与Fama-French时间序列有效模型回归有共同因素。
>
> 3.  短期横截面因子动量解释了短期行业动量[@arnott2023factor]。
>
> 4.  行业动量很大程度上与股票动量相关[@grundy2001understanding]。
>
> 5.  投资者情绪指数存在一阶自相关[@baker2006investor]。

### 研究结论

> 正的自相关是因子收益的的普遍特征。因子动量来自于对未来因子收益的押注策略。因子动量通过股票因子载荷传递到横截面股票收益中，本文发现因子动量解释了传统的标准动量、行业调整动量、中间动量、夏普动量以及残差动量。而其他的动量因子不能解释因子动量。

> 我们的研究结果发现，动量不是一个独特的因子，相反他是已经发现因子自相关的总和，由于所有的赢家和输家有相似的的因子暴露，投资者交易动量承担了系统性风险。动量和其他因子不相关是因为因子载荷随时间在变化。

> 因子动量可能源于错误定价。当情绪足够持久时，情绪投资者产生了因子动量。虽然动量因子和情绪投资者的行为一致，但这并不意味着因子动量一定来自错误定价。

