---
title: 投资者需求，企业投资与资本错配
author: 薛英杰
date: '2025-05-29'
slug: investor demand firm investment
categories:
  - research
tags:
  - research
editor_options: 
  markdown: 
    wrap: 72
bibliography: [reference.bib]
link-citations: TRUE
bilbio-style: "biomed-central.csl"
---

## Investor demand,firm investment,and capital misallocation

### 摘要

> 投资者需求波动显著地影响公司的价值和资本获取，为了量化他们的实际效应，我们建立了一个动态
> 投资模型，将资本供给侧与需求侧纳入其中。强劲的投资者需求放松了金融约束，促进了股票发行和投资，
> 而疲软的需求则鼓励了投机性的股票回购，挤出了投资。我们使用间接推理来估计模型，匹配投资者需求
> 和企业政策之间的内生关系。我们的估计表明，需求波动是企业层面投资和经济范围内资本错配的重要驱
> 动因素，占MPK分散的26.9%和生产力损失的23.4%。

### 研究问题

> 美国股票市场历史上充满了令人惊奇的繁荣与萧条。例如，在1990年纳斯达克泡沫期间，互联网股票加
> 以价格水平脱离了大多数理性定价预期。许多股票价格暴涨为公司提供了原本无法获得融资的机会，这些
> 戏剧性的估值事件归因于投资者的需求。尽管估值与基本面不匹配，但他们仍然青睐这些股票，这种需求
> 如何影响企业间的资本配置?它是否促进了对生产率更高、资金需求更大的公司的投资?如果不是，投资者
> 需求导致的资本配置扭曲程度有多大?这些问题直接说明了金融市场在有效配置资本方面的核心作用。

### 研究思路

> 在本文中，我们通过建立和估计一个动态模型来回答此问题。在模型中，企业在面临投资者对其股权需
> 求驱动的资本供应时做出投融资决策。投资者需求随时间变动，并嵌入了投资者需求与企业最优投融资之
> 间的关系，研究了企业财务政策对投资者需求的影响，进一步评估了投资者需求对上市公司资本配置效率的影响。

### 投资者需求的度量

> 参考[@koijen2019demand]的模型，该模型使用公司特征和基本面的潜在波动来反映投资者的需求，并强调该研究对资产定价的意义。我们研究讨论了这些需求的驱动效应对公的产出和经济资源配置效率的意义。

### 资本错配的度量

> 资本错配是用企业横截面上的资本边际产量(MPK)的方差和经济中全要素生产率(TFP)的平均损失来衡量的，两者都反映了企业之间有效资本配置的偏差[@hsieh2009misallocation]。

### 本文的贡献

> 1.  本文的模型关注的是公司和投资者之间的交互。公司考虑由投资者需求引起的价格均衡后做出投融资决策。这些决策会反馈到投资者需求函数中，投资者需求的间接效应在于其对公司融资决策的影响。高需求会激励公司发行更多的股份，而低需求会使公司以诱人的价格回购股票。
> 2.  本文的模型通过投资者需求影响公司实际投资决策而考虑了两个关键机制。第一，投资者需求波动创造了市场择时的机会，能够使公司利用金融交易，这个资源缓解了公司的融资约束，帮助他们的投资向无约束水平收敛。第二，公司参与金融交易可能对其他投资能力产生异质效应。正向的超额需求会鼓励公司发行股票，提供给他们额外投资的资金。负向的超额需求促使企业减少投资，优先考虑有利可图的金融市场而不是投资效率。

### 文献观点

> 1.  与以往研究其他资源错配的驱动因素相比，投资者需求的波动时资源错误的一个重要驱动因素[@midrigan2014finance;
>     @moll2014productivity; @david2022risk]。
>
> 2.  @dessaint2019noisy
>     的研究表明，企业根据共同基金流动引发的股市噪音调整投资。
>
> 3.  @warusawitharana2016equity
>     研究了一个动态投资模型，以估计反映在公司市净率中的错误定价在多大程度上推动了投资和融资。

### 结论

> 在本文中，我们建立了一个动态模型，在这个模型中，企业在面临投资者提供资金的情况下进行投融资决策。该模型内化了权益资本的需求侧和供给侧，使我们能够捕捉到投资者需求与公司发行或回购股票决策的均衡效应。我们严格规范控制投资者基于特征的时变需求和公司最优政策的参数。我们的研究结果揭示了投资者和公司决策之间显著的相互作用。在总水平上，企业间需求的变化放大了横断面投资回报的差异，降低了经济中资本配置的效率。虽然本文的主要重点是实物投资，但我们的框架具有很强的适应性，可以扩展到探索有关投资者需求对公司层面决策的实际影响的广泛问题，包括治理、创新和社会责任实践。以及评估更广泛的宏观经济影响。
