---
title: 带约束的投资组合均值方差最优化求解
author: 薛英杰
date: '2025-07-20'
slug: constrained Optimization in investment portfolio
categories: []
tags: []
bibliography: references.bib
---

### 标准均值方差有效组合权重估计

> 均值-方差有效组合是给定期望收益，通过调整组合权重实现投资组合风险最小化，或给定 风险，通过调整组合权重实现投资组合收益最大化。该问题可以用数学表达式表示如下：

$$
w_{mvp}=\min_w w^\prime \Sigma w  \\  s.t. wl=1 \\ w\mu=\bar{\mu}
$$

> 其中，$\Sigma$ 是投资组合中资产收益的协方差,$l$为所有元素为1得向量，$\mu$为股票收益向量，$\bar{u}$为投资组合期望收益。

> 该优化问题可以进一步表述为带有均值方差偏好和风险厌恶因子表达式,具体如下：

$$
w_{mvp}=\max_w w^\prime\mu- \frac{\gamma}{2} w^\prime\Sigma w  \\  s.t. wl=1 
$$

> 其中，$\gamma$为风险厌恶系数。

> **最优组合问题的解如下：**

$$
w_{\gamma}^{*}=\frac{1}{\gamma}(\Sigma^{-1}-\frac{1}{l^{\prime}\Sigma^{-1}l}\Sigma^{-1}ll^{\prime}\Sigma^{-1})\mu+\frac{1}{l^{\prime}\Sigma^{-1}l}\Sigma^{-1}l
$$

> 在实证中，估计该系数常常存在很多问题。例如，在短期内，$\mu$和$\Sigma$的估计有很大的噪声；甚至当资产的数量$N$超过收益率时间序列长度（$T$）时，收益率的方差协方差矩阵$\Sigma$将不再是正定矩阵，其逆矩阵将不存在。为了解决这个问题，一些正则化技术应用而生[@ledoit2004; @ledoit2003; @ledoit2004; @ledoit2012; @fan2008]。

### 考虑估计不确定性与交易成本的均值方差有效组合权重估计

> 由于资产收益噪声较大，估计的参数具有很强的不确定性，因此，在不确定性条件下估计参数将面临重大挑战，@wang2005shrinkage 在模型和不确定性下对投资组合选择提供了理论分析；@pflug2012 证明了在所有资产上等权配置是对抗模型不确定性的最优选择。
>
> 在估计参数的不确定性中，交易成本是大家担心的主要问题，组合调整是有成本的，最优选择应该取决于投资者当前的持仓。在实证中，只给的收益率$\hat{\mu}$与其方差-协方差矩阵$\hat{\Sigma}$，得到的最优估计权重非常糟糕，文献提出了很多办法来克服该问题。例如，一种办法是对方差-协方差矩阵$\hat{\Sigma}$施加正则化，利用资产定价模型估计得到的先验信息[@kan2007]；或者使用高频数据来改善预测。
>
> 一个操作简便、有效（即使在高维度情况下）且纯粹受经济论据启发的统一框架是对交易成本进行事前调整[@hautsch2019]。
