---
title: 绿色金融与ESG文献阅读笔记
author: 薛英杰
date: '2023-04-09'
slug: green finance
categories:
  - research
tags:
  - research
bibliography: [one.bib]
link-citations: TRUE
bilbio-style: "annual-review-of-law-and-social-science.csl"
---

## [Firms and climate change: a review of carbon risk in corporate finance](https://link.springer.com/content/pdf/10.1007/s43979-022-00005-9.pdf?pdf=button)

### 摘要

> 本文概述了基于金融经济学的碳风险研究，重点是公司金融。在公司金融文献中，碳风险是指社会向低碳经济转型，由于监管收紧、消费者偏好改变、声誉受损等对公司价值的影响。我们关注碳风险与不同公司绩效因素之间的联系，例如公司风险、资本成本、财务绩效、公司价值和公司决策。虽然关于碳风险的研究在公司金融领域仍处于萌芽状态，但有关该主题的文献数量一直在增加，尤其是最近两年。我们发现一些结果是稳健的，而另一些则喜忧参半。这表明相互矛盾的假设仍然存在，需要进行更深入的探索。

### 1 . 引言

> 近年来，由于担心与人类活动排放的二氧化碳有关的全球变暖，企业的碳绩效变得越来越重要。政府间气候变化专门委员会 (IPCC) 在"气候变化 2021：物理科学基础"中指出，全球平均温度的升高明确是由于人类的影响。1 为了限制人为气候因素，2015 年 12 月的 COP 21在法国，来自 190 多个国家的代表签署了《巴黎协定》(PA)，并承诺将全球变暖限制在比工业化前水平"远低于 2°C"的水平。在实践中，许多司法管辖区已经引入了碳定价机制以减少碳排放，2 例如碳交易和碳税。具体而言，25 个国家实施了碳税（例如加拿大、英国、德国、芬兰和新加坡），36 个国家实施了碳排放交易计划（例如欧盟、美国、韩国和中国）。
>
> 这些遏制碳排放的政策引发了企业是否会受到碳风险影响的问题。哪些类型的公司最容易受到此类政策的影响？对公司绩效的影响是正面的还是负面的？为了回答这些问题，本研究回顾了关注碳风险问题的公司金融研究。尽管它与我们的研究密切相关并且很重要，但我们并未回顾有关气候变化或气候风险的大量文献。此外，为了将审查控制在可控范围内，我们将本文的范围限制在与我们正在解决的问题相关的公司金融文献中。
>
> 我们首先澄清碳排放和碳风险的定义和范围，并评估碳信息披露和数据可用性的现状。然后，我们回顾了公司风险如何与碳风险敞口相关，然后分析了关于碳风险是否以及如何影响公司资本成本的文献。此外，我们总结了碳风险与公司绩效或公司价值之间的关系。我们还检验了是否碳风险对企业行为有影响。最后，我们以对未解决问题的讨论结束，并提出进一步研究的潜在领域。

### 2 定义、度量和数据可利用性

#### 2.1 定义和范畴

> 在企业金融文献中，碳风险通常是指社会向低碳经济转型过程中由于广泛的政策、法律、技术、市场和声誉变化而对企业价值造成的影响。碳风险是一种转型风险。企业面临碳风险是因为他们在低碳转型下的碳密集型生产过程，而不是因为他们面临某种物理气候风险（例如海平面上升）。一些学者给出了碳风险的定义。例如，@hoffmann2008corporate 将碳风险视为"与气候变化或化石燃料使用相关的任何企业风险"。@ehlers2022pricing 将碳风险定义为"收紧碳排放政策的潜在财务影响"。 @stringr 将碳风险称为高排放企业在从高碳生产系统向低碳生产系统过渡期间发生的监管和市场风险。 @nguyen2020carbon 将碳风险定义为公司在从以化石燃料为基础的经济向低碳经济转型过程中的财务脆弱性。过去，高排放国可以将其碳排放成本外部化，因此不会面临碳风险。然而，随着越来越多的碳减排举措正在实施，企业需要将碳排放成本内部化，使碳风险成为核心业务考虑因素 [@clarkson2015valuation]。
>
> 在实践中，碳排放量被用来识别企业的生产过程是否是碳密集型的。碳排放通常来自化石燃料消耗、农业、森林砍伐、生产过程（例如水泥制造）和制冷剂气体使用。根据温室气体议定书，碳排放根据企业的运营和经济活动分为直接排放和间接排放。具体而言，直接排放（范围 1）与化石燃料的燃烧或企业拥有或控制的来源的化学品和材料的加工有关。间接排放是指来自购买的电力、热力或蒸汽（范围 2）的排放，以及来自所有其他价值链的排放，例如产品使用、购买的材料、外包活动和废物处理（范围 3）。

#### 2.2 测量和数据可用性

> 在回顾以往的研究时，我们发现了两种衡量企业碳风险的方法。一种方法基于碳排放，包括碳排放水平（范围 1、范围 2、范围 3 或总量）和碳排放强度（碳排放量与销售收入之比）。有一个普遍的假设，即排放水平越高，风险就越高，这一假设已通过许多实证研究进行了检验。因此，很明显提出碳排放量（性能）是否是碳风险的良好代表的问题。根据气候相关财务信息披露工作组 (TCFD)，向低碳经济转型需要改变政策、立法、技术和市场，而这些变化可能会对高排放者产生财务影响。因此，只有当公司位于气候法规更严格的司法管辖区时，我们才会将碳排放量（绩效）视为碳风险的良好代表。另一组研究使用良好的企业碳绩效作为低碳风险的代表，包括减排和碳效率。具体而言，减排量是两年或两年以上碳排放量的变化。碳效率是指与行业竞争对手相比，一家公司的产出水平在何种程度上具有较低的碳排放量 [@trinks2020efficiency]。此外，由于碳披露是解决气候相关问题的第一步，因此有必要确定碳披露是否是一种很好的风险衡量标准。如上所述，碳风险是指社会向低碳经济转型对企业价值的影响。相反，碳披露是指企业报告其碳排放量的做法，这可以减少信息不对称，但不能降低碳风险。因此，碳风险和碳披露是两个不同的概念，因为诚实的公司可能是高风险的，也可能是低风险的。
>
> 衡量碳风险的一个挑战是获取公司层面的碳排放信息，这些信息通常不会在公司的财务报表中披露，也不是大多数金融监管机构的强制要求[@andrew2011carbon]。此外，目前还没有统一的碳排放披露标准或核算方法。学者和投资者通常从遵循温室气体协议的数据提供商那里获取信息，并提供企业层面的碳排放数据。例如，由关注转型气候风险的机构投资者设立的CDP（前身为Carbon Disclosure Project），每年都会邀请全球大型企业自愿披露碳信息。企业需要填写一份问卷，获取有关企业直接和间接碳排放的信息。其他数据提供商，如 Trucost、MSCI、汤森路透、Sustainalytics、彭博和 ISS，依赖 CDP 数据并辅以其他数据源，最终形成企业层面的碳排放数据。这些数据为后续的实证研究提供了依据。

### 3 碳和企业风险

> 探索公司碳风险是否影响股票市场风险相关指标的实证工作是有限的。 @trinks2020efficiency 估计碳效率，反映公司相对于具有可比生产结构的最高效同行的碳排放水平。他们发现，碳效率高的公司系统性风险显着降低，但总体风险并未降低。@xue2020corporate 发现具有良好环境管理绩效的英国企业，如减排绩效监测，可以有效降低其特质风险和总体风险。然而，作者并未发现碳强度对企业风险有显着影响。
>
> 几项研究使用违约风险作为衡量公司风险的指标，并证实碳风险与违约概率之间存在正相关关系。具体来说， @capasso2020climate 以 2007 年至 2017 年彭博巴克莱综合企业指数成分股为样本，研究碳风险敞口对企业违约风险的影响。他们发现，一家公司的高碳排放和高碳强度会导致违约风险增加，尤其是《巴黎协定》通过后。在相关工作中，@duong2022firms 分析了 2004 年至 2018 年全球 2785 家公司的更广泛和更具代表性的样本，@kabir2021carbon 分析了碳排放与违约风险之间的关系。他们还表明碳排放对公司违约风险具有显着的积极影响，表明碳排放量较大的公司风险敞口更有可能拖欠债务。对于碳密集型行业和高度环保意识的经济体中的公司，影响更大。此外，宣布环保举措和设定排放目标可以降低碳风险对企业违约风险的影响，而卷入环境丑闻则会加剧这种影响。从另一个角度来看，@duong2022firms 使用 13 个指标评估企业的碳风险管理得分，发现得分与信用违约互换利差之间存在显着负相关，表明投资者认为良好的碳风险管理可有效降低违约概率。有趣的是，公司的违约概率也会对其排放水平产生积极影响，因为财务紧张和违约概率高的公司对跟上国家环境战略的热情较低 [@duong2022firms]。
>
> 除了暗示关联或因果关系外，许多此类研究还有助于解释为什么公司的碳风险与其违约风险正相关（例如，@kabir2021carbon ）。首先，在向低碳经济转型的过程中，制定并执行了新的法规。碳风险较高的公司更有可能承受巨大的监管压力，从而导致减排和合规成本增加。其次，由于利益相关者的环境意识增强，高碳排放者可能遭受声誉风险，导致收入进一步损失。第三，投资者和贷款人向高排放者收取碳风险溢价作为补偿，从而增加了排放者的融资成本。因此，收入减少和成本增加会放大公司的违约概率。

### 4 碳风险和资本成本

> 在分析碳风险对资本成本的影响时，研究者通常考虑两个视角：股权成本和债务成本[@li2014carbon]。

#### 4.1 碳风险和股权资本成本

> 一组研究考察了碳排放量高​​和低的公司之间股票回报的差异。主流观点是投资者要求的回报与预测的风险水平成正比。由于整个经济的低碳转型给高排放企业带来了越来越大的监管和市场风险，金融投资者要求对这些风险进行补偿，从而提高了高碳排放企业的股权资本成本[@trinks2020efficiency]。一些实证研究支持这一观点。例如，@oestreich2015carbon 观察到德国股票市场存在碳溢价，获得免费碳配额的公司表现优于其他公司。@bolton2021investors 发现，碳排放量（和排放量变化）较高的美国公司具有较高的股票回报，他们认为碳溢价不能用意外盈利能力或其他众所周知的风险因素的差异来解释。
>
> 然而，碳溢价并不总是得到证实。一些研究发现碳α。例如，[@in2017being]In 等人。 [16] 基于企业层面的碳排放强度构建碳效率减去低效率的投资组合。他们证实，自 2010 年以来，碳强度低的公司的表现优于高排放公司。@bernardini2021impact 专注于欧洲电力公司，发现从 2012 年到 2016 年，在碳排放强度低的公司做多而在碳排放强度高的公司做空的投资组合会产生正的风险调整后回报 (alpha)。此外，@gorgen2020carbon 认为不存在碳风险溢价，尽管碳风险可以解释回报的系统变化。投资者不为碳风险定价的可能原因有两个。首先，他们不知道如何解释或评估与碳风险相关的信息。其次，他们认为碳信息无关紧要，不认为碳风险会影响公司的声誉或竞争优势 [@najah2012carbon]。
>
> 另一组研究直接分析了碳风险与权益资本成本之间的相关性。 @trinks2020efficiency 显示出显着的积极影响公司的碳强度对其股权资本成本的影响。他们发现，在碳风险是一个突出问题的地方，影响更为明显，例如在碳定价法规下的高排放部门和公司。@bui2020carbon 还表明，碳强度与股权资本成本呈正相关，并且可以通过广泛的碳披露来减轻这种相关性。作者解释说，原因是披露为投资者提供了更多信息并降低了他们对高排放者风​​险的估计，从而降低了所需的溢价。@albarrak2019effect 支持这一论点。 他们发现通过 Twitter 传播碳信息可以显着降低公司的股权成本。同样，@kim2015effect 发现碳强度与韩国企业的股权资本成本之间存在显着的正相关关系。与 @bui2020carbon 不同，他们认为自愿披露可持续发展报告的公司与不披露的公司之间的影响没有什么不同。
>
> 总之，该领域的研究人员使用不同的方法和指标来检验碳风险是否被投资者完全整合。尽管大多数研究证实碳风险会显着增加股权成本，但研究结论存在不一致之处。在表 1 中，我们展示了每篇文章的结果。

#### 4.2 碳风险和债务成本

> 关于碳风险与债务成本之间的联系，大多数研究都是基于代理理论，根据该理论，当贷款人和借款人对碳密集型项目的预期不一致时，就会出现代理问题。具体来说，如果一个碳密集型项目成功，股东将从大部分利润中受益，而如果不成功，贷方将承担大部分成本。此外，根据我们在上一节中回顾的文献，我们确实发现碳风险的增加会增加企业的违约风险和信用风险[@kabir2021carbon; @alsaifi2022carbon ] 。因此，具有高碳风险的公司将被收取更高的利息，因为贷方需要补偿增加的现金流不确定性、违约风险和声誉风险[@chen2023; @jung2018carbon; @zhou2018carbon] 。
>
> 在实证分析中，虽然现有文献证实了碳风险与债务成本之间存在正相关关系，但研究结果存在一定差异。熟食店等。@delis2019being 检查银团贷款市场，并将化石燃料和非化石燃料公司的贷款利率与全球样本进行比较。他们表明，只有在《巴黎协定》通过之后，银行才开始对搁浅的化石燃料储备风险进行定价，从而导致化石燃料公司的信贷成本增加。相关地，@ehlers2022pricing 研究银行是否对所有部门的碳风险定价以反映特定部门以外的更广泛现象。他们还发现，在《巴黎协定》通过后，银团贷款市场出现了显着的碳溢价，尽管相对较低，约为 3-4 个基点。有趣的是，他们确认溢价仅存在于直接碳排放（范围 1），这表明银行不太关心公司的整体碳足迹，而是关心其直接排放。总而言之，两项研究都表明，银行直到巴黎协定才开始为碳风险定价。相对于它们，@kleimeier2018carbon 发现，在巴黎协定通过之前，来自范围 1 或范围 2 的碳排放对贷款利差产生了显着的积极影响。他们还发现，对于不透明的公司，自愿披露可以显着降低银行贷款利差。然而，对于透明的公司来说，自愿披露没有影响。这一结果与减少信息不对称可以降低资本成本的发现一致（例如，[@diamond1991disclosure]），造成结论差异的原因可能是样本企业之间的差异。虽然 Ehlers 等人。@ehlers2022pricing 和 @kleimeier2018carbon 使用公司层面的碳排放作为碳风险的代理， @kleimeier2018carbon 涵盖对 CDP 做出响应的公司，而 @ehlers2022pricing 涵盖 Trucost 数据库中的样本公司，该数据库不仅包括披露其碳排放量的公司，还包括通过投入产出模型估算排放量的公司。此外，作者使用不同的方法来计算企业的排放水平。 @kleimeier2018carbon 使用行业和公司规模调整后的碳排放量， @ehlers2022pricing 将碳风险衡量为年碳排放量与年收入之比。他们结果的差异也可能是由不同的样本周期驱动的。具体来说， @ehlers2022pricing 使用 2006 年至 2015 年表示巴黎协定之前的时期，而 @kleimeier2018carbon 使用了 2007 年至 2013 年的样本。不同的是， @delis2019being 根据是否拥有化石燃料储量对高风险和低风险公司进行分类。
>
> 另一组研究基于特定国家。 @chen2012pricing 关注美国债券市场，发现电力行业的排放率和到期收益率利差之间存在显着的正相关关系。最近， @jung2018carbon 证实了 2009 年至 2013 年间未能响应 CDP 的澳大利亚公司的历史碳强度（以范围 1 排放量除以销售收入衡量）与债务成本之间存在显着的正相关关系。有趣的是，增加的惩罚如果企业表现出碳风险意识，成本就可以抵消。此外， @maaloul2018effect 使用 2012 年至 2015 年间的加拿大公司样本，发现碳排放总量和排放强度都会增加债务成本。 @kumar2006 在 2011 年至 2014 年期间调查了印度公司，发现直接碳排放水平较高的公司的债务成本较高。然而， @zhou2018carbon 并没有发现碳风险与债务成本之间存在正相关关系。 反而得出不同的结论。他们表明，碳风险与债务成本之间的关系对于高碳行业的中国私营企业而言是 U 形的。结果的差异可能是由于碳风险估计的差异。 @zhou2018carbon 将碳风险定义为基于企业对​​碳排放的惩罚的有序变量，而该领域的其他研究更倾向于使用碳排放或碳强度来定义碳风险。
>
> 总之，该领域的作者采用了不同的碳风险和债务成本措施来分析这两个概念之间的关系，并得出大致相同的结论：碳风险增加了企业的债务成本。在表 2 中，我们概述了每篇文章中如何衡量风险和成本，以及估计关系的方向、样本选择、时间段和文章引用。

### 5 碳风险、财务绩效和公司价值

> 本节回顾了关于碳风险对公司财务业绩和价值影响的文献。财务绩效和价值通常以两种方式衡量：基于会计的绩效（例如，ROA、ROE）和基于市场的绩效（例如，股票回报、市场价值、托宾方程）。自从我们讨论了碳排放与股票回报之间的关系在 4.1 节中，我们不会在本节中再次这样做。在传统的公司金融理论中，公司的唯一目标是股东价值最大化。减少环境破坏的活动会产生额外成本，并使企业处于竞争劣势[@aupperle1985empirical]。然而，正如相关文献所证明的那样，一些经济机制可以推动碳绩效与公司价值之间的正相关关系[@busch2018corporate] 。首先，根据波特假说，虽然环境监管可能涉及额外成本，但它也可以为企业的研发提供动力，鼓励企业使用新技术来增加生产和利润[@yan2020impact]。其次，企业参与碳减排活动可以提高它们的声誉，赋予它们竞争优势，并最终实现碳排放和财务绩效的双赢局面。此外，由于环境偏好，投资者可能会给予碳绩效更好的公司更高的估值[@dam2015toward] 。
>
> 在实证分析中，大多数研究证实了碳风险对公司绩效和价值的负面影响。 @busch2011hot 对 2010 年至 2016 年间的 32 项研究进行了荟萃分析，表明碳排放量与企业的财务业绩呈负相关。 @nguyen2020carbon 发现，与非污染企业相比，澳大利亚的污染企业（碳密集型行业的公司）出现负净收入的可能性更高，托宾 q 值更低，ROE 也更低。从 2003 年到 2010 年，有 362 家日本公司，Lee 等人。 @lee2015impacts 发现碳排放显着降低了企业的托宾 q 和 ROA。 @trinks2020efficiency 等人从不同的角度得出了一致的结论, 根据 2009 年至 2017 年 1572 家公司的全球样本，发现碳效率高的公司具有出色的短期盈利能力 (ROA)。@busch2018corporate 证实，具有出色企业环境绩效（较低碳强度）的公司具有更高的托宾的 q。以中国制造为例公司作为研究对象，@yan2020impact 还发现，良好的企业碳绩效有助于提高托宾 q。此外，他们发现披露碳信息的公司的效果更为突出。
>
> 另一组研究证实了碳风险与市场价值之间的负相关关系。 @griffin2017relevance 表明，碳排放对标准普尔 500 指数中的公司造成每吨 79 美元的市场隐含股权折扣，大约是市值的 0.5%。 @matsumura2014firm 认为，资本市场为碳风险定价并惩罚企业的碳排放量，每增加 1000 公吨碳排放量，企业价值平均减少 212,000 美元。 @clarkson2015valuation 表明碳排放量与市场价值之间存在显着的负相关关系。此外，他们指出，碳排放量只会影响排放量超过碳配额的公司的公司估值，如果公司的碳强度低于其行业竞争对手，则可以减轻负面影响。 @choi2021 分析了 2008 年至 2015 年间富时全球股票指数系列中最大的 500 家公司，发现公司的碳排放量与其市值显着负相关。他们进一步表明，碳排放的负面影响对于拥有国家碳交易计划和严格环境法规的国家的公司更为明显。@saka2014 研究了日本市场并得出了类似的结论：碳排放量与股权市场价值呈显着负相关。
>
> 然而，其他文献表明碳绩效与财务绩效之间的关系是非线性的。例如， @misani2015 提出倒 U 形关系，发现当公司的碳绩效（负行业调整后的碳强度）处于中间时，公司具有最高的托宾 q。此外，[@tatsuo2010 、 @trumpp2017too 、 @lewandowski2017corporate 提出了碳排放（碳绩效）与财务绩效之间的曲线关系。
>
> 总之，对于碳风险与企业绩效（价值）之间的关系，学者们尚未达成共识。大多数（但不是全部）研究表明，公司的碳风险与财务业绩或公司价值之间存在负相关关系。然而，即使在得出相似总体结论的研究中，有些研究的详细结果也不一致。例如， @busch2011hot 发现该公司的碳强度与其托宾 q 具有显着的负相关关系，但与其 ROA 或 ROE 没有显着相关性。相比之下， @lee2015impacts 发现碳排放显着降低了 Tobin'sq 和 ROA。总的来说，研究结果差异的原因可能是方法论的差异，例如是否以及如何解决反向因果关系和其他内生性来源。另一个需要调查的问题是研究结果的差异是否是由于测量选择的差异造成的。正如 @busch2018corporate 所述，基于相对排放量的碳风险可以显着影响公司的财务业绩，而由绝对排放量衡量的碳风险与财务业绩无关。此外，碳绩效似乎与基于市场措施的财务绩效比基于会计措施的财务绩效有更强的联系。表3详细列出了每篇文章中碳风险和企业绩效（价值）的衡量指标，并指出了它们之间的相关性。

### 6 碳风险和企业决策

> 鉴于资本市场已将碳风险考虑在内，企业可能会通过操纵某些内部决定。最近，一些学者研究了碳风险敞口是否会影响公司的财务报告决策。 @amin2021carbon 调查公司的碳风险敞口是否影响管理者的盈余管理决策。他们发现碳排放与实际盈余管理 (REM) 之间存在显着的正相关关系，表明管理者选择报告强劲的财务业绩以抵消高碳排放的负面影响。作者进一步发现，公司治理、区域环境法规和机构投资者的投资方向会影响这种关系。此外，@lemma2020corporate 确认具有较高碳风险敞口（碳强度）的南非公司倾向于从事盈余管理活动，从而降低财务报告质量。在代理理论的支持下， @velte2021environmental 发现碳绩效降低了应计盈余管理 (ACC) 但增加了 REM。作者认为，管理者将碳战略用作掩盖盈余行为的一种手段，并倾向于通过从 ACC 转向更不透明的 REM 来采用隐藏的盈余管理政策。
>
> 另一组研究表明，碳风险也会影响企业的财务选择。 @ngwakwe2013carbon 发现，如果企业参与碳减排计划，他们更愿意支付更高的股息，这表明企业的碳减排量与其股息之间存在显着的正相关关系。同样， @balachandran2018does 研究了碳风险对澳大利亚上市公司股息政策的影响。实证结果证实，在《京都议定书》批准后，高排放部门的公司支付股息的可能性较小，而且股息支付率低于低排放部门。他们将结果归因于这样一个事实，即碳风险越高，未来回报的不确定性就越高，因此，股息（概率）越低。此外，由于澳大利亚独特的税收环境在归集税制和传统税制下同时运作，他们研究了两种不同税收环境之间碳风险效应的异质性。他们发现归集税收环境的重要性仅在于碳风险对股息支付率的影响，而不是支付决策。
>
> @nguyen2020carbon 再次将澳大利亚批准《京都议定书》视为外生事件，研究了碳风险对企业资本结构的影响。他们发现，在京都议定书之后，高碳排放国显着降低了账面杠杆和市场杠杆，特别是对于财务受限的公司而言，这表明碳风险是公司资本结构的重要决定因素。此外， @bose2021does 发现碳排放会影响公司的收购决策，高碳排放者更愿意收购外国公司而不是国内公司来外包他们的碳风险。此外，只有目标位于国内生产总值较低或环境、监管或治理标准薄弱的国家时，碳排放量才会影响收购方的选择。

### 7 进一步研究

> 整体文献回顾发现，目前对企业风险和碳风险的研究不足，需要在该领域进一步研究。在本节中，我们将讨论当前研究中的遗留问题。
>
> 第一个有前途的研究方向是碳信息披露的客观性。碳排放数据是后续研究的基础。但是，由于企业一直自愿披露其碳排放信息，目前尚无客观统一的披露标准；这大大降低了数据的一致性和可比性。因此，未来的研究可以致力于制定碳信息披露标准，并将碳信息与财务、会计和管理领域相结合。
>
> 其次，碳风险文献中的一些不同结果似乎与碳风险衡量方式的差异有关。例如，一些研究将碳风险定义为碳排放量，而另一些研究则使用碳强度作为碳风险的替代指标。同样，在排放数据方面，一些研究侧重于直接碳排放，而另一些研究则使用总排放量，包括直接和间接碳排放。碳风险测量的差异是否驱动实证结果仍然是一个悬而未决的问题。因此，很明显要提出哪个碳风险代理是合适的问题。正如 TCFD 所述，在向低碳经济转型期间，由于政策、立法、技术和市场的变化，高排放者面临碳风险。因此，有必要更深入地了解碳风险的含义以及如何选择合适的代理人。例如，大多数研究直接使用企业的碳排放作为碳风险的代理，而没有考虑气候变化是否被社会重视。如果一家高碳公司位于气候监管较低的司法管辖区，因此不会产生碳风险，那么高排放量将不能很好地代表碳风险。
>
> 第三，虽然大多数研究表明碳风险与股权资本成本之间存在负相关关系，但碳溢价仍然没有一致的结论。一些学者甚至否认碳溢价的存在[18]。因此，协调不一致的发现仍然是未来工作中需要解决的一个重要问题。例如，需要更多证据来说明不同时期和地区的不同监管严格程度在多大程度上导致了不同的结果。
>
> 第四，关于碳风险与债务成本之间的联系，大多数研究基于银团贷款市场（如贷款利率）或财务报表信息（如利息支出除以平均有息债务），但仅一些研究侧重于债券市场。这为未来研究债券发行中的碳定价提供了机会。
>
> 第五，关于碳风险在企业绩效和价值中的作用，学者们尚未得出一致的结论。来自不同样本的证据证明它们之间呈负相关或无线性相关。尽管一些研究已经证明这些结果的差异是由于不同的测量指标造成的，但还需要更深入的探索。最后，研究人员在研究碳风险在企业融资中的作用时，仍然需要面对建立因果关系的挑战。需要更多的方法来解决这个问题。

### 8 结论

> 在本文中，我们旨在全面概述碳风险与不同类型的公司绩效之间的联系，例如公司风险、资本成本（包括股权和债务）、财务绩效、公司价值和公司决策。通过文献回顾，我们发现虽然近2年相关文献不断增多，并逐渐走向各种主题，但这些领域在学术研究中仍处于新兴阶段。此外，我们强调，某些主题的研究结果是稳定和确凿的，但其他主题的结果仍有争议。例如，虽然越来越多的 Wang 等人。 Carbon Neutrality (2022) 1:6 第 8 页，共 1 页 证据表明碳风险会降低公司价值，这一建议在文献中仍有争议。因此，研究人员可以进一步探索这些差异，以更好地理解结果的经济驱动因素。
>
> 本文的目标基本上是双重的。首先，我们希望让企业管理者、决策者和投资者了解碳排放和碳风险对个体企业的影响，促使他们更加关注碳风险和碳信息披露。其次，我们希望让读者更全面地了解企业融资中的碳风险，从而激发对这一重要且令人兴奋的话题的更多研究。

### 参考文献
