---
title: 噪声无处不在
author: 薛英杰
date: '2020-09-20'
slug: 噪声无处不在
categories:
  - research
tags:
  - research
---

> 噪声，无时无刻不出现在我们身边。自然界的声音、金融市场的信息、经济周期的波动都包含了或多或少的“噪声”，它对世界和人们看世界的视角影响深远，为我们的生活带来了意外，也送来了惊喜，使我们处于一个不确定的世界。有时候，我们喜欢它，有时候也憎恶它，总之，我们离不开它，也消灭不了它。这是我读了Fischer Black的噪声，最直观的一个感受。今天呢，就来总结一下他宏伟巨著背后的深刻思想。


## [Noise](https://doi.org/10.1111/j.1540-6261.1986.tb04513.x)

     Fischer Black
     1986 The Jounal of Finance
   
Black先生认为，大量小事件中的噪声往往使一个非常有力的驱动因素。也就是说，多数小事情都是由于噪声所致。在金融市场中，噪声使交易成为可能，让我们看到了金融资产的价格波动。但是，噪声在某种程度上引起了市场无效，而其又阻止我们利用这种无效。在经济中，各生产部门关于未来技术和偏好不确定相关的噪声形成了经济周期，其又会抵制政府的政策干预。不需要遵循任何理性规则期望形式的噪声引起了通货膨胀，这是以前在金本位和固定汇率制度时期没有的现象。大多数情况下，噪声在理论和实证上是很难检验的，使得我们被迫在黑暗中前进。


噪声让我们的不完整地观察到现象背后的本质，阻止我们认识股票组合的期望收益，认识货币政策是否影响了通货膨胀，以及认识任何我们想做好的事情。在经济模型中，噪声是还没有出现的信息，是关于经济部门内或部门之间对未来需求和供给条件的不确定性。当信息出现的时候，这些部门才知道技术与偏好匹配的正确性。

### 金融市场中的噪声


> 噪声成就了金融市场，却造就了他的缺陷。

在金融市场中，噪声与信息相对。一方面，人们进行普通的信息交易，期望从交易中获取收益；另一方面，人们像交易信息一样交易噪声，如果交易噪声的人们期望从噪声交易中获取收益，他们的行为是错误的。但是，噪声交易对于市场流动性（*流动性是市场的变现能力，也就是想买时能买到，想买时能卖出，买不到或卖不出的市场是缺乏流动性的市场*）来说是必不可少的。


如果没有噪声交易者，在单个资产上的交易将非常少，人们会直接或间接地持有单个证券，并很少交易。**噪声交易者的存在意味着投资者对资产的估值持有不同的看法，即使有的看法可能是错误的，但这为交易成功创造了可能性**。为了改变广泛的市场风险暴露，人们会交易共同基金等组合产品，他们将没有理由来交易单个公司的股票，而拥有公司信息的人们将会交易公司的股票。如果一个交易信息的人想交易股票，要实现这个需求就需要另外一个拥有信息的人站在交易的对手方，那么两个人都拥有信息？从这个角度来讲，明白人都知道，两方中必定又一方错了，犯错的一方面将会减少交易，他就是没有信息的一方，也就是所谓的“噪声交易者”。

而且，如果单个证券由于没有噪声交易者而不可交易，也就不会又共同基金等衍生品的出现，因为他们没有定价基础。所以，金融市场的整个结构取决于单个公司证券的市场流动性。

> 噪声交易是像信息一样交易噪声。

噪声交易是金融市场不可或缺的元素，虽然从客观的角度来讲，噪声交易者不交易最好，但交易噪声的人们是自愿交易噪声的，**或许，他们认为他们交易的噪声就是信息，或许，他们仅仅是想交易而已（脑子抽风了）。**噪声交易者的存在是在为信息买单，这激励了投资者付出辛劳去挖掘公司信息，从而提升了市场的定价效率，大多时候，噪声交易者就是亏钱的投资者，而信息交易者往往是赚钱的投资者。

> 噪声交易越多，市场流动性越有流动性。

正因为噪声交易者的存在，使交易变得频繁，让我们观测到价格变动。但是，噪声交易将噪声融入股票价格，使股票价格中既包含了信息交易者交易的信息，也包含了噪声交易者者交易的噪声，随着噪声交易量增加，资产价格中包含了很多噪声，使得信息交易者将有利可图。信息交易量的增加并不意味着更有效的价格，因为更多的信息交易者进来，他们会持有大量头寸，对信息支付更高的价格，致使市场流动性缺乏，从而降低价格效率。所以，市场对流动性的需求导致了信息效率低下。


> 信息交易者不会持有足够大的头寸来消除噪声

一方面，虽然信息使信息交易者占有优势，但并不能保证其获利，持有较高的头寸意味着冒着较大的风险，所以，投资者持有头寸有一个限制。另一方面，信息交易者并不一定能保证他们交易的就是信息而不是噪声，万一他们掌握的信息早已在资产价格中反应了呢？虽然组合收益是期望收益的噪声估计，甚至在使用市场模型调整后，也很难说明白信息交易者占有优势。同样地，也很难说明白噪声交易者通过交易会亏损。关于谁是信息交易者或噪声交易者有很多是模糊不清的。

> 噪声交易者融入价格的噪声是逐渐累积的

在某种意义上，噪声交易者像醉汉一样，不知不觉中离起点越来越远，虽然有时信息交易者会研究并采取行动来抵消这种不理性，但只有当股价离价值越远时，信息交易者会变得越来越激进，许多信息交易者持有大量头寸进入市场，来修复这种不理性，他们可能进行兼并重组，杠杆收购等。而且，许多价值的估计都是包含噪声的，所以我们绝不知道股价将走向何方。

> 价值是不可观测的，无信息事件频繁出现影响股价

比如，大盘指数调整会引导投资者交易，上市公司股票更名也会引起投资者购买该股票，同样，A股与港股上市的同一个公司股价变化差异较大

> 股价的短期波动大于价值的短期波动

由于信息与噪声独立，信息引起的股价波动反应了公司价值的变化，而噪声引起的股价波动反应了与价值无关的价格变化，总的，来说价格的波动要大于价值的波动。且公司价值的波动受公司层面信息出现频率的影响。


总之，噪声创造了交易获利机会，又使获利机会难以被利用。

### 经典语句表达

> 1. Noise trading is trading on noise as if they were information 噪声交易是像信息一样交易噪声

> 2. What if the information they have has already been reflected in price? 万一他们掌握的信息已经反应在价格中呢？ 