---
title: 噪声交易与定价效率文献梳理
author: 薛英杰
date: '2020-10-05'
slug: 噪声交易与定价效率文献梳理
categories:
  - research
tags:
  - research
---


读[Black(1986)](https://doi.org/10.1111/j.1540-6261.1986.tb04513.x)噪声这篇文章时，已经发现噪声交易的存在具有两面性。最经典的是，他提到“噪声成就了金融市场，却造就了金融市场的缺陷”，并将噪声交易分为两类，一类是流动性交易，一类是不知情交易。流动性交易者对市场充满信任,愿意以一定的市场价格买入或卖出任意数量的风险资产,这类噪声交易者是证券市场赖以存在的基础。不知情交易者没有掌握关于风险资产真实价值的信息, 却误认为自己拥有正确的信息,因此其交易行为给证券市场带来了一定程度的摩擦, 使资产价格时常偏离其真实价值 。所以不知情的噪声交易者的存在降低了定价效率。


## [噪声交易与市场质量](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2008&filename=JJYJ200809008&v=zxC%25mmd2Bk8Gc95o30TBBlZi2d65NNPVnmFsjN%25mmd2FyEug5TM2Kk1u8A3nlX2k737I%25mmd2B5jTG%25mmd2F) ^[苏冬蔚.噪声交易与市场质量[J].经济研究,2008,43(09):82-95.]

    经济研究 2008 苏冬蔚
    
### 摘要

本文通过行业、规模、负债和成长能力的配对,建立起32家上证50成份股
上市公司的控制样本,然后运用合理的计量方法,首次估计出符合我国股市微观结构的噪声交易高频时间序列,在此基础上深入分析噪声交易与信息不对称、流动性 、波动性和有效性等市场质量指标之间的经验关系,发现:我国股市私人信息具有较高的相关性和持久性;噪声交易提高了交投活跃程度,同时却扩大了执行成本和价格波动幅度;噪声交易与信息不对称的关系不大;噪声交易使实际价差缩小, 进而削弱了市场有效性。由此可见,噪声交易是一把“双刃剑”, 只有继续改革价格形成机制、增强价值投资力量、引导长期资金入市、完善信息披露制度并强化交易监控, 才能进一步提高我国股市的质量。

### 研究问题

> 我国证券市场经过十多年的发展已颇具规模,但长期以来市场的主要参与者是中小投资者( 散户) , 基于理性投资信念的市场运作手法还不成熟,过度投机、内幕交易和股价操纵等问题异常突出, 政府政策对市场也存在巨大影响,市场上信息不对称程度大且噪声交易多 。如何定量分析噪声交易并深入揭示出噪声交易与流动性、波动性、信息不对称和有效性等市场质量指标之间的关系,从而为有关机构和证交所提供科学合理的政策依据已成为一个亟待研究和解决的问题。

### 相关文献

> **噪声交易改善市场质量的研究**

> 1、[Kyle(1985)](https://www.jstor.org/stable/1913210) ^[Kyle A S. Continuous auctions and insider trading[J]. Econometrica: Journal of the Econometric Society, 1985: 1315-1335.]假设市场上存在一名知情交易者、多名噪声交易者和一名做市商, 知情交易者拥有资产真实价值的私人信息,而噪声交易者掌握的信息与资产真实价值无关, 却误把噪声当作有用的信息, 或纯粹进行流动性交易, 同时, 做市商不知道资产的真实价值,但却能收集到资产价格和成交量变化所释放出的信息;在知情交易者没有竞争压力等前提下,知情交易者采取分散交易次数的方式, 试图隐藏其私人信息,以获取最大的利润;随着噪声交易者数量增加, 知情交易者更有意愿积极参与交易,此时资产价格就更能揭示出私人信息, 因此噪声交易能提高市场有效性。

> 2、[Glosten and Milgrom(1985)](https://doi.org/10.1016/0304-405X(85)90044-3) ^[Glosten L R, Milgrom P R. Bid, ask and transaction prices in a specialist market with heterogeneously informed traders[J]. Journal of financial economics, 1985, 14(1): 71-100.]认为,在信息不对称下,如果噪声交易的比重增加, 逆向选择成本减小,做市商就会降低买卖报价价差,因此噪声交易能减少信息不对称并提高市场流动性。

> 3、[Easley 等( 2002)](https://doi.org/10.1111/1540-6261.00493) ^[Easley D, Hvidkjaer S, O'hara M. Is information risk a determinant of asset returns?[J]. The journal of finance, 2002, 57(5): 2185-2221.] 、[Gur 和 Stanzl( 2004)](https://doi.org/10.1111/j.1468-0262.2004.00531.x) ^[Huberman G, Stanzl W. Price manipulation and quasi‐arbitrage[J]. Econometrica, 2004, 72(4): 1247-1275.] 以及 [Wang ( 2005)]()^[Wang F A. Trading on noise as if it were information: Price, liquidity, volume and profit[R]. working paper, Rice University, 2002.]将市场微观结构和行为金融理论结合起来,在假设噪声交易者对所掌握的信息精度显得过于自信而知情交易者在不同时期采取不同投资策略(惯性或反转策略) 的基础上, 推导出不同的线性贝叶斯—纳什信息均衡模型,再通过数字模拟, 对模型进行比较静态分析,发现噪声交易越多,市场流动性就越大,价格形成过程更加有效, 同时, 知情交易者获利也就越多 。

> 4、[Easley 等( 1996)](https://doi.org/10.1111/j.1540-6261.1996.tb04074.x) ^[Easley D, Kiefer N M, O'hara M, et al. Liquidity, information, and infrequently traded stocks[J]. The Journal of Finance, 1996, 51(4): 1405-1436.] 根据日间买卖订单的数量、成交价及其变化,构建出一个知情交易概率指数, 发现 NYSE 在开盘期间换手率高的股票知情交易少,表明噪声交易有助于提高交投活跃程度并降低信息不对称 。

> 5、[Berkman 和 Eleswarapu(1998)](https://doi.org/10.1016/S0304-405X(97)00048-2) ^[Berkman H, Eleswarapu V R. Short-term traders and liquidity:: a test using Bombay Stock Exchange data[J]. Journal of financial Economics, 1998, 47(3): 339-355.]运用事件研究法,发现交易制度的变化对噪声交易和市场流动性有显著影响, 如印度监管当局为抑制过度投机而在1993 年12 月废除股票远期交易体系,导致噪声交易减少,与此同时,1994年股市日均换手率下降了72%,表明噪声交易与市场流动性成正比。

> 6、[Chakravarty 等( 2004)](https://doi.org/10.1016/S0022-0531(03)00101-7) ^[Chakraborty A, Yılmaz B. Informed manipulation[J]. Journal of Economic theory, 2004, 114(1): 132-152.] 研究了NYSE和 CBOT( 芝加哥期货交易所) 60 只交投最活跃的期权,发现保证金交易所带来的杠杆效应能吸引噪声交易并加速标的资产的价格发现, 表明噪声交易有助于改善市场效率。

> **噪声交易降低市场质量的研究**

> 7、[Admati( 1988)](https://doi.org/10.1093/rfs/1.1.3) ^[Admati A R, Pfleiderer P. A theory of intraday patterns: Volume and price variability[J]. The Review of Financial Studies, 1988, 1(1): 3-40.] 提出了一个完全竞争状态下的理性预期均衡模型, 发现噪声交易的存在使市场必须同时利用价格和私人信息才能完成对交易者后验信念的修正并准确传递交易者的需求函数,换言之,单纯依靠价格无法如实反映所有的私人信息, 因此噪声交易降低了市场有效性 。

> 8、[Palomino( 1996)](https://doi.org/10.1111/j.1540-6261.1996.tb04079.x) ^[Palomino F. Noise trading in small markets[J]. The journal of finance, 1996, 51(4): 1537-1550.] 提出了一个不完全竞争状态下的纳什均衡模型,发现当知情交易者无法预测噪声交易者的信念或两者的信念相差过大时,知情交易者将不会与噪声交易者进行交易,而且在最严重的情况下,市场上没有任何交易,因此价格无法充分揭示出所有投资者的私人信息。

> *9、[Stoll( 1989)]( https://doi.org/10.1111/j.1540-6261.1989.tb02407.x) ^[Stoll H R. Inferring the components of the bid‐ask spread: Theory and empirical tests[J]. the Journal of Finance, 1989, 44(1): 115-134.] 指出, 做市商必须不断调整报价, 才能维持订单平衡, 噪声交易会降低做市商的存货水平,迫使做市商提高买卖价差,因此噪声交易降低了市场流动性 。*

> *10、Madhavan( 1992)认为,噪声交易增加了知情交易者和做市商面临的不确定性,致使交易频率缩小、买卖价差增加以及市场流动性减小。*

> 11、[Handa 等( 2003)](https://doi.org/10.1016/S1386-4181(02)00041-1) ^[Handa P, Schwartz R, Tiwari A. Quote setting and price formation in an order driven market[J]. Journal of financial markets, 2003, 6(4): 461-489.]认为,指令驱动交易制度下买卖价差是投资者类别和信息不对称的函数, 不知情交易者比例上升,买卖价差随之扩大,市场流动性就下降。

> 12、[De Long 等( 1991)](https://doi.org/10.1086/261703) ^[De Long J B, Shleifer A, Summers L H, et al. Noise trader risk in financial markets[J]. Journal of political Economy, 1990, 98(4): 703-738.]认为,知情交易者受生命周期、流动性需求和短期评价等客观因素制约只能从事有限的套利活动,从而给噪声交易者提供了较大的生存空间, 同时, 噪声交易者往往对信息过度反应或反应不足,导致资产价格过度波动。

> 13、[Campbell 和 Kyle(1993)](https://doi.org/10.2307/2297810) ^[Campbell J Y, Kyle A S. Smart money, noise trading and stock price behaviour[J]. The Review of Economic Studies, 1993, 60(1): 1-34.]发现,资产收益的波动程度与噪声交易者的比例呈正相关关系。

> 14、[Vayanos( 2001)](https://doi.org/10.1111/0022-1082.00321) ^[Vayanos D. Strategic trading in a dynamic noisy market[J]. The Journal of Finance, 2001, 56(1): 131-171.]通过对大额交易者和噪声交易者动态投资策略的研究发现, 适度的噪声交易有助于风险共担,促使大额交易者分散订单,以一定的节奏和噪声交易者不断进行交易和信息反馈,促进价格发现,但过度的噪声交易却迫使大额交易者迅速下单, 以期领先于市场, 致使价格过度波动。

> 15、[Chakraborty和Yilmaz(2004)](https://doi.org/10.1111/j.1540-6261.2004.00661.x) ^[Chakravarty S, Gulen H, Mayhew S. Informed trading in stock and option markets[J]. The Journal of Finance, 2004, 59(3): 1235-1257.]发现噪声交易的存在使知情交易者有动机进行错误投资并承担由此所造成的短期损失,以迷惑和吸引更多的噪声交易并获取长期利润, 因此噪声交易、市场操纵及信息不对称均为内生变量,它们之间的相互作用使价格无法及时揭示出私人信息, 导致市场有效性减弱。

> 16、[Damodaran 和 Liu( 1993)](https://doi.org/10.1093/rfs/6.1.79) ^[Damodaran A, Liu C H. Insider trading as a signal of private information[J]. The Review of Financial Studies, 1993, 6(1): 79-119.]以房地产评估师公布的投资价值报告为事件, 发现 NYSE 的 54 家房地产投资基金( REIT) 在公告后换手率上升 、买卖价
差扩大且信息不对称增加 。

> 17、[Keim 和Madhavan( 1996)](https://doi.org/10.1093/rfs/9.1.1) ^[Keim D B, Madhavan A. The upstairs market for large-block transactions: Analysis and measurement of price effects[J]. The Review of Financial Studies, 1996, 9(1): 1-36.] 使用 1985 —1992 年间 NYSE、AMEX 和 NASDAQ 上发生的 5625笔大额交易数据,发现在大额交易发生后,市场上噪声交易显著增加, 价格波动幅度从 1.45 %上升到 8 %。

> 18、[Brown( 1999)](https://doi.org/10.2469/faj.v55.n2.2263) ^[Brown G W. Volatility, sentiment, and noise traders[J]. Financial Analysts Journal, 1999, 55(2): 82-90.]使用美国个人投资者协会通过问卷调查得出的投资者情绪指数( 投资者对牛市或熊市的总体认定)衡量噪声交易,发现投资者对市场前景过于乐观或悲观, 都会导致价格波动幅度上升。

> 19、[Chordia 和 Subrahmanyam ( 2004)](https://escholarship.org/uc/item/34k8f3pv) ^[Chordia T, Subrahmanyam A. Order imbalance and individual stock returns[J]. 2000.] 利用 1993 —1998 年间NYSE-TAQ 数据, 发现噪声交易是NYSE委托单失衡的主要原因,即噪声交易使特定时间内的买单( 或卖单) 数量远远超过卖单(或买单)数量,同时,委托不平衡引起日内收益率呈显著的负自相关性, 表明市场的价格发现效率下降。

### 结论

> *1、噪声交易增加执行成本并扩大价格波动幅度,对市场质量具有一定的负面影响。*

> *2、根据VAR模型和Granger因果检验的结果,我国股市的噪声交易具有较强的外生性, 受市场波动性 、信息不对称和交易成本的影响不大。*

> 3、知情交易者往往能事先取得关于资产价值的重要信息并进行内幕交易, 导致市场上存在严重的信息不对称,同时,信息不对称影响交易成本,而且私人信息具有较高的相关性和持久性 。