---
title: 被动投资与股票定价效率的文献梳理
author: 薛英杰
date: '2020-12-27'
slug: 被动投资与股票定价效率的文献梳理
categories:
  - research
tags:
  - research
---


## [Passive Ownership and Price Informativeness](https://marcosammon.com/images/sammon_jmp.pdf)

     MARCO SAMMON
     
     Job Market Paper
     
### 摘要

> 虽然在过去30年中，被动持股快速增长，但关于被动持股为什么能影响股价信息含量以及如何影响股价信息含量。这篇文章为回答这个问题提供了新答案，检验了被动持股改变如何影响投资者收集信息。我们建立了一个被动持股如何影响投资者收集信息以及投资者如何在系统风险和特质风险上分配有限注意的模型。该模型通过数据中可观察到的交易量、收益和波动将投资者的认知决策和股价信息含量联系起来，受该模型的启发，建立了三个股价信息含量的度量，他们在过去三十年是递减的。在横截面上，被动持股增加显著与股价信息含量显著地负相关。为了探索因果关系，我们证明了在指数调整引起的拟外生被动持股增加后股价信息含量是下降的。

### 研究问题

> 在理论和实证文献中，关于被动持股如何影响股价信息含量并没有一致的结论，本文回答了为什么被动持股能影响股价信息含量以及如何影响股价信息含量。

> **核心观点：** <span style="color:red">给定一个机械的交易规则，从直觉上讲，随着越多的投资者变成被动投资者，将有更少的投资者从事基本面研究，导致股价信息含量降低。这与过去30年盈余公告前，股价信息含量较低的事实一致。</span>

### 研究思路

> 为了刻画被动投资和信息效率的关系，我们需要明确股价信息含量的测度，并理解其作用机制。**由于被动投资是基于机械的规则，投资者更像非知情交易者，随着非知情投资者的比例增加，股价信息含量将降低。**

> 被动持股并不意味着无信息，被动基金被大量主动投资者持有，被动持股可能影响信息获取的群体以及他们获得什么信息。ETF持有者可能是寻找特定系统风险因子的机构投资者，ETF的出现可能是投资者了解更多的系统性风险。大多数投资者通过ETF来主动管理资产，只有30%的ETF投资者在做被动投资。例如： in reference to Global X’s
ETF offerings, its former CEO said, Hedge funds tend to use our ETFs as a tactical play
to get in and out of segments that are difficult for them to access directly. Greece is a good
example. GREK has seen a lot hedge fund trading

> 如果投资者是知情交易者，他们厌恶风险，由于特质风险可以被分散掉，他们更关注系统性风险。因此，他们既可以利用ETF交易系统性风险，也可以来交易特质风险。（1）当ETF可以利用时，投资者可以直接基于系统性风险进行交易，他们更愿意了解更多系统性风险相关的信息，进而进行择时交易。（2）当ETF可以利用时,投资者可以利用ETF对冲系统性风险，进而从事个股层面的套利。

> **随着信息不对称程度增加，非知情交易者因逆向选择问题而不愿意交易，他们担心他们的交易对手是掌握更多信息的投资者，这样他们做出的任何交易都是最糟糕的交易。** 

### 相关文献

> 1、被动投资通过增加系统信息提高了股价的信息含量（[Glosten et al. (2016)](https://www.rhsmith.umd.edu/files/Documents/Departments/Finance/fall2015/glosten.pdf)^[Glosten L, Nallareddy S, Zou Y. ETF trading and informational efficiency of underlying securities[J]. Unpublished working Paper, 2016.]; [Cong and Xu (2016)](https://dx.doi.org/10.2139/ssrn.2800590)^[Cong L W, Xu D. Rise of factor investing: asset prices, informational efficiency, and security design[C]//29th Australasian Finance and Banking Conference. 2016.]）

> 2、被动持股增加了非基本面波动，导致股价信息含量的降低（[Ben-David et al. (2018)](https://doi.org/10.1111/jofi.12727)^[Ben‐David I, Franzoni F, Moussawi R. Do ETFs increase volatility?[J]. The Journal of Finance, 2018, 73(6): 2471-2535.]; [Kacperczyk et al. (2018)](https://dx.doi.org/10.2139/ssrn.3137803)^[Kacperczyk M T, Nosal J B, Sundaresan S. Market power and price informativeness[J]. Available at SSRN 3137803, 2018.]）

> 3、[Grossman and Stiglitz(1980)](https://www.jstor.org/stable/1805228)^[Grossman S J, Stiglitz J E. On the impossibility of informationally efficient markets[J]. The American economic review, 1980, 70(3): 393-408.]将价格效率定义为基于条件变量的股票价格方差。

> 4、在股票市场，非知情交易者更喜欢延迟交易到不确定性被解除（[Admati and Pfleiderer，1988](https://doi.org/10.1093/rfs/1.1.3)^[Admati A R, Pfleiderer P. A theory of intraday patterns: Volume and price variability[J]. The Review of Financial Studies, 1988, 1(1): 3-40.]； Wang，1994）


### 研究结论

> 1、被动持股影响投资者变成知情交易者和知情投资应该了解什么。
 
> 2、被动投资者使投资者了解公司特质更有吸引力，并允许投资者对冲他们的系统性风险。

> 3、被动持股使投资者更容易在系统风险上押注，使非知情交易者更易实现分散。

> 4、本文发现过去30年股价平均信息含量在递减，在公司层面，被动投资导致股价信息含量降低。

> 5、被动持股与股价信息搜集递减相关，这是因为投资者担心反向因果。


## [Passive Investors, not passive ownership](https://doi.org/10.1016/j.jfineco.2016.03.003)

    Ian R. Appel, Todd A. Gormley, Donald B. Keim
    
    Journal of Financial Economics
    
### 摘要

> 被动的机构投资者是美国股票市场的重要组成部分，为了检验被动投资者是否影响了公司治理以及通过什么机制影响了公司治理，我们建立了被动基金持股变化和罗素指数1000与2000指数之间的联系。我们发现被动共同基金影响公司的治理选择，导致了更多的独立董事，收购护城河消除和更加公平的投票权。被动投资者通过他们投票集团发挥作用，与观察到治理差异增加了公司价值一致，被动持股与企业长期业绩改善相联系。

### 研究问题

> **近三十年来，被动投资快速增长，带来了一个不可回避的问题：被动投资导致持股分散，如何才能有效低监督管理者？**

> 一些人担心被动投资缺乏监督大的分散组合的动力和资源，懒投资者市场份额的增加削弱了公司治理，损害了公司业绩，而另一部分人认为被动投资并不等于被动持股。所以我们来检验被动的机构投资者是否影响了公司治理结构，最终影响了公司业绩。

> <span style="color:red">(1)为什么被动投资增长可能削弱公司治理和表现？</span>

>  首先，机构投资者可能缺乏监督管理者的激励，被动基金目的在于履行一个比较基准的业绩表现，不像主动型基金，他们没有提高单个股票表现的动机。其次，被动投资者可能难以对管理层施加影响，通过最小化与跟踪指数的偏离权重，被动的机构投资者往往缺乏非被动投资者影响管理层的渠道和方法，例如累积持股和减少头寸。第三，给定一个分散的组合，被动投资者可能没有足够的资源来研究和监督组合内每一个公司。

> <span style="color:red">(2)为什么被动投资增长可能提高公司治理和表现？</span>

>  首先，被动投资的机构监督企业管理者可以提高其管理的资产价值，由于其管理的资产组合是固定，他们并不能取消他们的头寸再表现不佳的股票，只能通过加强监督上市公司管理者，这样他们更有动机加强监督，来提高组合业绩表现。其次，管理被动基金的机构可能使用其持股规模施加影响。所有机构投资者有一个受托责任，代替股东的最优利益来投票，并且管理者更倾向于从被动投资者的角度考虑，由于主动投资者换收率较高。第三，虽然，当被动机构可能缺乏监督分散组合内每一只股票的精力时，他们可能会以低的成本有效地参与与他们认为最优的公司治理相符合的公司职责。

### 研究思路

> 我们利用罗素指数1000与罗素指数2000之间的成分股调整作为工具变量，研究了被动基金持股对公司治理结构和业绩表现的影响。具体来讲，我们使用给定年份股票是否调入罗素指数2000的虚拟变量作为工具变量，这个工具变量依赖的假设是在市值确定的情况下，股票被调入指数并不直接影响公司治理和业绩表现，而是通过被动持股影响公司治理和业绩表现。

> **被动的机构确实改变了企业公司治理问题上的投票策略，机构代理投票政策对董事会的治理的影响表现在三个方面:**（1）支持更加独立的董事会；（2）反对逆向收购；（3）反对不平等的投票权。在此基础上，我们分析了投票结果，管理层和股东意见相关的治理可能和被动投资者发挥的作用直接相关。



### 相关文献

> 1、被动的机构投资者可能被激励监督管理层，并改善市场表现，因为这样可以提高其管理的资产价值（[Del Guercio and Hawkins, 1999](https://doi.org/10.1016/S0304-405X(99)00011-2)^[Del Guercio D, Hawkins J. The motivation and impact of pension fund activism[J]. Journal of financial economics, 1999, 52(3): 293-340.]）

> 2、虽然被动的机构投资者可能缺乏监督管理分散组合中每一个公司政策选择的精力，但他们可能有效、广泛地从事低成本的监督，使公司按照他们认为最好的治理模式进行管理。（ Black, [1992](https://heinonline.org/HOL/LandingPage?handle=hein.journals/uclalr39&div=30&id=&page=)^[Black B S. Agents watching agents: The promise of institutional investor voice[J]. UCLA l. Rev., 1991, 39: 811.], [1998](https://dx.doi.org/10.2139/ssrn.45100)^[Black B S. Shareholder activism and corporate governance in the United States[J]. As published in The New Palgrave Dictionary of Economics and the Law, 1998, 3: 459-465.]）

> 3、在罗素2000指数中排名靠前股票的媒体和分析师覆盖并没有显著增加 ([Crane, Michenaud, and Weston，2014](https://doi.org/10.1093/rfs/hhw012)^[Crane A D, Michenaud S, Weston J P. The effect of institutional ownership on payout policy: Evidence from index thresholds[J]. The Review of Financial Studies, 2016, 29(6): 1377-1408.])。

### 研究贡献

> 1、我们的研究贡献了机构持股对公司治理和公司政策的影响，被动持股很少研究，但其重要性一直在上升

> 2、我们的研究和一些执行被动投资策略的养老基金相关，但其却成功地从事主动投资。

> 3、我们的研究与被动投资者可能缺乏监督管理层的意愿和能力相反。




### 研究结论

> 1、我们发现被动共同基金持股对公司治理的三个方面均有影响。被动基金持股增加与董事会的独立增加、反收购程度和投票权的对称程度相关。

> 2、我们证明了一个关键的机制，被动投资者主要通过大投票集团的权力对管理层施加影响，被动持股与管理层提议支持票的份额下降有关。说明管理者面临着一个更有争议和更专注的股东基础，并增加了治理相关股东提案的支持度。

> 3、被动投资者影响治理结果的另一种机制是促进其他投资者的积极努力。但我们并没有发现对冲基金持股事件和公司收购事件的概率随被动持股而上升。

> 4、被动投资对公司价值有正向影响，被动持股越高的公司未来价值越高，被动基金长期持股与公司ROA和托宾Q的改善相关。

> 5、被动投资者并不是被动持股者，被动基金成功地影响公司治理选择并改善了公司的长期表现。

> 6、股票被调入罗素指数2000后分析师覆盖降低


## [The effect of institutional ownership on firm transparency and information production](https://doi.org/10.1016/j.jfineco.2015.05.008)


      Audra L. Boone, Joshua T. White
      Journal of Financial Economics
      
### 摘要

> 我们罗素1000/2000指数的调整检验了机构持股对公司的信息和交易环境的影响，由于指数和基本策略，罗素2000指数排名靠前的公司比罗素1000指数排名靠后的公司机构持股比例高，指数分割点附近的公司特征类似，我们发现机构持股比例越高越高意味着更大的管理层披露、分析师跟踪和流动性，导致更低的信息不对称。指数化机构低于更低信息不对称程度的偏好有利于信息生产，提高管理层监督并降低交易成本。

### 研究问题

> 虽然机构投资者表现出异质性的投资和交易策略，但没人知道他们对信息偏好的变化如何影响信息生产和交易环境。由于一个公司的信息环境影响投资、流动性和风险，理解机构投资者影响信息环境对资本市场影响有重要的意义。

### 研究思路

> 以前的研究也证明了机构投资者持股和信息环境的关系，但这种因果关系受内生性影响，因此，机构投资者如何影响信息环境仍需要研究。为了克服这个困难，我们使用罗素1000指数和2000指数来研究机构持股如何影响一个公司的信息环境。

>  我们围绕罗素1000和2000指数切换基于两个突出的公司特征来识别外生世界，首先，门槛两侧的公司呈现了类似的特征，其次，由于每个指数是加权构建，罗素2000指数排名靠前的公司比罗素1000指数排名靠后的公司有显著高的组合权重。指数加权机制导致机构持股围绕罗素指数1000/2000的门槛变化对于公司的信息环境是外生的，但不同类型的机构持股不可能是同质的。

>  因此，接近指数顶部的公司股份被指数持有的比例更高，靠近底部的公司持股比例相对较小,为了检验效应的差异，我们基于投资组合周转率、多样化和预期投资期限将机构投资者分为三类，一类是拟指数投资者，[短期投资者(transient investor)和专业投资者（dedicated investor）](https://dergipark.org.tr/en/download/article-file/713744),来检验不同类型的持股对公司信息环境的影响。发现机构投资者持有罗素2000指数头部公司的股份比例高与罗素1000指数尾部公司，与我们预期一致，这个结果主要是由你指数投资者驱动。而且短期机构投资者也被这些公司所吸引，相反，专业投资者在门槛附近并没有表现出不同的持股差异。

### 相关文献

> 1、专业投资者长期持有公司头寸，有利于其与管理层直接沟通（[Admati and Pfleiderer, 2009](https://doi.org/10.1093/rfs/hhp037)^[Admati A R, Pfleiderer P. The “Wall Street Walk” and shareholder activism: Exit as a form of voice[J]. The Review of Financial Studies, 2009, 22(7): 2645-2685.]; [Edmans and Manso, 2011](https://doi.org/10.1093/rfs/hhq145)^[Edmans A, Manso G. Governance through trading and intervention: A theory of multiple blockholders[J]. The Review of Financial Studies, 2011, 24(7): 2395-2428.]）。

> 2、由于专业投资者长期持有公司头寸，有利于与管理层直接沟通,所以其很可能依赖私人信息，受公开信息生产的影响较少。（[Bushee and Noe,2000](https://doi.org/10.1016/0165-4101(89)90008-6)^[Bhushan R. Firm characteristics and analyst following[J]. Journal of accounting and economics, 1989, 11(2-3): 255-274.]）

> 3、持有较低头寸的短期交易者收集的私有信息能够使他们提前交易具体公司的信息，并从短期价格动量中获益（[Ke,Petroni, and Yu, 2008](https://doi.org/10.1111/j.1475-679X.2008.00296.x)^[Ke B, Petroni K R, Yu Y. The effect of Regulation FD on transient institutional investors' trading behavior[J]. Journal of Accounting Research, 2008, 46(4): 853-883.]）

> 4、管理者会将短期投资者和股价波动的不良影响联系起来，从而不可能改变政策以迎合短期投资者（[Beyer, Larcker, and Tayan, 2014](https://doi.org/10.1016/j.jacceco.2010.10.003)^[Beyer A, Cohen D A, Lys T Z, et al. The financial reporting environment: Review of the recent literature[J]. Journal of accounting and economics, 2010, 50(2-3): 296-343.]）。

> 5、准指数投资者既包括被动指数基金，也包括那些积极管理，但密切模仿特定指数的基金。 他们持有的各种资产使得收集其投资组合公司的私人信息成本更高，他们的跟踪策略在很大程度上削弱了他们对私人信息进行战略性交易的能力（[Gillan and Starks, 2000](https://doi.org/10.1016/S0304-405X(00)00058-1)^[Gillan S L, Starks L T. Corporate governance proposals and shareholder activism: The role of institutional investors[J]. Journal of financial Economics, 2000, 57(2): 275-305.]; [Parrino, Sias, and Starks, 2003](https://doi.org/10.1016/S0304-405X(02)00247-7)^[Parrino R, Sias R W, Starks L T. Voting with their feet: Institutional ownership changes around forced CEO turnover[J]. Journal of financial economics, 2003, 68(1): 3-46.]）

> 6、由于更高的公司透明度减少了信息不对称程度，提高了流动性，经常通过最小化成本竞争的指数投资者从更高透明度的公司获益（[Diamond and Verrecchia, 1991](https://doi.org/10.1111/j.1540-6261.1991.tb04620.x) ^[Diamond D W, Verrecchia R E. Disclosure, liquidity, and the cost of capital[J]. The journal of Finance, 1991, 46(4): 1325-1359.]），从而降低了他们的整个交易成本（[Keim, 1999](https://doi.org/10.1016/S0304-405X(98)00049-X) ^[Keim D B. An analysis of mutual fund design: the case of investing in small-cap stocks[J]. Journal of Financial Economics, 1999, 51(2): 173-194.]; [Frino and Gallagher, 2001](https://doi.org/10.3905/jpm.2001.319822) ^[Frino A, Gallagher D R. Tracking S&P 500 index funds[J]. The Journal of Portfolio Management, 2001, 28(1): 44-55.]）。

> 7、公司管理层更多地披露降低了信息收集的成本（[Easley and O'hara,2004](https://doi.org/10.1111/j.1540-6261.2004.00672.x)^[Easley D, O'hara M. Information and the cost of capital[J]. The journal of finance, 2004, 59(4): 1553-1583.]），这增强了评价管策略的能力，并降低了监管成本。

> 8、投资管理公司BlackRocd声称，当他认为公司报告或透明性不足时，他会和公司私下协商或用投票权鼓励更好的披露（BlackRock, 2014）。

> 9、纯被动指数基金和那些与指数密切相关的主动基金都占股票基金总额的很大一部分,相当一部分积极管理的股票基金是秘密的指数投资者，他们持有的投资组合密切模仿指数策略，即使他们声称是积极管理的（[Cremers and Petajisto, 2009](https://doi.org/10.1093/rfs/hhp057)^[Cremers K J M, Petajisto A. How active is your fund manager? A new measure that predicts performance[J]. The review of financial studies, 2009, 22(9): 3329-3365.]）

> 10、最近许多证据也发现准指数投资者是主动投票者（[Crane, Michenaud, and Weston, 2014](http://portal.idc.ac.il/en/main/research/caesareacenter/annualsummit/documents/crane_michenaud_weston.pdf)^[Crane A D, Michenaud S, Weston J P. The effect of institutional ownership on payout policy: A regression discontinuity design approach[J]. SSRN Electronic Journal, 2012, 12: 1-45.]），进一步证实了他们对经理的影响力。

> 11、更多的信息披露有助于管理层建立开放的对话机制，以通知投资者他们的策略和意图（[Baginski, Clinton,and Mcguire, 2014](https://www.jstor.org/stable/248513)^[Baginski S P, Conrad E J, Hassell J M. The effects of management forecast precision on equity pricing and on the assessment of earnings uncertainty[J]. Accounting Review, 1993: 913-927.]）

> 12、 大量的文献证明，由于分析师掌握专业的知识，他们既加工信息，也生产信息（[Healy and Palepu, 2001](https://doi.org/10.1111/j.1911-3846.1999.tb00592.x)^[Healy P M, Hutton A P, Palepu K G. Stock performance and intermediation changes surrounding sustained increases in disclosure[J]. Contemporary accounting research, 1999, 16(3): 485-520.]; Beyer, Cohen, Lys, and Walther, 2010）

> 13、更高的机构持股可能增加了对分析师服务的需求（[Frankel, Kothari, and Weber, 2006](https://doi.org/10.1016/j.jacceco.2005.10.004)^[Frankel R, Kothari S P, Weber J. Determinants of the informativeness of analyst research[J]. Journal of Accounting and Economics, 2006, 41(1-2): 29-54.]）。

> 14、公开信息生产通过降低信息不对称间接增加流动性（[Beyer, Cohen, Lys, and Walther, 2010](https://doi.org/10.1016/j.jacceco.2010.10.003)）

> 15、被动投资者缺监督企业和影响企业政策的激励（[Coffee, 1991](https://doi.org/10.2307/1123064) ^[Coffee J C. Liquidity versus control: The institutional investor as corporate monitor[J]. Columbia law review, 1991, 91(6): 1277-1368.]; [Porter, 1992](https://doi.org/10.1111/j.1745-6622.1992.tb00485.x) ^[Porter M E. Capital choices: Changing the way America invests in industry[J]. Journal of Applied Corporate Finance, 1992, 5(2): 4-16.]）。

> 16、机构多元化投资和交易策略可能导致披露和信息偏好的差异（[Bushee and Noe, 2000]() ^[Bushee B J, Noe C F. Corporate disclosure practices, institutional investors, and stock return volatility[J]. Journal of accounting research, 2000: 171-202.];[Bushee, 2001](https://doi.org/10.2307/2672914) ^[Bushee B J, Noe C F. Corporate disclosure practices, institutional investors, and stock return volatility[J]. Journal of accounting research, 2000: 171-202.]）

> 17、机构投资者有了解公司事务的受托责任（[Del Guercio,1996](Del Guercio D. The distorting effect of the prudent-man laws on institutional equity investments[J]. Journal of Financial Economics, 1996, 40(1): 31-62.)^[Del Guercio D. The distorting effect of the prudent-man laws on institutional equity investments[J]. Journal of Financial Economics, 1996, 40(1): 31-62.]）。

> 18、分析师作为信息中介，在处理和生产宏观信息上扮演着重要作用（[Lang and Lundholm, 1996](https://www.jstor.org/stable/248567)^[Lang M H, Lundholm R J. Corporate disclosure policy and analyst behavior[J]. Accounting review, 1996: 467-492.]; [Healy and Palepu,2001](https://doi.org/10.1016/S0165-4101(01)00018-0)^[Healy P M, Palepu K G. Information asymmetry, corporate disclosure, and the capital markets: A review of the empirical disclosure literature[J]. Journal of accounting and economics, 2001, 31(1-3): 405-440.]; [Hutton, Lee, and Shu, 2012](https://doi.org/10.1111/j.1475-679X.2012.00461.x)^[Hutton A P, Lee L F, Shu S Z. Do managers always know better? The relative accuracy of management and analyst forecasts[J]. Journal of Accounting Research, 2012, 50(5): 1217-1244.]）。

**思考：**

> **<span style="color:red">被动机构持股主要通过管理层和分析师来改善企业信息透明度和信息生产，被动持股比例越高，机构投资者越有通过投票来规范企业信息披露的需求，由于其管理的组合内资产较多，需要依赖分析师来生产信息 </span>**

### 研究结论

> 1、机构投资者持有罗素2000指数头部公司的股份比例高与罗素1000指数尾部公司,这个结果主要是由你指数投资者驱动。

> 2、不同机构投资者投资和交易策略的差异说明每类投资者对公开信息和私有信息生产上的偏好和影响在变化。专业投资者长期持有公司头寸，有利于与管理层直接沟通,所以其很可能依赖私人信息，受公开信息生产的影响较少。

> 3、专业投资者往往持有很少的短期头寸，可能从公开和私有信息中获益。一方面，收集的私有信息能够使他们提前交易具体公司的信息，并从短期价格动量中获益，另一方面，更大的公开信息能够产生更多的交易机会，可能放松了这些交易对价格的影响。投资期限段降低了他们影响管理层和分析师生产信息的能力。

> 4、如果短期交易者从公开（私有）信息中收益，他们将吸引到（离开）更加透明的公司。

> 5、准指数投资者准指标要求更大的公司透明度，并加强公共信息生产，以尽量减少这些成本

> 6、拥有更多准指数公司所有权的公司通过管理预测和自愿证券交易委员会(SEC)形成8K文件，向投资者更多地传达公司前景

> 7、罗素2000指数顶部的公司提供了更大的预测特质性，在每个会计期间预报较早。

> 8、公司透明度增加可能会降低分析师的分歧，因为它降低了分析师获取信息的成本，并利用了他们合成额外信息的能力。

> 9、在罗素2000指数头部的公司中，分析师跟踪越多，预测意见分歧越低，部分原因是由于在罗素1000指数尾部跟踪准指数投资者持股稀疏公司的分析师显著降低。

> 10、 分析师跟踪和管理层主动披露是负向关的，表明当公司透明度较低时，准指数投资者需要分析师服务作为一种信息生产的替代形式。

> 11、某种程度上，持股变化通过管理者和分析师影响公司透明度和信息生产。

> 12、罗素2000指数头部公司中，指数持股越低的公司表现出低的信息不对称性和高流动性，表明公司透明性增加降低了交易成本。

> 13、大型机构都会出于代理投票的目的而设有收集分析公司信息的部门，其他机构也会外包他们的代理投票研究给相应的咨询服务机构，这都广泛地应用了公开信息披露。

### 不熟悉的英文

> predilection 偏好，偏爱，嗜好  例：He has a predilection for rich food,他偏好油腻食物。

> salient  显著的，突出的，主要的

> delve into ......      钻研...........

> rule out .......      排除...........

> ** The Dedicated institutional stockholders with stable ownership and high rank in the
companies of their own portfolio and are more enthusiastic to supervise the companies in their portfolio**,貌似对应国内的大股东

> **Transient institutional stockholders owning high turnovers
and little stocks in diverse companies** 对应国内短期投资者

> be indiferent to  对....漠不关心  例：these institutions are not indifferent to the information environment because higher information asymmetries increase both their transaction and monitoring costs.由于信息不对称增加了交易和监管成本，机构投资者对信息环境并不是漠不关心。


## [Information,Participation, and Passive Investing](https://dx.doi.org/10.2139/ssrn.3299280)

### 摘要

> 我们研究了基本面信息挖掘成本对价格信息含量和被动投资的影响，在多个风险资产和一个冗余市场指数的REE模型框架下，我们把被动投资定义为搭乘主动交易者努力获取基本面信息的便车和放弃主动选股策略之间的最优决策。信息成本下降有一个对偶效应，一方面降低了市场择时成本，进而降低了被动持股份额，另一方面，降低了选股成本，增加了被动持股份额。如果选股效应主导市场择时效应，被动持股增加伴随着更大的股价信息含量。我们利用SEC的扩展业务报告语言任务作为对信息成本的负面冲击，提供了信息成本下降导致了被动投资上升的证据。

### 研究思路

> 关于被动持股近年来上升最流行的解释是被动投资的成本相对主动管理基金较低被动投资的增加意味着越来越低的股价信息含量。但这与价格信息含量增加的趋势不一致，特别是受指数化策略影响最大的大公司，这对用简单的成本解释被动投资和股价信息含量提出了新的挑战。

> **首先，为了独立考虑主动投资者的市场择时和选股策略，我们的模型中包括了多个风险资产，其次，我们区分了选股策略的参与者和信息成本，基本面信息成本下降增加了追求市场择时策略的投资者比例。其次，我们提供了证据支持信息成本下降提升了被动投资，发现低信息成本恶化了主动获取信息投资者的业绩表现。**


### 相关文献

> 1、主动投资相对更高的成本导致均衡中出现更多的被动投资（Grossman and Stiglitz，1980）。

> 2、Bai et al.（2016）发现金融市场中股价的信息含量越来越多，特别是受被动投资影响的大公司（Farboodi et al.，2018）。

> 3、更高的ETF持股导致了更精确的会计信息的反映，表明价格效率随被动持股提高（Gloseten et al.,2018）。

> 4、Golse et al.（2018）被动投资恶化了弱形式的价格效率。

> 5、Gremers et al.（2016）更多的指数化通常导致更多的主动投资获得更大的alpha。

### 研究结论

> 1、我们建立了一个新的理论框架，来解释三个流行的趋势，（1）被动投资份额越来越高；（2）信息成本降低；（3）价格信息含量更高。

> 2、在我们的模型中，交易者最优化信息获取和股票选择，发现如果选股策略占主导地位，被动投资份额上升。




