---
title: 卖空限制与股市波动文献
author: 薛英杰
date: '2020-08-22'
slug: 卖空限制与股市波动文献
categories:
  - research
tags:
  - diary
---


# 卖空交易与股票价格稳定性——来自中国融资融券市场的自然实验


```
李志生 杜爽 林秉旋

2015年《金融研究》
```

### 摘要

基于2009年4月－2013年12月我国股票市场的数据，本文研究了融资融券标的股票和非标的股票、以及股票被列入和剔出融资融券标的前后的价 格波 动特征 。 结果表明，融资融券交易机制的推出有效提高了我国股票价格的稳定性，融资融券标的股票的价格波动率和振幅均出现了显著性下降 。 我们还发现，融资融券交易显著降低了股票价格的跳跃风险，有利于 防止股票价格的暴涨暴跌和过度投机。此外，融资融券交易在抑制股票 价格异质性波动上也起到了实质性作用，从而有助于增加上市公司信息透 明度和市场信息效率。
    
### 研究问题

多层次的金融创新为市场提供了便捷和充足的流动性，使得全球资产价格的波动显著增大，导致金融市场的不稳定，卖空机制是金融创新进程中的一个重要的里程碑，卖空机制对证券市场效率和证券价格稳定性有重要的影响。中国大陆股票市场建立以来，信用交易和卖空机制长期不被允许，投资者过度投机和羊群效应严重，导致股票价格暴涨暴跌和异常波动，2010年3月31日，上海证券交易所和深圳证券交易所启动 了融资融券交易试点 ， 标志着Ａ股市场针对个股的做空机制正式建立 。 但卖空交易对资产价格波动和市场稳定性的影响在学者们之间的意见分歧较大，卖空交易到底是增加了市场波动还是降低了市场波动？

### 相关文献

多数理论研究指出，卖空约束会导致系统性的定价误差，导致资产价格剧烈波动。

> 1、在卖空交易缺失的市场，资产价格反映的是乐观投资者的估值，当投资者对某项风险看法存在广泛差异时，卖空约束使得悲观者离开市场，因而只反映了乐观投资者的观点，从而使股价向上偏离，由此产生系统性泡沫，导致资产价格大幅波动（[Miller,1997](https://www.jstor.org/stable/2326520?seq=1)^[ Miller E. M.,Risk, Uncertainty, and Divergence of Opinion[J].The Journal of Finance, 1977 32(4):1151-1168.]）。

> 2、由于存在卖空约束，市场悲观情绪被隐藏，在资产价格下跌时，市场所积累的隐藏负面信息会突然释放，从而加速市场下跌([Hong and Stein,2003](https://doi.org/10.1093/rfs/hhg006)^[Harrison Hong, Jeremy C. Stein,Differences of Opinion, Short-Sales Constraints, and Market Crashes[J].
The Review of Financial Studies. 2003:16(2 ): 487–525.])。

> 3、[Bai et al.(2006)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=890726)^[Bai, Yang and Chang, Eric Chieh C. and Wang, Jiang, Asset Prices and Short-Sale Constraints[J]. AFA 2007 Chicago Meetings Paper, Available at SSRN: https://ssrn.com/abstract=890726  ]的模型研究表明，由于知情交易者有显著的影响，卖空约束会降低价格中的信息价值，从而加大非知情交易者所承担的风险，因此，卖空约束可能会降低资产价格，并加大其波动性。

> 4、卖空约束的存在，资产价格对信息的调整速度会减慢，错误的定价难以被纠正，在资产价格高估的情况下，卖空约束会进一步加剧资产价格的高估程度和波动性（[Aufriev and Tuinstra,2013](https://doi.org/10.1016/j.jedc.2013.04.015)^[Aufriev M.,J. Tuinstra. The impact of short-selling constraints on financial market stability in a heterogeneous agents model[J].Journal of Economic Dynamics and Control
, 2013,37(8):1523-1543
 ]）。

> 5、参与卖空的投资者倾向采取反转交易策略，因而起到稳定市场的作用([Diether et al.,2009](https://doi.org/10.1093/rfs/hhn047)^[Karl B. Diether, Kuan-Hui Lee, Ingrid M. Werner, Short-Sale Strategies and Return Predictability[J], The Review of Financial Studies, 2009, 22(2):575–607])。

> 6、卖空禁令增大了买卖价差和股票价格的波动，有损市场效率和质量([Beber and Pagano,2013](https://doi.org/10.1111/j.1540-6261.2012.01802.x)^[Beber A.,Pangano M. Short‐Selling Bans Around the World: Evidence from the 2007–09 Crisis[J]. 2013, 68(1):343-381])。

> 7、卖空可能导致皮格马利翁效应（Selef-fulfilling Prohency ），从而加速市场下跌([Aitken et al.,1998]( https://doi.org/10.1111/0022-1082.00088)^[ Aitken M. J.,  Frino A.  McCorry M. S.  Swan P. L. Short Sales Are Almost Instantaneously Bad News: Evidence from the Australian Stock Exchange[J]. Jounal of Finance,1998,53(6):2205-2223])。

### 文献背景

> 1、融资融券业务为研究卖空机制对股票价格稳定性的影响提供了很好的自然环境，我国股票市场只有少数股票被列为融资融券标的，有利于对比和事件分析得到稳健的结果。

> 2、我国融资融券在参与者层面存在明显的非对称性，只有部分证券公司有融资融券权限，而且证券公司对融资融券的参与者设置了较高的门槛。

> 3、由于制度设计等多方面的原因，自我国融资融券制度推出以来，市场融资融券量都比较小。

### 研究设计

1、价格稳定性的度量

（1）月度收益的标准差和股票价格的振幅；（2）跳跃风险；（3）特质波动率

2、实证模型

为了检验融资融券交易是否会对资产价格的稳定性产生影响，使用非平衡面板回归模型分三层进行研究：

（1）对融资融券制度推出后，融资融券标的股票和非融资融券标的股票的价格稳定性进行比较，具体如下：

$$ Stability_{it}=\alpha_0+\beta Shotlist_{it}+\gamma Control_{it}+v_i+e_t+\epsilon_{it}$$

其中，$Stability_{it}$表示股票价格稳定性，$Shotlist_{it}$为虚拟变量，融资融券标的取1，其他取0。

接下来对股票被纳入和剔除融资融券标的前后的价格稳定性进行事件分析，具体模型如下：

$$Stability_{it}=\alpha_0+\beta EventIN_{it}+\gamma Control_{it}+v_i+e_t+\epsilon_{it}$$

$$Stability_{it}=\alpha_0+\beta EventOut_{it}+\gamma Control_{it}+v_i+e_t+\epsilon_{it}$$
其中，$EventIN_{it}$和$EventOut_{it}$为虚拟变量，对于股票$i$事件（加入或剔除）前为1，否则为0.


### 研究结论

> 1、融资融券交易机制的推出有效地降低了股票价格的波动性。

> 2、融资融券制度显著地降低了股票价格的跳跃风险，有利于抑制股价的暴涨暴跌。

> 3、融资融券制度在抑制股票价格特质风险上起到了市值性作用，有助于增加上市公司信息透明度和市场信息效率。


# 卖空约束、投资者行为和A股市场的定价效率
```
古志辉 郝项超 张永杰
2011年《金融研究》
```

### 摘要

本文构建了一个随机估值模型，在此基础上运用面板数据方法对A股市场的资产定价泡沫和成因进行了研究，获得了如下结论：首先，A股市场中的估值泡沫和投机泡沫并存。其次，卖空约束导致的定价偏差是定价泡沫的成因之一。第三，异质信念与不对成信息和泡沫水平正相关，过度自信与泡沫水平负相关。第四，重要流通股股东的信息优势与交易中的不对称信息无协同效应，最后，若卖空约束不存在，观察不到损失厌恶对泡沫的影响。

### 研究问题

影响中国A股市场资产定价泡沫的因素有哪些？卖空约束、异质信念、过度自信、损失厌恶还是信息不对称？

### 相关文献

> 1、如果投资者是有限理性的，其短视的决策行为是资产定价泡沫形成的原因之一（[Tirole,1982](https://www.jstor.org/stable/1911868?seq=1)^[ Tirole J.,On the Possibility of Speculation under Rational Expectations[J],
Econometrica, 1982,50(5):1163-1181]）。

> 2、卖空和异质信念是资产定价泡沫的重要原因（[Miller,1997](https://www.jstor.org/stable/2326758)^[Miller M., Debt and Taxes[J],
The Journal of Finance
1997,32(2):261-275]）

> 3、中国上市审批制度、有限证券种类、政府托市行为、卖空机制缺失、套利机制有效性和上市公司分红都可能是A股资产定价泡沫的影响因素（[周春生，杨云红，2002](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&filename=JJYJ200207003&dbname=CJFD2002)^[周春生, 杨云红. 中国股市的理性泡沫[J]. 经济研究, 2002(07):33-40.]）。

> 4、当前投资者认为在未来会有出价更高的投资者，他们愿意支付较高的价格，从而导致支付与折现的未来现金流出现偏差，即投机溢价（[Harrison and Kreps,1978](https://doi.org/10.2307/1884166)^[J. Michael Harrison, David M. Kreps, Speculative Investor Behavior in a Stock Market with Heterogeneous Expectations[J], The Quarterly Journal of Economics, 1978,92(2):323–336]）。

> 5、如果投资者具有学习的能力，那么在异质信念存在的情况下，投机溢价直到学习结束才会消失，所以，投资者在存在异质信念时，会倾向于接受一个较高的价格，从而导致定价泡沫（[Morris,1996](https://www.jstor.org/stable/2951751)^[ Morris S.,Trade with Heterogeneous Prior Beliefs and Asymmetric Information[J].
Econometrica,1994,62(6):1327-1347]）。

> 6、当投资者存在过度自信的异质信念，并且市场上存在卖空约束时，有两种原因将导致资产价格超过基础价值（[Hong,Scheinkman and Xion,2006]( https://doi.org/10.1111/j.1540-6261.2006.00867.x)^[Hong H.,J Scheinkman, and W. Xiong,Asset Float and Speculative Bubbles[J]. Journal of Finance,61(3):1073-1117.]）。

> 7、投资者之间的信息不对称对方大价格的波动性，在信息不对称的影响下，消息灵通的投资者会借助信息上的优势与消息不灵通的投资者进行交易，这样噪声交易存在时，就会面临逆向选择问题（[Wang,1994,2002](https://www.journals.uchicago.edu/doi/abs/10.1086/261924)^[Wang J.,A Model of Competitive Stock Trading Volume[J]. Journal of Political Economy,1994,102(1):127-167.]）。

### 研究结论

> 1、在存在卖空的市场上，投资者的估值偏高，形成了理性估值泡沫，同时，存在投机性定价泡沫。

> 2、由于卖空约束导致的定价偏差是估值过高或定价泡沫形成的主要原因。

> 3、放松卖空约束如推出股指期货和融资融券等业务可以有效地降低泡沫水平。

> 4、监管机构还需关注金融创新的选择，对于证券公司而言，需要推出相关认股权证，可以有效地降低证券公司客户的违约概率。


# 我国推出融资融券交易提高了标的股票的定价效率码？——基于双重差分模型的实证研究

```
徐宏伟 陈欣

2012年《管理世界》
```


### 摘要

基于双重差分（DID）模型，本文研究了我国融资融券试点对股票定价效率和收益率分别的影响，发现仅在少数指标上有一定积极作用，总体上效果仍然有效，为现有文献争议和后续政策完善提供了新的经验证据。具体来说，融资融券1年内：（1）对定价效率的改善仍然较弱，标的股票价格的负面信息含量和对市场向下波动调整速度变化均不明显，（2）能够显著减少股价暴跌概率，对抑制暴涨几乎没有什么影响，最终只起到单向“缓冲器”的作用。（3）今年能显著降低H股、高市值、低换手率和低市盈率股票的偏度，对改善收益率的尖峰现象则没有起到积极作用。结合市场实际运行情况，本文认为融资融券制度这一机制创新没有完全发挥功能的主要原因在于诸多交易限制，并提出了相应的政策建议。


### 研究问题

> 卖空机制是否能够改善定价效率,缓解同涨同跌，暴涨暴跌等现象？

### 相关文献

> 1、由于政策限制、搜寻成本等原因，卖空约束使得股价不能及时或充分反映市场负面信息，从而导致定价效率较低及收益率分布不合理（Diamond and Verrechina,1987;Bris et al.,2007;Saffri and Sigurdsson,2011）

> 2、由于政策环境、市场情况和发展阶段不同，允许卖空并不能对定价效率产生一定影响，反而在一定情况，可能因为投资者利用私人信息、杠杆交易、市场委托等行为加大市场波动（Allen and Gale,1991;Kemi and Madhaven,1995;Bai et al.,2006;Charoenrook and Daouk,2005）。

> 3、[Diamond和Verrechina（1987）](https://doi.org/10.1016/0304-405X(87)90042-0)^[Diamond D. W. and  Verrecchia R. E.,Constraints on short-selling and asset price adjustment to private information[J].Journal of Financial Economics,1987,
18(2):277-311.
]建立了一个卖空约束排除部分信息交易者的模型，证明了卖空约束损害了股票定价效率，因为其削弱了股价对私人信息的调整速度。

> 4、[Charles和Owen(2002)](https://doi.org/10.1016/S0304-405X(02)00224-6)^[Charles M. J. and Owen A. L. Short Sale
Constraints and Stock Returns[J].Journal of Financial Econom⁃
ics，2002，66(2-3):207-239.]研究发现卖空成本很高的股票具有更高的估值水平以及未来更低的收益率。

> 5、[Reed(2003)]()^[Reed A.,Costly Short Selling and Stock Price Adjustment to Earnings Announcements[J],Working pa⁃
per， University of North Carolina.]提出卖空约束大的股票吸收信息非常缓慢，并且股价对负面信息反映更慢，表明卖空约束对市场信息反映是不对称的。

> 6、在允许卖空的市场上，股价能够快速吸收负面信息，与监管者所认为的卖空约束能够防止市场恐慌的观点相反，不能卖空导致市场奔溃的概率较大（[Bris,2007](https://doi.org/10.1111/j.1540-6261.2007.01230.x)^[Bris A, Goetzmann W N, Zhu N. Efficiency and the bear: Short sales and markets around the world[J]. The Journal of Finance, 2007, 62(3): 1029-1079.]）。

> 7、[Saffi和Sigurdsson(2011)](https://doi.org/10.1093/rfs/hhq124)^[Saffi P A C, Sigurdsson K. Price efficiency and short selling[J]. The Review of Financial Studies, 2011, 24(3): 821-852.]根据全球26个国家在2005-2008年期间的股票数据，采用信贷余额作为卖空约束的代理变量，发现卖空约束对于股票吸收市场和个股负面信息速度有明显负面影响，并且放松卖空约束与价格不稳定性和极端负收益并无直接联系。

> 8、[Li和Myers(2006)](https://doi.org/10.1016/j.jfineco.2004.11.003)^[Jin L, Myers S C. R2 around the world: New theory and new tests[J]. Journal of financial Economics, 2006, 79(2): 257-292.]研究发现，当卖空约束使得目标公司经营状况变得不透明时，其股价反映的特质信息就比较少。

> 9、[廖士光（2011）](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2011&filename=LXGZ201101007&v=MDA5NDdmYitSbUZ5L21VN3pOS1RYTWRMRzRIOURNcm85Rlk0UjhlWDFMdXhZUzdEaDFUM3FUcldNMUZyQ1VSN3E=)^[廖士光.融资融券交易价格发现功能研究——基于标的证券确定与调整的视角[J].上海立信会计学院学报,2011,25(01):67-76.]利用沪深证券市场标的股票确定与调整事件进行分析，发现我国融资融券交易业务发展失衡，融资融券交易有助于提升标的股票市场的价格，融资融券交易的总体价格发现功能则有待进一步发挥。

> 10、[杨德勇和吴琼（2011）](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2011&filename=ZYCY201105006&v=MTI4MzlLUHpUSWQ3RzRIOURNcW85RllvUjhlWDFMdXhZUzdEaDFUM3FUcldNMUZyQ1VSN3FmYitSbUZ5L21XcnI=)^[杨德勇,吴琼.融资融券对上海证券市场影响的实证分析——基于流动性和波动性的视角[J].中央财经大学学报,2011(05):28-34.]发现融资融券机制能够一定程度上抑制个股波动，并提高个股的流动性。

### 研究设计

1、定价效率的代理变量

（1）个股股价吸收好或坏私有消息的不同程度

$$R_i^{2Diff}=R_i^{2-}-R_i^{2+}$$

其中，$R_i^{2-}$和$R_i^{2+}$分别为市场下跌或上涨时，将个股日收益率和市场日收益率回归所得$R^2$,这个指标度量了个股吸收好消息或坏消息的程度

 （2）个股对好消息或坏消息反映的速度
 
 $$\rho_i^{Diff}=rho_i^{-}-rho_i^{+}$$
 
其中，$rho_i^{-}$和$rho_i^{+}$分别为个股周收益率与市场收益率（上涨或下跌）的相关系数。

2、融资融券政策推出前后定价效率的变化

为了检验融资融券政策推出前后定价效率的变化，我们采取双重差模型（DID）具体如下：

$$y_{it}=\beta_0+\beta_1 D_t+\beta_2D_g+\gamma D_tD_g+\sum{X_{it}}+\epsilon_i$$

其中，$y_{i,t}$第i个股票第t期的指标值，$D_t$为虚拟变量，融资推出后$D_t=1$,否则$D_t=0$,$D_g$为组间虚拟变量，当为融资融券标的股票时，$D_g=1$,否则$D_g=0$,$\sum{X_{it}}$为控制变量。

### 结论

> 1、 总体上， 标的股票价格对负面私有信息的含量以及对市场向下波动的调整速度变化均不明显，融资融券试点对定价效率的影响总体上仍十分有限，这主要是由于这一机制试点期间受到诸多限制， 导致融资融券总体规模过小所致。

> 2、 融资融券总体上有助于显著减小股价暴跌的概率，在分组样本分析中， 这种作用同样十分稳健。但对抑制股价暴涨和同涨共跌却几乎没有影响，最终只起到了“单向缓冲器”作用。

> 3、仅能显著降低含 H 股、 高市值、 低换手率和低市盈率股票的偏度， 且对改善收益率的尖峰现象并没有起到积极作用。 这表明短期内融资融券试
点虽然对某些股票具有一定积极作用， 但总体上还非常有限。


# [融资融券对股价特质性波动的影响机理研究：基于双重差分模型的检验](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2015&filename=GLSJ201408005&v=2205LbYcuSG2hUK6jHWtfONE7ou%25mmd2FqCDy03Z9eXbsn2GiAite4FWA3%25mmd2FDUL%25mmd2FNtd%25mmd2B85)^[[1]肖浩,孔爱国.融资融券对股价特质性波动的影响机理研究:基于双重差分模型的检验[J].管理世界,2014(08):30-43+187-188.]

      肖浩 孔爱国
      
      2014 管理世界
      
### 摘要

本文基于双重差分模型检验了融资融券对股价特质性波动的影响及其机理。研究发现,融资融券交易降低了标的证券股价特质性波动,但这一影响是通过降低标的证券的噪音交易、提升信息传递速度、降低公司盈余操纵以及降低投资者之间的信息不对称程度来实现。以上结果表明,融资融券业务降低了股价特质性波动的非信息效率因素。此外,本文发现,融资融券对公司盈余操纵的影响只有在业务开通时的瞬间效应而无持续效应,这表明卖空机制对公司的外部治理作用有待改善。

### 研究问题

对于个股而言，融资融券增加了知情交易者利用公司特质信息获利的能力和途径，这势必增加股价的信息含量。而目前国内外研究主要关注融资融券交易的卖空机制对股票波动性、流动性、股票收益分布及定价效率的影响，但鲜有研究涉及融资融券交易对股价信息含量的影响。[Roll(1988)](https://doi.org/10.1111/j.1540-6261.1988.tb04591.x) ^[Roll， Richard， 1988，R2， Journal of Finance， Vol.25，
pp. 541~566.]发现市场和产业层面的信息只能解释个股股价小部分的波动，未解释的部分（股价特质性波动）由公司特质信息或噪声噪声，并且公司特质信息进入股价的主要方式是私有信息知情交易者的交易，因此，大多数研究认为特质波动是股价中特质信息的可行测度。但另一些研究表明股价特质波动受到噪声交易（[Lee and Liu ,2011](https://doi.org/10.1016/j.jbankfin.2010.11.002) ^[Lee D W, Liu M H. Does more information in stock price lead to greater or smaller idiosyncratic return volatility?[J]. Journal of Banking & Finance, 2011, 35(6): 1563-1580.]）、信息传递延缓（[Dasgupta et al., 2010](https://www.jstor.org/stable/27919561) ^[Dasgupta S, Gan J, Gao N. Transparency, price informativeness, and stock return synchronicity: Theory and evidence[J]. Journal of Financial and Quantitative Analysis, 2010: 1189-1220.]）和公司盈余质量恶化（[Rajgopal and Venkatachalam,2011](https://doi.org/10.1016/j.jacceco.2010.06.001) ^[Rajgopal S, Venkatachalam M. Financial reporting quality and idiosyncratic return volatility[J]. Journal of Accounting and Economics, 2011, 51(1-2): 1-20.]）等非信息效率因素的影响。融资融券交易对股价特质性波动有何影响？ 作用机制如何？ 有何经济意义？

### 相关文献

> 1、[Miller(1977)](https://www.jstor.org/stable/2326520) ^[Miller E M. Risk, uncertainty, and divergence of opinion[J]. The Journal of finance, 1977, 32(4): 1151-1168.]认为，卖空交易的限制将使得股价无法反映负面私有信息，进而导致股价高估，增加市场波动。

> 2、[Seguin(1990)](https://doi.org/10.1016/0304-3932(90)90033-Z) ^[Seguin P J. Stock volatility and margin trading[J]. Journal of Monetary Economics, 1990, 26(1): 101-121.]发现信用交易能增大信息流入和市场厚度，被允许使用信用交易的 OTC 股票股价波动性减小， 噪音交易变低。

> 3、杨德勇和吴琼（2011） 利用事件研究法检验了融资融券业务开通前后个股的波动性，结果表
明融资融券交易降低了个股波动性。

> 4、[Hardouvelis（1990）](https://www.jstor.org/stable/2006705)^[Hardouvelis G A. Margin requirements, volatility, and the transitory component of stock prices[J]. The American economic review, 1990: 736-762.]发现提高信用交易保证金将部分利用市场非理性情绪的投机排挤出市场，进而降低了个股股价的波动。

> 5、[Saffi 和 Sigurdsson（2011）](https://doi.org/10.1093/rfs/hhq124)^[Saffi P A C, Sigurdsson K. Price efficiency and short selling[J]. The Review of Financial Studies, 2011, 24(3): 821-852.] 发现卖空限制降低了股价对市场和公司负面信息的吸收速度； 但放松卖空约束并不一定导致股价波动率上升以及极端值频率提高。

> 6、[Saffi 和 Sigurdsson（2011）](https://doi.org/10.1093/rfs/hhq124)^[Saffi P A C, Sigurdsson K. Price efficiency and short selling[J]. The Review of Financial Studies, 2011, 24(3): 821-852.] 则利用个股回报与上一期市场回报的相关系数、 股价对市
场信息反应的延迟程度以及股票收益分布等指标刻画股价的定价效率，并发现融券余额较少的股票，
股价定价效率较低。

> 7、[Morck 等人（2000）](https://doi.org/10.1016/S0304-405X(00)00071-4)^[Morck R, Yeung B, Yu W. The information content of stock markets: why do emerging markets have synchronous stock price movements?[J]. Journal of financial economics, 2000, 58(1-2): 215-260.]考察了产权保护对股价特质性波动的影响，其发现产权保护好的国家， 投资者收集私有信息套利的激励更大，股价特质性波动更高。

> 8、[Jin 和Myers（2006）](https://doi.org/10.1016/j.jfineco.2004.11.003)^[Jin L, Myers S C. R2 around the world: New theory and new tests[J]. Journal of financial Economics, 2006, 79(2): 257-292.] 发现公司信息透明度高的市场股价特质性波动更大； 存在卖空约束的市
场， 公司负面特质信息不易进入股价而致特质性波动更低。

> 9、[Lee and Liu ,2011](https://doi.org/10.1016/j.jbankfin.2010.11.002) ^[Lee D W, Liu M H. Does more information in stock price lead to greater or smaller idiosyncratic return volatility?[J]. Journal of Banking & Finance, 2011, 35(6): 1563-1580.] 也发现股价特质性波动和其他股价信息含量指标（如PIN）呈现U型关系， 与噪音正相关。

### 核心观点

> **融资融券业务的开通一方面会促进了私有信息知情者的交易， 导致股价的特质性波动变大。 但
另一方面， 知情者利用信息优势获利的能力和途径的增加使得噪音交易者处于更不利的位置，噪音交易者会选择离开融资融券标的股票，进而降低噪音对股价特质性波动的影响,同时，融资融券业务使得拥有私有信息的知情者能够利用杠杆交易迅速修正股价和价值之差，卖空机制也使得先前不能得
到反映的负面信息进入股价，这都提高了公司特质信息进入股价的速度，导致股价特质性波动降低。**

### 结论

> 1、融资融券业务的开通降低了标的股票的特质性波动。

> 2、事前噪音交易高的融资融券标的公司股价特质性波动下降幅度显著大于事前噪音低的公司；信息进入股价速度高的标的公司， 股价特质性波动率下降幅度也显著偏大

> 3、融资融券业务的开通降低了股价特质性波动中的非信息效率因素， 提高了股价的信息效率。

## [Asset Prices Under Short-Sale Constraints](http://w4.stern.nyu.edu/finance/docs/pdfs/Seminars/071w-wang.pdf)

    Yang Bai, Eric C. Chang and Jiang Wang
    
    Working Paper

### 摘要

这篇文章研究了卖空限制如何影响资产价格和市场有效性，我们在投资者基于对冲风险和利用私有信息投机的基础上呈现了卖空限制，建立了一个完全理性预期均衡模型。卖空限制降低了市场信息和资源配置效率，由风险共享驱动的卖空限制改变了向上的资产需求，从而改变了资产价格。而有私有信息驱动的卖空限制非知情交易者感受到的资产不确定性。当信息效应主导时，卖空限制导致资产价格降低，波动增加，我们已经证明，当价格不能提供信息时，非知情交易者感知到的不确定性激增，卖空限制导致价格下降的同时增加了波动。

### 研究问题

> **以前的研究主要关注投资者关于未来支付的期望如何影响资产价格以及卖空限制如何影响投资者预期和资产价格的关系，他们忽视了风险如何影响价格以及卖空限制如何影响投资者感知的风险，某种程度上，风险与资产价格相关，卖空限制通过影响投资者感知的基本面风险进而影响资产价格。**

### 研究思路

在理性预期模型中，竞争股票市场中的投资者出于两种动机进行交易。一种动机是对冲风险，第二种动机是利用私有信息进行投机。假设投资者会面临卖空限制，他们会接收到关于股票未来支付的私有信息，并利用私有信息进行交易。在这样一个经济中，市场既扮演分配的角色，也扮演信息角色，允许我们检验卖空限制如何影响市场效率。由于Miller 和 Diamond 只关注了两个交易动机中的其中一个，本文同时考虑了影响资产价格的两个动机，这样，卖空限制可能对股票价格的影响不同。

当投资者拥有大量不能交易的风险资产时，投资者可能渴望持有一个负向头寸来对冲风险，但卖空约束使得他们的行动受限。从而导致投资者有一个看多的总体需求。

当知情交易者从事信息交易时，卖空约束限制了他们对负面消息的利用，受限的交易导致股价信息含量降低，使得正负信息不对称。当使用价格反映信息时，由于非知情投资者完全考虑了这种不对称，这并不会引起非知情交易者的预期偏差。

然而， 股价信息含量降低增加了非知情交易者感知的资产不确定性，卖空限制对信息效率的影响又反过来影响了投资者的交易。特别地，由于不确定性增加，非知情交易者将降低对资产的需求，从而导致股价下降。

### 相关文献
> 1、[Miller(1997)](https://www.jstor.org/stable/2326520?seq=1)认为卖空限制将更悲观的投资者拦在市场之外，价格往往反应了一个更乐观的价值。

> 2、[Harrison and Kreps (1978)](https://doi.org/10.2307/1884166)^[Harrison J M, Kreps D M. Speculative investor behavior in a stock market with heterogeneous expectations[J]. The Quarterly Journal of Economics, 1978, 92(2): 323-336.]发现卖空限制可能驱动价格超过更乐观的投资对未来现金流期望的价值。

> 3、[Diamond和Verrechina（1987）](https://doi.org/10.1016/0304-405X(87)90042-0)发现卖空限降低了股价的信息效率，但没有导致价格高估。


### 主要结论

>  1、由于卖空限制导致信息效率的缺失增加了非知情交易者感知的风险，当投资者是风险厌恶者时，风险增加引起股价下降，信息不对称程度严重时，卖空限制可能降低了资产价格。

>  2、当市场信息效率严重低下时，卖空限制可能降低了资产价格，在市场信息对称条件下，由于限制了股票总需求的波动范围，卖空限制可能降低了股价波动。但在信息不对称比较严重时，由于非知情交易者感知到感知到更高的风险，需要一个高的价格调整与其交易相适应，从而卖空限制可能引起股价波动增加。

> 3、在卖空限制下，知情交易者被隔离在市场外，市场价格可能变得无信息，市场价格反映信息的失败导致非知情交易者感知到的未来资产支付的不确定性激增，价格跳跃增加，价格波动上升。**这与市场崩盘期间我们观测到的股价表现一致，并没有大消息，股价却突然下降，价格下跌伴随着更多市场的困惑，而不是清晰的经济运行状态，崩盘后，困惑增加反映在更高的价格波动上，卖空限制可能是一个市场崩盘的潜在诱因**


## [Short-Sale Constraints and the Idiosyncratic Volatility Puzzle: An Event Study Approach](https://doi.org/10.1016/j.jempfin.2014.05.005)^[Jiang D, Peterson D R, Doran J S. Short-sale constraints and the idiosyncratic volatility puzzle: An event study approach[J]. Journal of Empirical Finance, 2014, 28: 36-59.]

    Doran, James and Jiang, Danling and Peterson, David
    Journal of Empirical Finance
    
### 摘要

使用事件研究，我们发现卖空限制在特质波动和收益的负向关系中扮演着重要作用。我们探索了改变卖空限制的三个外生事件：IPO锁定到期，引入期权和金融股卖空限制的禁令。前两个事件的卖空限制改变后，无论短期还是长期，高特质波动的表现不如低特质波动的表现，高特质波动伴随着异常高的交易量。高特质波动的金融公司在短期禁令执行中经历了一个更大的价格上升，禁令到期后，价格大幅下降。

### 研究问题

> **卖空限制缓解如何影响特质波动与收益的关系？**

### 研究思路

> 通过IPO锁定解封、期权交易引入市场和卖空禁令终止三个外生冲击事件，检验了卖空限制和特质波动率的关系。

> 具体来讲，在IPO锁定期，IPO锁定前的股东在六点个月内不能卖出他们的股票，但这些锁定的股票可以被借出，使做空更容易、成本更低。这样，IPO锁定到期引起的冲击缓解了卖空限制。期权引入后，投资者面临的卖空限制可以通过期权市场来缓解，从而促进做市场商通过卖空基础资产来对冲头寸。由于做市商面临的卖空限制比散户和机构投资者小，期权可以有效地缓解股票市场的卖空限制。如果高特质的股票被高估，我们期望这些股票经历一个更负向的价格反映。金融股卖空禁令为检验卖空限制对股价波动的影响提供了一个自然实验，当卖空限制被实施时，卖空者被迫放弃空头头寸，这导致非做空股票面临一个斜率向下的需求曲线。

### 研究假设

> 1、在IPO解禁和期权引入后，高特质波动的股票表现不如低特质波动的股票

> 2、IPO解禁和期权引入后，高特质波动的股票更易被交易

> 3、当金融股做空禁令解除后，高特质波动的股票更易被做空

### 相关文献

> 1、在IPO锁定期，IPO锁定前的股东在六点个月内不能卖出他们的股票（[Bradley, Jordan, Yi, and Roten 2001](https://doi.org/10.1111/j.1475-6803.2001.tb00826.x)^[Bradley D J, Jordan B D, Yi H C, et al. Venture capital and IPO lockup expiration: An empirical analysis[J]. Journal of financial Research, 2001, 24(4): 465-493.]）。

> 2、投资者不能出股票被人为是最严格的卖空限制,IPO锁定到期引起的冲击缓解了卖空限制（[Ofek and Richardson, 2003](https://doi.org/10.1111/0022-1082.00078)^[Odean T. Volume, volatility, price, and profit when all traders are above average[J]. The journal of finance, 1998, 53(6): 1887-1934.]）。


> **特质波动与股票收益**

> 3、高特质波动股票的月度市值加权组合收益超越地特质波动组合收益1%，这个发现并不能被大多数公司特征和宏观因素解释，而且，高波动的股票表现不佳在全世界范围内存在（[Ang, Hodrick, Xing, and Zhang ，2006](https://doi.org/10.1111/j.1540-6261.2006.00836.x)^[Ang A, Hodrick R J, Xing Y, et al. The cross‐section of volatility and expected returns[J]. The Journal of Finance, 2006, 61(1): 259-299.]）。

> 4、[Malkiel and Xu (2006)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.8.8510&rep=rep1&type=pdf)^[Malkiel B G, Xu Y. Idiosyncratic risk and security returns[J]. University of Texas at Dallas (November 2002), 2002.], [Spiegel and Wang (2006)](https://ssrn.com/abstract=709781)^[Spiegel M I, Wang X. Cross-sectional variation in stock returns: Liquidity and idiosyncratic risk[J].2005.], [Chua, Goh, and Zhang (2007)](https://doi.org/10.1111/j.1475-6803.2010.01264.x)^[Chua C T, Goh J, Zhang Z. Expected volatility, unexpected volatility, and the cross‐section of stock returns[J]. Journal of Financial Research, 2010, 33(2): 103-123.], and [Diavatopoulos, Doran, and Peterson (2008)](https://doi.org/10.1002/fut.20327)^[Diavatopoulos D, Doran J S, Peterson D R. The information content in implied idiosyncratic volatility and the cross‐section of stock returns: Evidence from the option markets[J]. Journal of Futures Markets: Futures, Options, and Other Derivative Products, 2008, 28(11): 1013-1039.], and [Fu (2009)](https://doi.org/10.1016/j.jfineco.2008.02.003)^[Fu F. Idiosyncratic risk and the cross-section of expected stock returns[J]. Journal of financial Economics, 2009, 91(1): 24-37.]使用其他公司层面的波动作为特质波动的代理变量，发现特质波动与收益之间具有正向关系，表明Ang et al 使用的特质波动度量不能捕捉预期的特质风险。

> 5、Doran, Jiang, and Peterson (2008)^[Doran J, Jiang D, Peterson D. Gambling in the New Year? The January idiosyncratic volatility puzzle[J]. Unpublished working paper, Florida State University, 2008.]发现，由于高特质波动的公司在一月获得了较高的超额收益，剔除一月效应后，特质波动与收益的负向关系任然稳健，

> 6、[Jiang, Xu, and Yao (2007)](https://www.jstor.org/stable/40505913)^[Jiang G J, Xu D, Yao T. The information content of idiosyncratic volatility[J]. Journal of Financial and Quantitative Analysis, 2009: 1-28.]发现，高特质波动的股票表现不佳是由于未来盈利不佳的企业逆向选择的结果，这些企业往往披露较少的信息，创造了更大的特质风险。 

> 7、[Boyer, Mitton, and Vorkink(2008)](https://doi.org/10.1093/rfs/hhp041)^[Boyer B, Mitton T, Vorkink K. Expected idiosyncratic skewness[J]. The Review of Financial Studies, 2010, 23(1): 169-202.]发现特质波动与收益的反向关系由偏度与收益的负向关系驱动。

> 8、[Han and Kumar (2008)](http://efalken.com/pdfs/HanKumarIdioretPuzzle.pdf)^[Han B, Kumar A. Retail clienteles and the idiosyncratic volatility puzzle[J]. Unpublished working Paper, University of Texas at Austin, 2008.]发现波动与收益的负向关系只有出现在散户主动交易的股票中。由于散户更可能是非知情交易者，更可能出现行为偏差，表明波动与收益的负向关系可能由噪声交易驱动。

> **异质信念与卖空限制**

> 特质波动是投资者意见分歧和噪声交易的代理变量

> 9、Miller ([1977](https://doi.org/10.2307/2326520)^[Miller E M. Risk, uncertainty, and divergence of opinion[J]. The Journal of finance, 1977, 32(4): 1151-1168.], [2001](https://doi.org/10.3905/jpm.2001.319791)^[Miller E M. Why the low returns to beta and other forms of risk[J]. The Journal of Portfolio Management, 2001, 27(2): 40-55.])发现公司基本面不确定性或波动与投资者意见分歧正相关。

> 10、[Delong et al（1990）](https://doi.org/10.1086/261703)^[De Long J B, Shleifer A, Summers L H, et al. Noise trader risk in financial markets[J]. Journal of political Economy, 1990, 98(4): 703-738.]发现股票市场的噪声交易产生了超额波动。

> 11、[Odean(1998)](https://doi.org/10.1111/0022-1082.00078)^[Odean T. Volume, volatility, price, and profit when all traders are above average[J]. The journal of finance, 1998, 53(6): 1887-1934.], [Daniel, Hirshleifer, and Subrahmanyam (1998)](https://doi.org/10.1111/0022-1082.00077)^[Daniel K, Hirshleifer D, Subrahmanyam A. Investor psychology and security market under‐and overreactions[J]. the Journal of Finance, 1998, 53(6): 1839-1885.] (2003)基于过度自信的行为模型预测了投资者由于过度自信而产生了超额波动。在这些模型中，收益波动代表现金流波动和噪声交易。

> 12、[Barberis and Xiong (2008)](https://doi.org/10.1016/j.jfineco.2011.10.005)^[Barberis N, Xiong W. Realization utility[J]. Journal of Financial Economics, 2012, 104(2): 251-271.]提出，当投资者从交易获利时，投资者获得一个正向的激励，从而被吸引到高波动的证券上，引起了误定价和后期的低收益。

> 13、[Scheinkman and Xiong (2003)](https://doi.org/10.1086/378531)^[Scheinkman J A, Xiong W. Overconfidence and speculative bubbles[J]. Journal of political Economy, 2003, 111(6): 1183-1220.]证明了，在卖空限制下，对其他投资者来说，过度自信导致的异质信念创造了为其后续高价卖出创造了机会。

> 14、[Hong, Scheinkman, and Xiong (2006)](https://doi.org/10.1111/j.1540-6261.2006.00867.x)^[Hong H, Scheinkman J, Xiong W. Asset float and speculative bubbles[J]. The journal of finance, 2006, 61(3): 1073-1117.]进一步研究表明，当卖空限制被放松时，市场泡沫可能会破裂。



### 研究结论

> 1、高波动股票，特别是大盘股，在事件窗口期内更容易被高估，这种高估部分原因是由于卖空限制阻碍了理性套利。

> 2、高特质波动的公司价格向下的反应更强。