---
title: 机构投资者提高了价格效率吗？
author: 薛英杰
date: '2021-04-03'
slug: 机构投资者提高了价格效率吗
categories:
  - research
tags:
  - research
---

> 信息在金融和经济资源配置中发挥了关键作用。Fama(1970)提出了有效市场假说，认为有效的市场中，信息可以被快速、准确、完整地纳入股票价格，投资者不能从市场中获得超额收益。因此，信息是股票定价的前提，反映了上市公司价值状态，对市场质量的影响至关重要。而定价效率是衡量股票价格整合市场信息的能力重要指标，反映了资本市场的质量。股价能否有效地反映上市公司的价值信息，一方面，取决于套利者和做市商收集、处理信息的效率和交易能力，当价格偏离价值时，掌握信息的套利者和做市商进入会消除误定价，从而使价格向价值收敛，另一方面，取决于市场信息环境，套利者和做市商的行为可能受金融摩擦（例如：资本限制，交易成本，卖空约束和特质波动）影响（[Rösch et al.,2017](https://doi.org/10.1093/rfs/hhw085) ^[Rösch D M, Subrahmanyam A, Van Dijk M A. The dynamics of market efficiency[J]. The review of financial studies, 2017, 30(4): 1151-1187.]），而不能完成套利，消除误定价，导致资产的定价效率较低。

从市场微观结构来看，市场主体由机构投资者和散户构成，但不同市场这两类投资者的比例不同。在美国等发达的资本市场，市场参与主体主要以机构投资者为主，而像中国这样的新型市场，则是散户主导的市场。与散户相比，机构投资者拥有专业的投资知识、经验和较强的信息搜集、分析能力，能对上市公司的估值和发展潜力做出客观的判断，因此，其交易行为使得更多的信息融入股价，并不会导致系统的定价误差。


众所周知，金融市场是一个信息交易市场，投资者根据自己掌握的信息判断未来资产价格趋势，并做出交易决策。但信息获取、处理、分析和交易是一个复杂的过程，每个环节出现问题都会导致信息无法被投资者传播到市场，从而影响市场的定价效率。

关于机构投资者对定价效率影响的解释主要从三个层面展开，一是公司治理，他们认为机构投资者持股越多，其在董事会越有话语权，可以通过有效地监督经理人来提高公司业绩，还可以促使上市公司披露有关信息，提高信息透明度。二是机构投资者信息挖掘优势，与散户投资者相比，机构投资者具有专业的投资知识，旗下有专门从事行业和公司研究的团队，生产信息能力较强，分析师发布研报是市场信息的主要来源。三是交易摩擦，资本限制、交易成本、卖空限制等交易摩擦存在，都影响了投资者的交易意愿，使其不愿或不能交易，从而导致股价信息含量降低。随着互联网飞速发展，信息传播的速度越来越快，投资者了解信息的渠道越来越多，金融市场已经越来越有信息。


