---
title: ETF持股影响股票定价效率的理论模型推导
author: ''
date: '2021-01-14'
slug: etf持股影响股票定价效率的理论模型推导
categories:
  - research
tags:
  - research
---

### 机理分析

定价效率是证券价格反映信息的能力，表现在股价反映信息的速度和准确性上（Saffi and Sigurdsson，2011）。关于证券市场信息与定价效率的关系在理论界已做出了充分的研究，提出了有效市场理论、金融市场噪声理论和交易摩擦理论等。目前，学术界普遍认为，ETF主要通过交易成本和限制等市场摩擦影响成分股的定价效率。与发达市场不同，A股市场各项制度和规则不够完善，交易成本较高，卖空限制严重，散户投资者持有市场88%的流通股（Liu et al.，2019），这都会影响定价效率。而且，高效价格发现机制的形成，离不开发达的信息中介机构和相对成熟的投资者群体（朱红军等，2008），中介机构的信息生产和挖掘能力也是影响定价效率的重要因素。因此，我们认为交易成本、卖空限制和信息挖掘三种是ETF影响定价效率的中介渠道。


### 模型建立

我们的模型尝试捕获证券市场的四个主要特征：（1）投资者异质性，（2）交易成本非零，（3）卖空存在限制，（4）知情投资者主动挖掘市场信息。投资者异质性体现在投资者的风险承担和关于未来资产回报信息上的差异，他们出于承担风险和信息投机的目的而交易。


> 证券市场

市场持续存在两期，分别为0期与1期，投资者在竞争的证券市场上交易，可交易的产品有无风险债券、股票和ETF基金，在1期，投资者获得投资收益，假定每单位债券的固定收益为1，股票价值为$V=F+\mu$，其中$\mu$和$F$分别为相互独立的均匀分布，$F\sim U[-a_F,a_F]$，$\mu\sim U[-a_\mu,a_\mu]$

> 投资者

市场上有两类投资者，一类为知情投资者，另一类为非知情投资者，每一类投资者完全相同，而且知情投资者与非知情投资者面临的信息不同，知情交易者掌握其投资资产的所有信息，非知情交易者通过资产价格来推断该资产价值相关的信息，假设一个投资者为知情交易者的概率为$w$，则为非知情交易者的概率为$1-w$。

> 禀赋

每位投资者$i（i=I,U）$初始的债券禀赋为零，$\bar\theta$单位的股票资产，投资者通过选择1期持股有的股票量$\theta_i$来最大化期望效用

>  信息结构

在0期，知情投资者观察到私有信息$F$，所有投资者都能观察到股票的市场价格$P$，这样知情投资者的信息集为$I_I=\{F,P\}$，非知情交易者的信息集为$I_U=\{P\}$，在1期所有不确定性都被消除。

> 财富及效用函数

每一位投资者都是风险厌恶者，其对效用函数为Markowiz-Tobin均值方差函数，让$\theta_i$表示投资者$i$最有持股，$w_i$为投资者$i$在1期的最终财富，具体公式如下：

$$W_i=\bar\theta P+\theta_i(V-P)$$

投资者效用函数为：

$$E[W_i|I_i]-\frac{1}{2}Var[W_i|I_i]$$


> **ETF持股作为外生冲击，通过交易成本、卖空限制，信息挖掘三种渠道来影响投资的决策行为。交易成本主要影响投资者从股票价格获取信息的准确性，卖空限制影响投资者对资产的需求，信息挖掘影响投资者成为知情投资的概率，ETF持股比例越高，股票交易成本越低，卖空限制越小，信息挖掘越充分，投资者成为知情交易者的概率越高，从股票价格中获取的信息越准确。**假设ETF持有股票i的市值比例为$\eta$，则投资者成为知情交易者的概率$w$是ETF持股比例的增函数，卖空限制和交易成本是ETF持股比例的减函数。


### 模型求解

> 投资者最大化期望效用，具体如下：

$$Max \hspace{0.4cm} E[W_i|I_i]-\frac{1}{2}Var[W_i|I_i] \hspace{0.4cm}i=I,U\\
s.t \hspace{0.4cm} W_i=\bar\theta P+\theta_i(V-P)$$


由于$E[W_i|I_i]=\bar\theta P+\theta_i(E[F|I_i]-P)$,$Var[W_i|I_i]=\theta_i^2(Var[F|I_i]+\sigma_u^2)$,则投资者的效用为：

$$U_i(W_i)=\bar\theta P+\theta_i(E[F|I_i]-P)-\frac{1}{2}\theta_i^2(Var[F|I_i]+\sigma_u^2)$$
一阶条件为：

$$\frac{\partial U_i}{\partial \theta_i}=(E[F|I_i]-P)-\theta_i(Var[F|I_i]+\sigma_u^2)=0$$
$$\theta_i=\frac{E[F|I_i]-P}{Var[F|I_i]+\sigma_u^2}$$

> (1)投资者信息对称

在信息对称条件下，$P$、$F$均为公开信息，投资者的交易成本为0，知情交易者与非知情交易者面临相同的信息集，即$I_u=I_I=\{F,P\}$，此时，$E[F|I_I]=E[F|I_U]=F$,$Var[F|I_I]=Var[F|I_U]=0$。

投资者的需求函数为：

$$\theta_I=\theta_U=\frac{F-P}{\sigma_u^2}$$

均衡价格为：

$$P^\star=F-\sigma_u^2\bar\theta$$

> (2)信息不对称

当信息不对称时，两类投资者掌握的信息不同，知情投资者掌握股票价值和价格信息，非知情投资者掌握价格信息，只能通过价格来推断资产价值信息。由于信息不对称条件下，求解比较复杂，参考Yang Bai et al.研究，我们先猜测一种均衡下的价格函数，在此价格函数下推导出投资者的需求，并证明在此均衡价格下市场出清。我们认为股票价格取决于经济状态变量，受交易成本和噪声影响，且股票价格只取决于信号$S=\frac{1}{2}(F-c\varepsilon)$，股票价格是$S$的严格增函数。其中，$c\varepsilon \sim U[-a_F,a_F]$，$0< c\leq1$。

对于知情交易者来说，在信息集$I=\{F,P\}$下的需求函数为：

$$\theta_I==\frac{F-P}{\sigma_u^2}$$

对于非知情交易者来说，在信息集$I=\{P\}$下，$E[F|I_U]=E[F|P]=E[F|S]$，$Var[F|I_U]=Var[F|P]=Var[F|S]$。由于$c\varepsilon$与$F$独立同分布，则其联合密度函数为$f(F,\varepsilon)=f_F(F)f_{\varepsilon}(\varepsilon)$，且$\varepsilon=\frac{F-2S}{c}$，则$S$的概率密度函数为：

$$f(S)=\int f(F,\frac{F-2S}{c})dF=\int f_F(F)f_{\varepsilon}(\frac{F-2S}{c})dF\\
 \hspace{5cm}=\frac{1}{4a_F^2}\int I[-a_F<F<a_F]I[-ca_F+2S<F<ca_F+2S]dF$$
 
由于$F$同时属于区间$[-a_F<F<a_F]$和$[-ca_F+2S<F<ca_F+2S]$，则需要取其交集，对$S$进行讨论。

当$S\ge\frac{(1-c)a_F}{2}$时，$F\in [-ca_F+2S,a_F]$，则

$$f(S)=\frac{1}{4a_F^2}\int _{-ca_F+2S}^{a_F}dF=\frac{(1+c)a_F-2S}{4a_F^2}$$

当$S\le-\frac{(1-c)a_F}{2}$时，$F\in [-a_F,ca_F+2S]$，则

$$f(S)=\frac{1}{4a_F^2}\int _{-a_F}^{ca_F+2S}dF=\frac{(1+c)a_F+2S}{4a_F^2}$$
当$-\frac{(1-c)a_F}{2}<S<\frac{(1-c)a_F}{2}$时，$F\in [-ca_F+2S,ca_F+2S]$，则

$$f(S)=\frac{1}{4a_F^2}\int _{-ca_F+2S}^{ca_F+2S}dF=\frac{2ca_F}{4a_F^2}$$

因此，我们便可求得条件概率密度函数，具体如下：

$$\begin{equation}
f(F|S)=f(F,F-2S)/f(S)=\left\{
\begin{aligned}
&\frac{1}{(1+c)a_F-2S}I[-ca_F+2S,a_F](F),\hspace{0.5cm}S\ge\frac{(1-c)a_F}{2} \\
&\frac{1}{2ca_F}I[-ca_F+2S,ca_F+2S](F),\hspace{0.5cm}\frac{(1-c)a_F}{2}\ge S\ge-\frac{(1-c)a_F}{2} \\
&\frac{1}{(1+c)a_F+2S}I[-a_F,ca_F+2S](F),\hspace{0.5cm}S\le-\frac{(1-c)a_F}{2} 
\end{aligned}
\right.
\end{equation}$$

求得条件均值与条件方差如下：

$$\begin{equation}
E[F|S]=\int Ff(F|S)dF=\left\{
\begin{aligned}
&\frac{1}{(1+c)a_F-2S}\int _{-ca_F+2S}^{a_F}FdF,\hspace{0.5cm}S\ge\frac{(1-c)a_F}{2} \\
&\frac{1}{2ca_F}\int _{-ca_F+2S}^{ca_F+2S}FdF,\hspace{0.5cm}\frac{(1-c)a_F}{2}\ge S\ge-\frac{(1-c)a_F}{2} \\
&\frac{1}{(1+c)a_F+2S)}\int _{-a_F}^{ca_F+2S}FdF,\hspace{0.5cm}S\le-\frac{(1-c)a_F}{2}  
\end{aligned}
\right.\\ \hspace{4cm}
=\left\{
\begin{aligned}
&\frac{(1-c^2)a_F+4S(ca_F-S)}{2((1+c)a_F-2S))},\hspace{0.5cm}S\ge\frac{(1-c)a_F}{2} \\
&2S,\hspace{0.5cm}\frac{(1-c)a_F}{2}\ge S\ge-\frac{(1-c)a_F}{2} \\
&\frac{(c^2-1)a_F+4S(ca_F+S)}{2((1+c)a_F+2S))},\hspace{0.5cm}S\le-\frac{(1-c)a_F}{2}  
\end{aligned}
\right.
\end{equation}$$

$$\begin{equation}
E[F^2|S]=\int F^2f(F|S)dF=\left\{
\begin{aligned}
&\frac{1}{(1+c)a_F-2S}\int _{-ca_F+2S}^{a_F}F^2dF,\hspace{0.5cm}S\ge\frac{(1-c)a_F}{2} \\
&\frac{1}{2ca_F}\int _{-ca_F+2S}^{ca_F+2S}F^2dF,\hspace{0.5cm}\frac{(1-c)a_F}{2}\ge S\ge-\frac{(1-c)a_F}{2} \\
&\frac{1}{(1+c)a_F+2S)}\int _{-a_F}^{ca_F+2S}F^2dF,\hspace{0.5cm}S\le-\frac{(1-c)a_F}{2}  
\end{aligned}
\right.\\ \hspace{4cm}
=\left\{
\begin{aligned}
&\frac{a_F^3-(2S-ca_F)^3}{3((1+c)a_F-2S))},\hspace{0.5cm}S\ge\frac{(1-c)a_F}{2} \\
&4S^2+c^2a_F^2/3,\hspace{0.5cm}\frac{(1-c)a_F}{2}\ge S\ge-\frac{(1-c)a_F}{2} \\
&\frac{(c^2-1)a_F+4S(ca_F+S)}{2((1+c)a_F+2S))},\hspace{0.5cm}S\le-\frac{(1-c)a_F}{2}  
\end{aligned}
\right.
\end{equation}$$
为了方便计算，令$\frac{(1-c)a_F}{2}\ge S\ge-\frac{(1-c)a_F}{2}$

此时,$F$的条件均值、方差和非知情交易者的需求函数分别为

$$E[F|S]=2S$$

$$Var[F|S]=\frac{c^2a_F^2}{3}$$

$$\theta_U=\frac{S-P}{\frac{1}{3}(c^2a_F^2)+\sigma_u^2}$$

将$\theta_I$和$\theta_U$代入市场出清条件$w\theta_I+(1-w)\theta_U=\bar\theta$得

$$w\frac{F-P}{\sigma_u^2}+(1-w)\frac{S-P}{\frac{1}{3}(c^2a_F^2)+\sigma_u^2}=\bar\theta$$
解得均衡价格为：

$$P=2S+c\varepsilon-\bar\theta\sigma_u^2-(1-w)\frac{S+c\varepsilon+\frac{1}{3}c^2a_F^2\bar\theta}{1+\frac{1}{3}wc^2a_F^2/\sigma_u^2}$$

将均衡价格代入需求函数，得到均衡需求如下：

$$\theta_I=\bar\theta+(1-w)\frac{S+c\varepsilon+\frac{1}{3}c^2a_F^2\bar\theta}{\sigma_u^2+\frac{1}{3}wc^2a_F^2}$$

$$\theta_U=\bar\theta-w\frac{S+c\varepsilon+\frac{1}{3}c^2a_F^2\bar\theta}{\sigma_u^2+\frac{1}{3}wc^2a_F^2}$$

### 均衡价格，最有需求模拟

参数设定，$a_u=a_F=2$，$\theta=0.1$，$w=0.5$，$c=0.01$，具体代码如下：
```{r,warning=FALSE}
set.seed(100)
theta=0.1
au<-af<-2
simamu=au^2/3
c=0
w=0.5
epsilon<-runif(101,-2,2)
S=seq(-1,1,0.02)
P=2*S+c*epsilon-theta*simamu-(1-w)*((S+c*epsilon+c^2*af^2*theta/3)/(1+w*c^2*af^2/simamu/3))

plot(S,P,lty=3,xlim = c(-1,1))

abline(v=0,col="red")
abline(h=0,col="blue")

thetaI=theta+(1-w)*((S+c*epsilon+c^2*af^2*theta/3)/(simamu+w*c^2*af^2/3))
thetaU=theta-w*((S+c*epsilon+c^2*af^2*theta/3)/(simamu+w*c^2*af^2/3))

plot(S,thetaI,type = "l",col="red")
lines(S,thetaU,col="blue",lty=3)
```

