---
title: 贝塔异象
author: 薛英杰
date: '2025-02-24'
slug: beta anomly
categories:
  - research
tags:
  - research
bibliography: references.bib
---

## Betting against beta

### 摘要

> 我们提出了一个带杠杆和保证金约束的模型，该模型随投资者和时间变化。我们发现了与模型的 五个中心假设一致的证据。（1）由于受约束的投资者哄抬高贝塔资产的价格，导致高贝塔的资产获得的 alpha 较低，这与我们在美国股票、20个国际股票市场、美国国债、公司债券和期货市场的实证发现一致。 （2）赌博高贝塔因子[^1]产生了显著正的风险调整收益。（3）当融资约束收紧时，赌博贝塔因子的收益降低。（4）增加的流动性风险会将beta压缩到1.（5）更大约束的投资者持有更高风险的资产。

[^1]: 赌博高低贝因子是做多加杠杆的低贝塔资产，做空高贝塔资产的投资组合收益。

### 研究问题

> 资本资产定价模型的基本假设是所有代理人都投资单位风险带来期望收益最高的投资组合， 并通过加杠杆或去杠杆来迎合他们的风险偏好。许多投资者，像散户，养老基金和共同基金，他们 承担的杠杆都存在约束。**因此，高风险的资产将替代使用杠杆。这种向高贝塔资产倾斜的行为表明，高风险的高贝塔资产需要比低贝塔资产更低的风险调整回报**

> **那么，不受约束的套利者如何利用这一效应，即，你怎么赌β？相对于市值、价值和动量效应的大小这个异象的大小是多少？在其他国家和资产类别中，做空贝塔值是否会获得回报？收益溢价如何随时间和横截面而变化？谁敢赌贝塔？**

### 研究思路

> 为了回答以上问题，本文建立了一个带杠杆约束的动态模型，并利用20个国家股票市场、国库券市场、信用债市场和期货市场的数据检验了该模型的推论。在实证中，本文在全球市场检验了基于beta的投资组合检验，然后，构造了赌博beta因子。

### 文献观点

> 1.美国股票的证券市场线要比资本资产定价模型（CAPM）更加平坦，带有借贷约束的CAPM模型比标准的CAPM模型对美股收益的解释更好[@mehrling2011; @black1972a]。
>
> 2.看沃伦巴菲特伯克希尔哈撒韦公司的持股，可以发现巴菲特通过购买低贝塔股票并运用刚来押注贝塔[@frazzini2018]。
>
> 3.高贝塔的股票经风险调整后的收益率较低[@baker2011]。

### 理论分析

> 我们考虑一个时代更替的经济，在这个经济中，每个时期$t$，代理人$i=1,\dots,I$出生都携带财富$W_t^i$，并生存两期。代理人交易证券$s=1,\dots,S$。其中，证券$s$支付红利$\delta_t^s$，有$\chi^{*s}$份流通股。在每个时期$t$，年轻的代理人选择份额为$\chi=(\chi^1,\dots,\chi^S)^\prime$的投资组合，其余财富投资收益率为$r^f$的无风险资产，以最大化他的效用：


$$
Max:  x\prime(E_t(P_{t+1}+\delta_{t+1})-(1+r^f)P_t)-\frac{\gamma^i}{2}\chi^\prime\Omega_t\chi
$$

> 其中，$P_t$是$t$时期的价格向量，$\Omega$是$P_{t+1}+\delta_{t+1}$方差-协方差矩阵，$\gamma^i$是代理人$i$的风险厌恶。代理人$i$的预算约束如下：

$$
m_t^i\sum_{s}\chi^sP^s_t\leq W^i_t
$$

> 乘子$m^i$为代理人的投资所使用的杠杆，这个约束要求股票份额与价格的乘积小于代理人的财富。


> 投资约束取决于代理人$i$。例如，一些代理人不能使用杠杆，在模型中通过$m^i=1$来捕获。其他代理人不仅不能使用杠杆，而且必须有一部分现金财富，这个由大于$m$大于1来捕获，而且他们面临保证金约束。


> 我们非常感兴趣总需求等于总供给时的性质：

$$
\sum_i\chi^i=\chi^*
$$

> 为了求均衡解，我们让一阶条件等于0，具体如下：

$$
E_t(P_{t+1}+\delta_{t+1})-(1+r^f)P_t-\gamma^i\Omega \chi^i-\phi^i_tP_t=0
$$

> 其中，$\phi^i$组合约束的拉格朗日乘数。解得$x^i$的最优头寸为：

$$
x^i=\frac{1}{\gamma^i}\Omega ^{-1}(E_t(P_{t+1}+\delta_{t+1})-(1+r^f+\phi^i_t)P_t)
$$


> 对所有代理人的头寸进行加总将得到均衡条件：

$$
\chi^*=\frac{1}{\gamma}\Omega ^{-1}(E_t(P_{t+1}+\delta_{t+1})-(1+r^f+\phi_t)P_t)
$$

> 均衡价格和收益如下：

$$
P=\frac{E_t(P_{t+1}+\delta_{t+1})-\gamma\Omega\chi^*}{1+r^f+\phi_t}
$$

$$
r_{t+1}^i=\frac{P^i_{t+1}+\delta^i_{t+1}}{P^i_t}-1
$$

> 假设市场收益为$r_{t+1}^M$，则贝塔可以表示为：

$$
\beta_t^s=\frac{cov_t(r_{t+1}^s,r_{t+1}^M)}{var_t(r_{t+1}^M)}
$$

> **推论1：**

> （1）对于任何资产$s$的均衡收益为：$E_t(r^s_{t+1})=r^f+\phi_t+\beta_t^s\lambda_t$。其中，风险溢价
$\lambda_t=E_t(r_{t+1}^M-r^f-\phi_t)$,$\phi_t$平均拉格朗日乘子，测量了融资约束的紧张程度
。

> （2）一个证券相对市场的超额收益$\alpha^s=\phi_t(1-\beta_t^s)$，该$\alpha$随着$\beta$上升而递减。


>  （3） 对于一个有效的投资组合，夏普比率在贝塔系数小于1的有效投资组合中最高，贝塔系数越高，夏普比率越小，贝塔系数越小。


> **下面我们将考虑做多低贝塔资产，多空高贝塔资产的因子的性质**。为了构建一个因子，让$w_L$是一个相对低贝塔资产组合权重，则低贝塔组合收益为$r_{t+1}^L=w_Lr_{t+1}$，同时考虑类似的高贝塔资产组合收益$r_{t+1}^H$，组合贝塔分别为$\beta_t^L$和$\beta_{t+1}^H$，且$\beta_t^L<\beta_t^H$。这样我们可以构建赌博贝塔因子:

$$
r_{t+1}^{BAB}=\frac{1}{\beta_t^L}(r_{t+1}^L-r^f)-\frac{1}{\beta_t^H}(r_{t+1}^H-r^f)
$$

> **推论2：**

> 赌博贝塔因子的超额收益为正：
 
$$
E_t(r_{t+1}^{BAB})=\frac{\beta_t^H-\beta_t^L}{\beta_t^H \beta_t^L}\phi_t\geq 0
$$

> **推论3**


> 组合约束（$m^k$）的冲击效应，可以解释为在极端信用危机中资金流动性恶化。这种资金流动性冲击导致BAB因子的损失，因为其要求的回报增加。因为投资者可能需要降低他们对贝塔值的押注，或者进一步扩大购买高贝塔值资产的规模。

> 组合约束越紧，意味着$m^k$上升，将导致BAB因子收益下降，未来获得的收益上升。具体如下：

$$
\frac{\partial r_t^{BAB}}{\partial m_t^k}\leq 0
$$
$$
\frac{\partial E_t(r_t^{BAB})}{\partial m_t^k}\leq 0
$$

> **推论4**

> 假设所有随机变量都是独立同分布，$\delta_t$与其他随机变量无关。此外，在时间t-1在BAB组合形成并设定价格后，由于$m_t$和$W_t$的新信息，贴现因子$\frac{1}{1+r^f+\phi_t}$的条件方差上升（下降）。

> 1. 所有证券的条件收益$beta$被压缩到1
> 2. BAB投资组合的条件贝塔系数变为正（负），即使它相对于用于投资组合形成的信息集是市场中性的。

> **推论5**

> 不受约束的代理持有风险证券的投资组合的贝塔系数小于1;受约束的代理持有风险证券的投资组合，具有较高的贝塔系数。