---
title: 机器学习与股票收益预测
author: 薛英杰
date: '2024-06-09'
slug: machine learning and stock return predict
categories:
  - research
tags:
  - research
bibliography: [one.bib]
link-citations: TRUE
bilbio-style: "biomed-central.csl"
---

## Machine learning in the Chinese stock market

### 研究背景

> 截至2020年，中国股票市场的价值已经创历史新高，达到100亿美元。国家经济从疫情中加速恢复已经超过了2015年股票泡沫期间的高点，使中国成为第二大资本市场。然而，不仅仅是规模，中国市场的特殊性使这个市场对学术研究更有吸引力，并使我能够探索理解新型市场的问题，补充我们对其他金融体系的了解。
>
> As of October 2020, the total value of China's stock market **has climbed a record high**[^1] of more than USD 10 trillions. As county's accelerating economic recovery from COVID-19 pandemic has surpassed previous high reached during the equity bubble in 2015, making it the second-largest in the word. However, it not only size, but equally important, the specificity of the Chinese stock market that makes this market particularly attractive for academic researcher and allows us to explore question that contribute to understanding of emerging market and complement our knowledge of financial system in other institutional settings.

[^1]: has climbed a record high：创历史新高

### 中国市场的主要特征

> -   发达的市场主要有机构投资者主导，而中国资本市场主要由散户主导。散户的投机和短期交易动机导致换手率增加。
>
>     The developed markets that are dominated by institutional investors, the Chinese stock market is dominated by retail investors. The speculative and short-term trading motives of many retail investors lead to increased turnover.
>
> -   从制度的角度来看，中国金融体系的核心特征是由中央控制、银行主导的独一无二的关系驱动。另外，当股票价格低于基本面价值时，上市公司（特别是国有企业）的被阻止回购。这样，自发的市场纠正机制受政府导向限制的影响。所以，国有企业的突出作用应该因其重要性和独一性而被特殊对待。他们不仅经常因为缺乏信息透明度而遭批评，还因为其政治目标偏离价值最大化损害了企业业绩。
>
>     The key characteristic of China's financial system from an institutional perspective is centrally controlled, bank-dominated and uniquely relationship driven. On the other hand, listed companies, especially state-owned enterprise, are prevent share buy-back when the stock price fall below the fundamental value. listed companies. Therefore, the automatic market correction mechanisms are affected by government-oriented restrictions. The SOEs' prominent role in China's capital markets deserve a different treatment for their importance and uniqueness. Not only are the criticized for the lack of information transparency, But the departure of SOEs' political objectives from value maximization may harm their cooperate performance.
>
> -   中国市场的卖空历史有限，许多学者认为卖空有助于价格发现，进而使得市场更加有效。而美国和欧洲市场的因子投资研究依赖于多空策略，这样的策略在中国市场无法实现。
>
>     The Chinese market has a limited history of short-selling, many academics agree that short-selling help price discovery, rendering market more efficiency. Most of studies on factor investing on US and Europe markets relies on long-short strategies, such a strategy is not realized in Chinese market.

### 研究目的

> 当前，中国市场没有大型因子数据可以利用，本文想构建大量因子数据，并期望通过机器学习的方法来检验那些因子在中国资本市场定价中发挥主要作用。

### 研究结论

> 本文研究了几个机器学习方法对中国股票市场的预测能力，发现最重要的因子是与流动性相关的交易信号。让人惊讶的是基于价格动量的信号之发挥了一小部分作用。基本面因子是第二重要的因子，短期交易的投资者产生很大的可预测性，特别是小盘股。国有企业在长期的预测性会增加。而且，神经网络模型在预测中是表现最稳定的，即使在2015年市场大幅下跌时也没有明显回撤。

## [Anomalies and the expected Market Return](https://doi.org/10.1111/jofi.13099)

### 摘要

> 我们首次系统地证明了多空异象投资组合收益（横截面文献的基石）与总市场超额收益的时间序列可预测性之间的联系。使用文献中的100个典型异象，我们使用了各种降维技术(包括机器学习、预测组合和降维)来有效地提取高维环境中的预测信号。我们发现，多空异象投资组合收益对市场超额收益具有显著的样本外预测能力。异象投资组合收益的预测能力似乎源于套利的不对称限制和过高定价的修正持久性。

### 研究背景与问题

> 股票收益预测是金融中的一个基本话题，而关于该话题的研究主要由两种路线。一是检验上市公司特征是否可以预测股票横截面收益的变化，并发现了多种异象；二是基于宏观经济变量研究市场超额收益在时间序列上的可预测性，例如，利率，通货膨胀率以及估值率，他们强调这些变量对股权风险溢价的影响。那么，这两条主线是否存在联系？也就是说，来自于上市公司特征的异象投资组合是否对市场收益有预测性。

### 研究内容

> -   本文将研究的重点放在横截面多空异象收益预测的关键文献上，由于这些研究将异象收益视为错误定价的证据。

> -   本文应用了样本外检验方法，这种检验提供了最严格和最相关的股票收益可预测的证据。

> -   检验了以横截面研究文献为代表的多空异象投资组合收益的预测能力，同时汇总了这些异象收益的信息。

> -   探讨了多空异常投资组合收益能够预测市场收益的经济学原理，从而用经济分析补充了我们的统计结果。

### 文献观点

> -   套利限制源于多种多样的摩擦[@gromb2010]。
> -   在 @gârleanu2013 、 @gârleanu2016 和 @dong2020fast 建立的模型中，风险承受能力有限和交易成本等摩擦导致套利者纠正错误定价的速度很慢。
> -   在实证研究中，套利限制的主要变量有总流动性[@pástor2003]、特质风险[@ang2006; @pontiff2006]、交易噪声[@hu2013]、经济不确定性[@jurado2015]、风险厌恶指数[@bekaert2022a]、卖空成本[@asness2018]。

### 研究结论

> 在实证上，我们发现，如果我们依赖防止数据过度拟合的策略，100个多空异常投资组合收益组中的信息对于预测非样本基础上的月度市场超额收益确实是有用的。在经济意义上，多空异象组合收益对市场收益的预测力可以被非对称错误定价修正持续性解释，这种错误定价修正的非对称性源于套利限制非对称。

> 本文的实证结果显示，多头和空头收益与未来市场收益正相关，而样本外预测能力较弱意味着错误定价修正更强，导致多空异象收益对未来收益有负向预测作用。

### 参考文献
