---
title: 被动投资兴起的经济后果
author: 薛英杰
date: '2025-01-13'
slug: the rise of passive investing
categories:
  - research
tags:
  - research
bibliography: [one.bib]
link-citations: TRUE
bilbio-style: "biomed-central.csl"
---

## Rise of Passive Investing: Effects on Price Level, Market Volatility, and Price Informativeness

### 摘要

> 过去20年，被动投资策略快速发展，引起了人们关于其对市场效率和稳定性的担忧，为了 回答这些问题，本文构建了一个理性预期均衡模型，允许投资者选择不同的投资模式（主动，被动和委托主动），引入代理异质性，并使用2000年至2017年的数据估计模型。该模型认为投资费用是外生的，这些费用的变化会影响投资者选择不同投资工具的分布变化。我发现，被动投资的增长并没有增加整体价格水平，从而与常见的ETF泡沫假说相矛盾，该假说假设被动策略的快速增长可能导致这些证券的价格脱离基本面。此外，该模型表明，这种投资转变加剧了资产价格波动，这与实证研究结果一致。我们估计，目前市场波动的10%左右可以归因于被动投资的兴起。由于信息获取能力减弱，这也导致价格信息量减少。进一步降低被动管理费将加强这些效果。与委托主动投资相关\
> \|的费用减少可能对被动投资的比例产生模糊的影响，但会导致价格波动加剧和信息量减少，类似于被动费用减少中观察到的动态。

### 研究问题

> 近年来，人们对被动投资策略的兴趣激增，被动指数基金的数量和规模快速增长，而主动管理基金的规模逐渐减少。主动基金的业绩评价不再以绝对收益作为标准，而是将评价重点转移到其相对整个市场的超额收益。这种评价将主动投资刻画为零和游戏，一些主动基金经理能超越市场，而其他的基金经理落后市场[@sharpe1991arithmetic]。
>
> 根据 @sushko ，当考虑与主动管理相关的交易成本和费用后，比较两类投资的平均收益，被动投资可能是最优的投资策略。加上被动投资的可获得性增加，使其成为投资者和散户的首选投资策略。
>
> 在二十世纪末，被动投资者在资本市场中处于边缘地位，这样，被分析师和经济学家的关注也很有限。近年来，被动投资的快速增长引发了对其市场影响的研究，鉴于这一趋势快速演变，关于该话题的研究仍然有限，并且潜在的挑战似乎没有的到充分解决。**首先，对于被动投资增加可能引起被动投资泡沫，其次，被动投资可能导致资产价格波动，最后，被动投资可能影响资产价格信息。**
>
> 为了回答以上问题，本文建立了带噪声信号 的理性预期模型分析了资产收益。在模型中，投资者可以通过基金选择三种不同的策略：主动、被动、混合，同时引入代理人异质性，投资相关的费用被作为外生变量考虑。

### 文献观点

> 1.  @grossman1980 提出了理性预期均衡模型，在这个模型中，投资者背负了获取收益信息的成本，导致资产价格不能完全反映可利用的信息。如果价格完全反映了信息，对于收集信息的投资者将没有任何好处。**按照这个逻辑，如果更多的投资者选择被动投资，资产错误定价将非常普遍，反过来，将有更多的投资者变成信息交易者从错误定价中获取收益。**
> 2.  @liu 扩展了 @grossman1980 的模型，分析了指数投资兴起对价格发现功能的影响，表明真全价格信息含量的增加或减少取决于被动投资增长的原因和信息获取的成本结构。他们推断，被动投资外生的增加无疑会导致价格信息含量的下降。
> 3.  @gârleanu2022 通过理论模型研究了被动投资对市场有效性的影响，发现市场有效性随着信息成本下降而上升，主动基金数量越多，市场有效性越强。同样，他们认为随着被动基金成本下降，会吸引更多的被动投资者，市场有效性将下降。其关键在于当一个稳健的共同因素存在于基本面时，宏观无效将超过微观无效。
> 4.  @anadu2020 研究了被动投资者对金融市场波动的影响，向被动投资策略转变重塑了金融稳定的格局，增加了一些风险，同时也减轻了另一些风险。

### 模型构建

> **1.择时**
>
> 本文考虑了一个两期模型，在第0期进行信息获取和投资决策，而在第一期实现收益。具体来讲，在第0期，主动投资者可能获取私有信息并基于此做出投资决策，也可能没有获取任何信息，仅仅是委托基金以主动或别动方式进行管理。在第1期，投资收益将被实现。代理人的目标是调整风险，最大化他们在第1期的期望收益，风险大小取决于他们选择的投资模式。
>
> **2.资产**
>
> 该经济包含无风险资产和风险资产，无风险资产收益标准化到0，即$r_f=0$，风险资产的收益服从于正态分布，具体如下：
>
> $$
> R\sim N(\theta,\sigma^2)
> $$
>
> 其中，$\theta$和$\sigma$分别为已知外生期望收益与收益的标准差。
>
> 风险资产的供给$X$是未知的，假设其服从正态分布，具体如下：
>
> $$
> X\sim N(\bar{x},\sigma_x^2)
> $$
>
> 其中，$\bar{x}$和$\sigma_x$外生的资产供给的均值和标准差。
>
> 在这个模型中，风险资产供给相关的不确定性发挥了重要作用，它防止了私人获得信息直接反映在价格中。换句话说，如果供给是已知的，没有获得私有信息的投资者将可以从价格水平中推断出其他投资者获取的私有信号的均值。因为私人信号的均值是一个足够的统计数据，从价格中推断出他的可能性完全消除了购买私有信息的动机。通过引入风险资产供给中的噪声也阻止了私有信息 直接在价格中反映。
>
> **3.投资者**
>
> 有大量的投资者，用i表示，其中$i\in(0,1)$，每一个代理人从三种投资模式中选择一种来优化决策。
>
> （1）主动投资：以成本$C$获取关于风险资产的私有信息$S_i$，并直接投资。
>
> （2）被动投资：支付费用$f_p$，并被动投资资产——没有信息获取，期望收益或方差从资产价格$P$中推断而获得。
>
> （3）委托主动投资：支付费用$f_{MF}$，并选择委托主动投资，同时得到一些风险减少的投资收益。
>
> 重要的是，代理人被假设在投资技巧上是同质性的。这捕获了教育水平、投资经验、投资渠道等因素随着总体而变化。在模型中，它通过不同代理人接受不同信息含量的信号反映。特别的，投资者$i$可以以成本$C_i$获得信息$S_i$，其中$S_i$的分布如下：
>
> $$
> S_i\sim N(R,\phi(i)),where \ \phi(i)=\frac{\alpha}{i^\beta}
> $$
>
> 其中，$\alpha,\beta>0$,方差函数$\phi(i)$的形式选择源于他是高度灵活的，并且具有期望性质以及等效幂分布。由于该函数是单调递增的，随着投资者数量增加将获得更多富有信息的信号。即信号拥有更低的方差$\phi(i)$。它也被看着$\lim_{i \to 0}\phi(i)=\infty$,这意味着最低技能的投资者将接收到低信息的信号，将鼓励他们选择被动投资或委托主动投资。

> 一个代理人被动投资不获取私有信息，也不发生信息获取成本$C$。这个代理人观测到风险资产的价格为$P$，在这个基础上，做出风险资产购买数量的决策。在均衡时，价格将揭示了关于其他投资者私有信号的一些信息（即整个市场的知识和预期）。在这模型中的被动投资相当于股市中的投资者观察跟踪大盘的指数基金的价格，并并基于价格推断的信息决定购买的份额。在模型中，被动投资的代理人需要支付费用$f_P$，这相当于被动基金的管理费用。

> 在模型中，委托主动投资尝试着捕获主动管理基金和其他股票管理者的一些结构和效应。简单地来讲，委托主动投资将被视为通过共同基金的投资，在现实中，共同基金的管理费用为$F_{MF}$，能获得一些风险资产的信息。委托主动基金的管理费用假设比被动管理基金的管理费用要高，即$f_{MF}>f_P$。

> **在模型中，存在单一风险资产，这意味着投资者是否委托多主动投资的惟一原因是能否从较低的方差中获益。**因此，通过共同基金进行投资被建模为获得信号。与主动投资者的信号不同，被动基金投资者的方差对所有基金投资者都是相同的。这样，选择主动投资的投资者$i$以方差$V_{MF}$获得信号$S_{i,MF}$:

$$
S_{i,MF} \sim N(R,V_MF(f_{MF}))
$$

> 其中，方差却决于共同基金的管理费用，具体如下：

$$
V_{MF}(F_{MF})=\frac{\delta}{f_{MF}^\eta}+\zeta
$$

> 其中，$\delta,\eta,\zeta>0$。方差的这种结构允许捕获共同基金在收取更高费用时能够获得更精确信息的机制。另外，$\lim_{i \to 0}\phi(i)=\infty$意味着当不收管理费用时，共同基金没有能力获取任何有意义的信息。为了模型额外的灵活，参数$\zeta$控制了总体方差水平。

> 在该模型中，管理费用是外生的，在股票市场上，有许多因素影响管理费用，包括但不限于主动投资行业的外生程度，技术的变化，新的投资产品等等。

> **4.最优化问题**

> 在决定投资模型后，给定信息集$I_i$，代理人通过在第0期选择最优需求$D_i$最大化他在时期1最终财富的期望效用，即

$$
\mathop{\max}_{D_i}E[U_i(W_i^1(D_i))|I_i]
$$

> 信息集取绝于代理人选择的投资模式，具体来讲，如果代理人$i$选择被动投资，则信息集为$I_i={P}$，对于主动投资者来说，信息集为$I_i={P,S_i}$，对于委托投资来说，信息集为：$I_i={P,S_{i,MF}}$。

> 最终财富为$W_i^1=D_iR+(W_i^0-D_iP)$，这是风险资产收益（$D_iR$）和无风险资产收益（$W_i^0-D_iP$）的总和。

> 假设效用函数为指数函数，具体如下：

$$
U_i(W_i^1)=-e^{-\gamma W_i^1}
$$

> 其中，$\gamma$是风险厌恶程度。

> **定理1**

> **在代理人**$i$的信息集$I_i$条件下，给定风险资产均衡价格以及其收益$R$的后验均值和方差，代理人$i$的最优需求如下：

$$
D_i=\frac{E(R|I_i)-P}{\gamma Var(R|I_i)}
$$

### 均衡求解

> 定理1提供了每一个投资者需求函数的一般形式，但由于不同的信息集条件，具体形式不同。最优需求的推到是基于Grossman-Stiglitz步骤，先猜风险资产的价格是收益和供给的线性函数，具体如下：

$$
P=a+bR+cX
$$

> 其中，$a,b$和$c$是确定的常数。

> 如果风险资产的价格和供给确实是线性函数，被动（P）、主动（A）、委托代（MF）理投资者的最有需求分别如下：

$$
D_{i,P}=D_P=\frac{1}{\gamma}\big(\frac{\theta}{\sigma^2}+\frac{b(-a-c\tilde{x})}{c^2\sigma_x^2}-P(\frac{1}{\sigma^2}+\frac{b}{c^2\sigma_x^2}(b-1)) \big)
$$

$$
D_{i,A}=\frac{1}{\gamma}\big(\frac{\theta}{\sigma^2}+\frac{S_i}{\phi(i)}+\frac{b(-a-c\tilde{x})}{c^2\sigma_x^2}-P(\frac{1}{\sigma^2}+\frac{1}{\phi(i)}+\frac{b}{c^2\sigma_x^2}(b-1)) \big)
$$

$$
D_{MF}=\frac{1}{\gamma}\big(\frac{\theta}{\sigma^2}+\frac{S_{iMF}}{V_{MF}(f_{MF})}+\frac{b(-a-c\tilde{x})}{c^2\sigma_x^2}-P(\frac{1}{\sigma^2}+\frac{1}{V_{MF}(f_{MF})}+\frac{b}{c^2\sigma_x^2}(b-1)) \big)
$$

### 市场出清

> 风险资产的市场出清要求三类投资对风险资产的需求等于风险资产的供给。不损失一般性，假设有$i\in (0,\lambda_{MF}]$的投资者选择共同基金，有$i\in (\lambda_{MF},\lambda_{MF}+\lambda_{P}]$的投资者选择被动投资，剩余$i\in (\lambda_{MF}+\lambda_{P},1]$的投资者选择主动投资。则投资的需求等于供给的条件如下：

$$
\int_0^{\lambda_{MF}}D_{i,MF}d_i+\lambda_PD_P+\int_{\lambda_{MF}+\lambda_{P}}^1D_{i,A}di=X
$$

> 从均衡条件中可以解出均衡价格，具体如下：

$$
P=a+bR+cX
$$

> 其中，$a,b$和$c$如下：

$$
a=\big(\frac{1}{\sigma^2} +\frac{\bar{q}^2}{\gamma^2\sigma_x^2}+\bar{q}\big)^{-1}\big(\frac{\theta}{\sigma^2} +\frac{\bar{x}\bar{q}}{\gamma^2\sigma_x^2}\big)
$$

$$
b=\big(\frac{1}{\sigma^2} +\frac{\bar{q}^2}{\gamma^2\sigma_x^2}+\bar{q}\big)^{-1}\big(\frac{\bar{q}^2}{\gamma^2\sigma_x^2}+\bar{q}\big)
$$

$$
c=\big(\frac{1}{\sigma^2} +\frac{\bar{q}^2}{\gamma^2\sigma_x^2}+\bar{q}\big)^{-1}\big(\frac{\bar{q}}{\gamma\sigma_x^2}+\gamma\big)
$$

> $\bar{q}$为平均投资获得的信息准确度，具体如下：

$$
\bar{q}=\frac{\lambda_{MF}}{V_{MF}(f_MF)}+\int_{\lambda_{MF}+\lambda_{P}}^1(\phi(i))^{-1}di
$$


### 投资者比例

> 在模型中，选择不同投资模型的投资者的比例是外生的，被动投资者的比例$\lambda_P$和委托代理投资者的比例$\lambda_{MF}$是重要的，决定这两个比例的均衡条件如下：

> (1)不主动投资的代理人对于被动投资和通过共同基金投资是无差异的。该条件保证了被动投资和共同基金都有需求。通过共同基金投资成本较高，但后验方差较低。

> (2)代理人$i=\lambda_{MF}+\lambda_{P}$对于投资主动还是被动无差异。


### 研究结论

> 过去20年被动投资的迅速增长引起了金融业经济学家和分析师对这一现象潜在后果的担忧。特别是金融业，意见分歧，也是由不同群体所代表的利益所推动的。具体而言，向被动投资的转变导致主动资产管理公司的业务损失，同时通过提供ETF为银行和其他实体创造了可观的利润，尽管ETF是低成本投资。由于被动投资仍然是一个相对较新的研究领域，经济学家考虑的模型及其分析很少，我们远远没有达成共识。

> 本文有助于现有的文献，试图解决三个基本方面，具体而言，我们展示了被动投资的兴起如何影响2000年至2017年期间的整体价格水平、价格波动及其信息量。我们提供了一个理论模型，并使用数据来估计它。首先，该模型表明，资产的整体价格水平不会因为投资模式的转变而增加。这与一种流行的说法相反，即被动投资，特别是ETF，可能导致了所谓的ETF泡沫。其次，我们看到被动投资的增加可能对资产价格波动产生放大效应。由于这种波动性的上升并不植根于基本因素，它表明这种变化对金融市场的总体稳定产生了负面影响。第三，该模型表明，价格信息含量下降，这与该领域的绝大多数先前的研究是一致的。

> 我们还分离了被动和委托主动管理费的影响，以显示被动投资者的比例如何变化，如果费用继续下降。外部因素，如市场竞争力的提高和技术的进步，可能会继续对收费产生负面影响。，被动费用的下降可能导致被动投资者比例的进一步增加。共同基金费用下降的影响似乎不明确，但如果出现足够大的负面变化，也可能导致这一比例进一步上升。如果费用确实继续下降，预计价格信息含量将下降，价格波动性将进一步放大。


## the implications of passive investing for secuties market


### 摘要

> 近年来，通过指数共同基金和交易所交易基金（ETF）进行被动投资的流行程度大幅增长，取代了成本较高的主动投资风格。转向被动投资可能会在两个关键方面影响证券市场。首先，它可能会导致更高的相关性的回报和更少的证券特定的价格信息。其次，它可能会影响总投资资金流量和市场价格动态。在这种情况下，主动型共同基金在最近的压力时期表现出持续的资金流出，而被动型共同基金的资金流动则相当稳定。ETF的流动相对波动，尽管它们与基础价格的联系不如其他基金类型那么直接。


### 研究问题

> 被动管理基金提供了一个低成本分散化的投资工具，这与主动管理型基金形成了鲜明对比，主动管理型基金通过自由选择证券或在预期市场转折点时进行交易，寻求获得高于其所选基准的回报。这样做会产生交易成本，并需要对主动管理人和投资相关的信息进行补偿，这与更高的费用密切相关。


> **除了个人投资者的潜在收益和成本问题外，被动管理投资组合的快速增长也引发了关于其对证券市场可能产生的影响的争论。一个令人关切的问题是，被动投资的机械投资规则可能会导致个别证券定价的扭曲。从总体层面来看，还存在一个问题：它是否可能通过放大投资者的交易模式而加剧价格动态的不稳定。**

> 尽管被动基金增长迅速，但在已发行证券中所占比例相对较小。即便如此，现有的实证证据表明，被动基金的整个投资组合交易仍有助于单个证券价格之间的相关性。被动型基金管理其投资组合的机械方式意味着，它们对总体证券价格动态的影响将主要取决于最终投资者的行为。**最重要的是，指数共同基金与ETF对市场的影响可能不同，在最近的市场压力时期，指数共同基金的投资者相对于那些使用主动共同基金的投资者发挥了稳定影响力，而ETF的流入和流出相对波动**


### 被动投资的理论基础

> 最终投资者对投资工具的选择不仅取决于基金经理的业绩，还取决于基金经理的风格是否符合他们的偏好和风险承受能力。个人投资者在决定是否采取被动投资策略时，一般有几个考虑因素：

> 1.从理论角度来看，个人投资者采取被动投资战略的理由是基于有效市场的概念。这一理论认为，证券价格迅速纳入所有可用信息，这意味着（超额）未来收益是不可预测的。一个自然的推论是，积极投资策略产生高于市场回报的空间有限，如果有的话。由于系统性业绩优于其他公司的可能性有限，人们对管理费超过维持多样化市场投资组合所需费用的理由产生了怀疑。即使人们拒绝市场效率的概念（因此，管理人员无法随着时间的推移产生高于市场的回报），被动投资仍然可以被认为是一种最佳策略，因为超过市场基准的表现是一种“零和游戏”。由于被动投资者的平均回报率在成本之前应该等于市场回报率，因此所有主动投资者的平均回报率也必须等于市场回报率。鉴于积极的投资者正试图击败市场，其中一些投资者的任何收益都必须被其他投资者的损失所抵消。因此，扣除交易成本后，主动投资者的平均回报将低于被动投资者。

> 2.主动管理在理论上仍有很强的理由。首先，知情的主动型基金经理可以获得高于市场的回报，因为投资者群体还包括主动但不知情的投资者，他们的总投资组合表现低于市场。其次，虽然零和博弈的论点适用于恒定的市场投资组合，但在现实中，被动型基金经理必须进行交易（尽管不频繁）以管理投资者的流入和流出，因为指数本身并不是静态的。这意味着，平均而言，知情的主动投资者可以利用被动管理人可预测的交易模式，例如在预期调整指数成员资格或首次公开发行之前进行交易，从而使业绩优于基准。


## 近期主动投资增长的驱动因素

> 近年来，各种因素导致投资者越来越青睐被动基金。其中一个关键因素是被动基金的业绩记录优于主动管理基金。

> 1. 近年来，大多数主动型股票基金的表现都未能超过市场基准。此外，至少在主要市场上，表现优于基准的基金并非一直如此。

> 2. 最近低成本被动基金的流行得到了金融咨询行业结构性转变的支持。其中包括：所谓的“机器人顾问”（提供低收费自动化投资管理服务的平台）的兴起;引入信托责任要求;以及放弃基于佣金的薪酬。监管机构对费用透明度的更大关注也在一些司法管辖区发挥了作用。

## 被动投资对资产定价和证券发行的影响

> **证券价格形成的有效性**

> 被动基金的投资决策是在投资组合层面而非个别证券层面作出的。被动型基金经理和投资者自然会强调影响投资组合回报的系统性（或共同）因素，如对货币政策、通货膨胀和其他宏观经济因素的预期。相比之下，被动型投资组合经理对指数中单个证券的特质缺乏兴趣。他们不投入资源寻找和使用与评估个别证券有关的特定证券信息。实际上，他们搭上了积极投资者在这方面的努力。因此，被动投资组合份额的增加可能会减少价格中包含的信息量，并导致定价效率低下和资本配置不当。

> 被动管理的投资组合的增加也可能通过市场上整个投资组合交易的增加而影响证券的定价。被动型基金经理根据资金流入和流出情况买卖整个一篮子指数成分股。这种交易模式可导致指数成分股价格的更大联动性。它还可能放大与指数中未包括的证券之间的任何定价差异。

>  一系列股票市场的大量学术研究已经确定了证券被添加到基准指数时的联动性，价格压力和其他交易效应。当个股被纳入标准普尔500指数时，明显的效果是显而易见的：它们与指数的相关性增加，交易量跃升，买卖价差缩小（图3）。研究结果支持这样一种观点，即指数纳入效应反映了“非基本面”投资者需求冲击。特别是对于ETF，最近有证据表明，交易和套利活动有助于标准普尔500指数股票的共同运动。

> 然而，应当指出，这些影响也产生了制衡力量。在某个时候，个别证券价格的更大异常预计将增加知情分析和活跃交易的收益，从而刺激更积极的投资战略。主动和被动风格之间的最终平衡将取决于证券市场的特点，如信息成本、可获得性和整体市场效率。因此，在深度和效率已经很高的市场中，主动投资者收集信息的回报应该相对较低，而被动投资的规模回报相对较高，其他因素都是一样的。







### 参考文献
