---
title: 股票久期
author: 薛英杰
date: '2025-08-12'
slug: equity duration and predictability
categories:
  - research
tags:
  - research
bibliography: references.bib
---

### 股票久期

> 股票久期的概念来源于债券定价，债券久期是用来衡量债券价格对利率变化的敏感度， 该概念应用在股票或股票组合上就是股票久期，用来衡量公司股票（或股票指数）的价值 对利率变化的敏感度。**通过利率变化对未来现金流现值的影响来体现。**具体定义如下：

$$
Equity Duration=-\frac{1}{P_E} \frac{\partial P_E}{\partial y}
$$

> 其中，$P_E$为股票价格或公司市值，$y$为利率（通常指无风险收益率）。

> 这意味着利率上升 1%，股票价值大约会变化（久期 × 1%）。

### 经济直觉

> -   利率上升 → 未来现金流的折现更大 → 股票价值下降。

> -   现金流更多来自远期年份的公司（如成长型科技股）→ 股票久期高。

> -   现金流主要集中在近期的公司（如公用事业、成熟高分红公司）→ 股票久期低。

## Equity duration and predictability

### 摘要

> 1945年之后，预期回报开始主导股价变动，预期股息增长的空间很小。股权存续期的增加有助于解释这种变化。随着未来的支付，预期收益变化更大。此外，由于预期收益比增长率更持久，它们对长期资产更重要。我们通过三个数据集为这一解释提供了实证支持:股息条、总市场的长时间序列和股票的横截面。一个简单的随时间变化的现值模型可以在很大程度上解释1945年后预期回报的主导地位。

### 研究问题

> 基本的经济学直觉表明，预期现金流(尤其是股息)的变化，应该在股价走势中发挥重要作用。但经典现值模型的估计表明，期望收益的变动在股价走势中国发挥了主导作用，股息增长率仅发挥了次要作用。同时也出现了许多令人困惑的发现，比如，股价的走势并不是由基本面的变化驱动，而是由投资者风险偏好[@cochrane2011]或“动物精神”[@keynes1937]的变化驱动；在1945年之前股息变化发挥主要作用，之后则是期望收益其主动作用。
>
> 在当今世界，投资者在分散化投资和转移风险方面的能力比任何时候都强，这意味着预期回报的重要性要相对下降，而不是提高。因此，现有研究对股价走势的主导因素的讨论并未给出令人信服的解释，究竟什么原因使得期望收益现在对股价影响发挥主导作用。

### 研究思路

> 本文认为这些研究分歧可以使用股票久期随时间大幅增加与股息支付率下降来解释。为了抓住更好的投资机会，企业可能将更多的利润用来再投资（或将现金存放在企业账户等待投资机会），这样会将向投资者分红推迟。这样投资者会以资本增值的形式来获取回报，导致整个市场的红利价格比率下降，红利增长率上升。这写证据表明股票久期已经随时间增长，折现率对资产价格变化更为重要。
>
> 在一个简单的理论框架下，本文对以上的讨论进行建模分析，讨论了久期影响期望收益相对重要性的渠道。（1）期望收益与红利增长的相对持续性。（2）不同支付期限资产期望收益的方差差异。然后利用红利数据、市场层面的时间序列数据以及股票横截面数据，进一步检验了我们的模型。

### 股票久期影响红利支付的理论模型

> 传统测度久期的方法就是利用上市公司现金流信息来测度。但由于数据不足，本文推到了一个简单模型，证明股息支付率的逆可以捕获股票久期。
>
> 在每一期，公司会决定当期的多少利润用来投资或维持，多少支付给投资者。公司将投资到边际投资净现值为零的点，投资机会越好，投资的金额将越多。这意味着向投资者的支付转移到未来，当前的股息率下降。
>
> 本文假设存在一个只做一期投资的公司，在每一期会决定向投资者支付多少红利，通过支付比率$\pi$来捕获，多少利润用来投资。边际投资正好产生预期收益R，公司只有在有净现值为正的项目投资时才保留收益。并假设企业的生产函数如下：
>
> $$
> Y_{t+1}=A_tK_t^a
> $$
>
> 其中，$Y$是产出，$K$是资本。
>
> 我们假设下一期完全折旧，产出的资本弹性为$\alpha \in (\underline{\alpha},1)$，该下界确保公司想保留一些利润，意味着规模收益递减，投资资本有一个机会成本$R$。
>
> 公司的久期被定义为产出的增长率$G$，具体如下：
>
> $$
> G\equiv\frac{Y_{t+1}}{Y_t}=(\frac{A_{t+1}}{A_t})^{\frac{1}{1-\alpha}}
> $$
>
> 这取决于生产的增长与产出的资本弹性。这样股息率可以表示如下：
>
> $$
> \pi=\frac{D_{t+1}}{E_{t+1}}=\frac{A_tK_t^{\alpha}-K_{t+1}}{A_tK_t^\alpha-K_t}=1-\frac{\alpha}{R-\alpha}(G-1)
> $$
>
> 如果久期上升，红利支付率将下降。

### 实证方法

> 本文使用红利价格比率来预测未来收益率、红利增长率和红利价格比率。具体如下：
>
> $$
> \begin{bmatrix}ret_{t+1} \\dg_{t+1} \\dp_{t+1}\end{bmatrix}=
> \begin{bmatrix}\beta_{ret} \\beta_{dg} \\beta_{dp}\end{bmatrix}dp_t+
> \begin{bmatrix}\epsilon^{ret}_{t+1} \\\epsilon^{dg}_{t+1} \\\epsilon^{dp}_{t+1}\end{bmatrix}
> $$
>
> 使用该模型的系数，我们可以计算期望收益与红利增长率的相对重要性，具体如下：
>
> $$
> ER=\frac{\beta_{ret}}{1-\rho\beta_{dp}}\\
> EDG=\frac{\beta_{dg}}{1-\rho\beta_{dg}}
> $$
>
> 然后，我们构建了具有不同派息率的股票投资组合，以检验是否有横截面证据表明，越长的持续时间对预期回报的作用越重要。

### 文献观点

> 1.  期望回报比期望红利增长率的持续性更强[@koijen2011; @van2010predictive; @golez2014]。
> 2.  到期时间更长的资产比到期时间短的资产价格变化更大[@giglio2017]。
> 3.  在较长时间内，预期收益在好状态和坏状态之间的差异更大[@gormsen2021] 。
> 4.  对ICAPM模型(含再投资风险)进行了估计，并表明风险厌恶的时间变化会对较长期资产的预期收益产生较大的变化[@gonçalves2021]。

### 主要结论

> 1.  本文使用了Golez和Koudijs(2018)的数据，涵盖了四个世纪，从17世纪初现代市场开始到2022年底。在最初的几个世纪里，公司的派息率很高，但在1945年后显著下降。我们表明，这种下降与预期回报的重要性增加是同步的。随着股票存续期的增加，市场变得更加以增长为导向，投资者的预期回报对股价的影响比基本面的变化更重要。从1629年到1945年，预期收益解释了股息价格比35%的变化。1945年后，这一比例上升至90%。
>
> 2.  本文进一步分析1945年以来美国股市的横截面。我们根据公司的派息率将其纳入投资组合。与我们的论点一致，预期回报的相对贡献随着派息率的增加而下降。预期收益解释了低派息投资组合中100%的价格波动，而在高派息投资组合中，预期收益解释了54%的价格波动。

### 参考文献
