---
title: 关于主动投资与被动投资的优秀文章
author: 薛英杰
date: '2025-09-09'
slug: active investment and passive investmen paper
categories:
  - research
tags:
  - research
---

### 主动投资和被动投资有什么区别？

> 英国《金融时报》发布了一[系列关于ETF的文章](https://www.ft.com/etf-hub)，为了解现代被动投资提供了良好的入门指南。我们推荐John Auther的文章，他指出ETF可能营造出高流动性的假象，并鼓励过度交易。我们对ETF交易的看法与对主动策略的看法大致相同——采取长期策略。

> 爱尔兰经纪人戴维 (Davy) 提供了有关主动投资和被动投资的[简洁入门知识](https://www.davyselect.ie/binaries/content/assets/davyselect/pdfs/guide-to-active-vs-passive.pdf)，而安永 (EY) 则强调了当前和预期的 ETF 行业发展（提到了我们自己的 ETF 主管尼克·金 (Nick King)），并且特别关注主动基金和因素、主题和主动 ETF 之间日益模糊的界限。

> 瑞士信贷的迈克尔·莫布辛（Michael Mauboussin）的文章值得一读，他撰写了一篇*关于被动投资和主动管理如何互动的文章。他认为，从主动投资转向被动投资的投资者比那些继续投资的投资者了解的信息更少，这使得继续投资的投资者在游戏中处于更艰难的地位——就像那些实力较弱的玩家离开牌桌一样。我们反驳说，也存在相反的效应：随着越来越多的投资者放弃利用低效率，剩下的主动投资者就会获得更多——就像牌桌上不断增加的奖金一样。

### 主动还是被动，哪个更好？

> 你可能已经猜到了，这个问题没有明确的答案。但双方都有很多重要的观点。

> 沃伦·巴菲特，一位通过主动投资积累财富的人，在他2016年[致投资者的信](https://www.berkshirehathaway.com/letters/2016ltr.pdf)中，谈到了他十年来押注股市将跑赢对冲基金行业。巴菲特当然赢了，但这不过是一个简单的统计数据。总体而言，鉴于投资是一场零和博弈，并且需要支付费用，主动投资行业的表现必然逊于指数。同样，被动投资也必然因为费用而跑输。但这并不意味着个人主动投资者无法持续跑赢——看看巴菲特的记录就知道了——而指数基金，顾名思义，永远无法超越基准。

> 指数投资领域的一股强大力量贝莱德 (Blackrock) 积极地为自己的[观点辩护](https://www.blackrock.com/corporate/literature/whitepaper/viewpoint-index-investing-supports-vibrant-capital-markets-oct-2017.pdf)。他们表示，指数投资规模相对较小，影响力不大，仅占全球股票的不到 20%，投资流向是由整体资产配置决策驱动的，而不是某些产品或投资风格的吸引力。我们同意这一点。指数投资的市场份额取决于你关注的市场。例如，美国股票的 ETF 和被动资产管理份额约为 40%。1 关于第二点，大多数投资者确实是根据整体资产配置观点做出决策的，但也存在一些从众行为——例如，2018 年 2 月，大量做空 VIX 交易导致两只跟踪波动率指数的 ETF 爆仓。

> 联博分析师一直是主动投资行业的中坚力量。他们的论文[《通往奴役的寂静之路》](https://www.bloomberg.com/news/articles/2016-08-23/bernstein-passive-investing-is-worse-for-society-than-marxism)* 曾引发小规模的争议，该论文指出被动投资比马克思主义更糟糕，因为它剥夺了市场的资本配置功能。我们认为这种说法略显夸张——在一个健康的市场中，两种投资方式并存是可行的，就像我们目前所做的那样。一个只由被动基金组成的市场会对经济产生负面影响，就像一个只由短期交易者组成的市场一样，但目前尚无任何一种情况发生的可预见风险。重要的是保持平衡。

> 查尔斯·埃利斯 (Charles Ellis) 于 1995 年写下了《失败者的游戏》(The Loser's Game)*，但如今听起来依然耳熟能详。他将投资比作一场网球比赛。在职业网球比赛中，比赛的胜负取决于击球的精准度。但在业余网球比赛中，比赛的输赢取决于失误——失误少的一方获胜。埃利斯认为，投资就像 60 年代的职业网球，当时技术娴熟的投资者可以取得优异的成绩，但由于“聪明”资金（即由专业投资者管理的资金中更大比例的资金）的涌入，投资逐渐变成了一场业余游戏，投资者必须避开落下的飞刀才能取得优异的成绩。随着被动投资的兴起，我们不禁要问，投资是否会慢慢回归到赢家的游戏？

### 利益相关方该如何应对主动与被动的争论？

> 投资咨询公司 Novus[建议](https://cdn2.hubspot.net/hubfs/305037/Seven%20Habits%20of%20Highly%20Successful%20Portfolio%20Managers.pdf?t=1482420582942&submissionGuid=5db5703c-09ee-4fa6-a52d-1a9fdfed09c8)，主动型投资组合经理可以养成七个习惯，帮助他们在不断变化的投资环境中取得成功——如果真的这么简单就好了。NIRI（美国国家投资者关系协会）为寻求吸引买方投资者关注的公司提供了一些非常好的建议。NIRI 建议加强与高管的沟通和联系——我们完全赞同这一点。

> 高盛发表了一篇引人入胜的论文*，探讨公司董事如何应对日益壮大的被动股东群体。该论文指出，近期主动型个股投资的下降削弱了公司基本面表现与股价之间的联系。这意味着董事会需要妥善协调管理层激励计划，以确保公司业绩。

### 关于该主题的学术工作

> 被动投资的根源始于哈里·马科维茨（Harry Markowitz）的[《投资组合选择》](https://www.math.hkust.edu.hk/~maykwok/courses/ma362/07F/markowitz_JF.pdf)（Portfolio Selection），它为指数投资和被动投资的发展打开了大门。马科维茨提出了通过分散投资在给定风险水平下实现收益最大化的理念。1964年，比尔·夏普（Bill Sharpe）创建了[资本资产定价模型](http://efinance.org.cn/cn/fm/Capital%20Asset%20Prices%20A%20Theory%20of%20Market%20Equilibrium%20under%20Conditions%20of%20Risk.pdf)（ CAM），并定义了我们今天所熟知的阿尔法（Alpha）和贝塔（Beta） 。尤金·法玛（Eugene Fama）于1970年出版了[《有效资本市场》](http://efinance.org.cn/cn/fm/Efficient%20Capital%20Markets%20A%20Review%20of%20Theory%20and%20Empirical%20Work.pdf)（Efficient Capital Markets），宣称市场是完全有效的，因此不可能战胜市场，从而完善了被动投资理论的基础。

> 正是市场有效性这一结论，才是学术界积极倡导者和消极倡导者争论的焦点。林恩·斯托特（Lynn Stout）从有效资本市场[假说](https://ssrn.com/abstract=523747)的构建基础入手，批判其前提（有效市场绝非如此）；罗伯特·席勒（Robert Shiller）则[探究了](https://ssrn.com/abstract=275515)表明市场非理性的心理偏见；理查德·塞勒（Richard Thaler）则[揭示了]( https://ssrn.com/abstract=327880)摩擦和偏见对市场的影响。最后，沃伦·巴菲特*列举了一些使用类似策略持续跑赢市场的投资者，他们被预先认定为优秀投资者。

> 尤金·法玛和理查德·塞勒都是诺贝尔奖获得者，他们在芝加哥大学商学院的走廊对面坐着，就市场是否有效展开了一场坦诚而有趣的视频辩论*。

> 我们认为，市场在很大程度上是有效的（在大多数公开市场，大多数时候都是如此），因此被动型和智能贝塔策略能够以经济高效的方式带来市场回报。然而，市场效率低下的情况也时有发生，例如长期来看、流动性较低的市场、围绕公司事件和技术驱动因素，以及基于行为偏差的情况。主动型基金经理可以持续利用这些情况。对投资者而言，重要的是他们的被动型基金能够忠实且低成本地复制指数，并且他们的主动型基金经理能够运用真正主动的策略在长期内创造相应的价值。这篇文章很好地解释了[主动份额比率](http://dx.doi.org/10.2139/ssrn.891719)如何帮助投资者衡量主动敞口的规模。

### 有关该主题的书籍

> [《证券分析》](https://www.amazon.co.uk/Security-Analysis-Foreword-Buffett-Editions/dp/0071592539) ——首次出版于20世纪30年代——是主动管理爱好者的终极读物。它构建了一个框架，帮助投资者在股票和债券市场上获得卓越表现，从而制定出针对特定证券的基本策略。[《不当行为》](https://www.amazon.co.uk/Misbehaving-Behavioural-Economics-Richard-Thaler/dp/0241951224/ref=sr_1_1?s=books&ie=UTF8&qid=1525969399&sr=1-1&keywords=misbehaving)则是理查德·塞勒的一部职业生涯传记，讲述了他如何将心理学的经验应用于投资领域，从而开启了行为金融学的学科。

> [《漫步华尔街》](https://www.amazon.com/Random-Walk-down-Wall-Street/dp/0393352242/ref=sr_1_1?s=books&ie=UTF8&qid=1525968272&sr=1-1&keywords=a+random+walk+down+wall+street)是一本通俗易懂的著作，对有效市场理论进行了辩护，并针对智能贝塔基金及其衍生品进行了更新。先锋集团创始人约翰·博格在其著作《共同基金常识》中，阐述了如何从被动视角思考共同基金的投资。

### 轻松一点——电影和小说

> [《美国丽人》](https://www.imdb.com/title/tt0169547/) *是对美国中产阶级的辛辣讽刺。我们（勉强地）通过主人公，将其与主动与被动之争联系起来。主人公一直以来都过着被动的生活，直到他转向更加主动的生活方式。这两种解读方式都有各自的缺陷。

> [《伊索寓言》](https://www.amazon.co.uk/Orchard-Aesops-Fables-Book/dp/1843622718)是一本古老的寓言集，其中最著名的或许是《龟兔赛跑》。当然，乌龟最终获胜，但这个故事的寓意却引人入胜——在某些版本中，它讲述的是乌龟的毅力，而在另一些版本中，它讲述的是兔子愚蠢的过度自信。无论投资者遵循何种策略，坚持不懈和避免过度自信都是重要的特质。