---
title: 家庭金融相关文献阅读
author: 薛英杰
date: '2023-03-08'
slug: family finance
categories:
  - cn
tags:
  - diary
bibliography: [one.bib]
link-citations: TRUE
bilbio-style: "biomed-central.csl"
---

## Let the rich be flooded:The distribution of financial aid and disstress after hurricane harvey

### 摘要

> 在洪灾区外，居民必须决定投保还是依靠灾难救助来管理洪灾风险。我们使用2017年8月袭击休斯顿的哈维飓风作为拟随机洪水，来理解洪水损失对获得保险和信贷家庭的影响。在洪灾区外，与非洪水区相比，信贷约束的家庭破产数量增加了20%，严重拖延债务的家庭比率增加了13%. 在洪水区组内，一方面，处理效应不显著意味着洪水保险抵消了信贷配给的洪水影响。另一方面，灾难援助并没有抵消初始不平等对灾后信贷结果的作用。更惊讶的是，我们发现SBA灾难贷款和FEMA拨款在配给上都是倒退的。我们的结果强调均值掩盖了灾难后重要异质性，这挑战了现有的关于联邦灾难计划如何有效减轻自然灾害的财政负担的叙述。

### 研究问题

> 气候变化已经带来了更加频繁的洪灾，并增加了实际处于灾难发生相关损失风险人们的不确定性。为了管理洪灾区外损失的尾部概率，家庭必须面临一个选择：购买保险或依赖灾难援助。那么，洪灾损失对家庭获得保险和灾难救助的方式选择有什么影响？

### 研究思路

> 本文研究了洪水对家庭消费破产和拖欠率的影响，这些家庭或多或少获得了联邦灾难贷款并生活在强制或非强制洪灾保险的区域。尽管可以预见，巨大的负面财富冲击可能会导致负面的信贷结果，但在洪水保险和联邦救灾援助的背景下，这些结果的规模和在家庭之间的分配都不是很明显------两者都是为了缓和冲击。而且在哈维之后，就业或工资几乎没有变化，信贷供应也没有受到限制，无论是整体还是根据洪水风险。哈维飓风后的这些独特特征使我们能够将透明的、处理强度的差分设计应用于消费者信贷数据，比较居住在发生洪水的街区的休斯顿居民与居住在没有经历洪水的街区的休斯顿居民的信贷结果。
>
> 为了理解保险的作用，我们利用休斯顿百年一遇洪灾去外的大多数遭受洪水淹没的建筑物和财产在洪灾区内要求购买洪水保险的抵押贷款作为研究对象，评估了洪灾保险普遍存在的洪水效应的影响。

### 相关文献

> 1、@Garllagher 研究了受卡特里娜飓风影响的个人的信贷和债务结果，发现受灾最严重的居民的整体拖欠率仅出现温和短暂上升。
>
> 2、Begley 发现他们所谓的"价格歧视需求"的代理指标与 SBA 贷款拒绝率随着时间的推移和许多灾难之间存在一致的关系。因此，信贷摩擦在哈维之后不同类型家庭的财务复苏中发挥作用。

### 研究结论

> 1、平均来说，到2019年第四季度，休斯顿遭受洪灾家庭的破产率增加了0.7%，更重要的是，这种处理效应大多数出现在洪灾区外，而且居住在这儿家庭按照其偿还能力不能获得SBA贷款。
>
> 2、与洪水保险降低灾后信贷依赖的想法一致，我们发现在洪灾区内部并没有显著的处理效应，也不会随偿还能力而变化。这意味着洪水保险有助于减轻信贷在洪灾中分配的负向影响。
>
> 3、 考虑到家庭之间先前存在的财产不平等情况，尽管洪水过后的信贷结果可能会出现某种程度的异质性，但人们也可能期望联邦救灾援助能够减少不平等的影响。我们研究发现，低偿还能力的家庭在获得SBA贷款上存在障碍，具体来讲，当有伤害登记的家庭居住在大部分低偿还能力的居民区时，他们不能获得SBA贷款的可能性为58%。
>
> 4、由于FEMA并没有将他的援助于信用得分的因素联系起来，FEMA援助授予中类似的不平等让人惊讶。因此，FEMA IHP无法弥补 SBA 贷款留下的资金差距。在低偿付能力街区，已确认损坏的房主获得 FEMA IHP拨款的可能性降低 1.5%--3.4%，并且在获得 FEMA 拨款的情况下，他们获得的援助减少了 1,363 美元。
>
> 5、之所以确认受损的家庭难以获得FEMA IHP，原因在于复杂的审批程序和申请材料要求，这使得弱势群体难以获得帮助。

## [Women's use of family planning services: An experiment on the husband's involvement](https://doi.org/10.1016/j.jdeveco.2022.102915)

### 摘要

> 尽管低收入国家计划生育服务 (FPS) 的可用性有所提高，但其使用率仍然很低，尤其是在撒哈拉以南非洲的农村地区。为了调查这在多大程度上可以用丈夫参与决策过程来解释，我们在坦桑尼亚农村进行了一项实验，夫妻在两种支付方式之间进行选择，其中一种支付方式是以参加健康中心的计划生育会议为条件。通过实验改变丈夫的参与，我们发现在涉及丈夫的治疗中更有可能选择 FPS。探索潜在的机制，我们表明这是由妻子（错误地）认为丈夫不赞成避孕药具的夫妇驱动的。我们还发现，丈夫的参与增加了妻子参加计划生育会议的期望。这两项研究结果都表明，配偶之间发起沟通可以减少需求限制。

### 研究问题

> 计划生育 (FP) 旨在帮助夫妇拥有他们想要的孩子数量，并控制生育间隔和时间。这对低收入和中等收入国家的夫妇及其子女有重要好处,虽然已经在低收入国家提供计划生育服务方面做出了许多努力，但女性对计划生育的未满足需求仍然很高，尤其在撒哈拉以南非洲大多数国家的农村地区。那么，什么因素限制了其需求侧的变化，丈夫的参与是否以及为何会影响一对夫妇接受当地健康中心提供的 FPS 的计划。。

### 研究思路

> 采用实验设计的思路，夫妻被随机地分配到参与计划生育服务的实验中，设计了只有妻子、只有丈夫或二人一起决策。比较不同决定的结果来分析丈夫参与对夫妻接受计划生育服务的影响。

### 相关文献

> 1.  @ashraf2014household 发现让丈夫参与会降低当地私人诊所的避孕药具使用率。
> 2.  因为男性想要更多的孩子并且拥有更高的议价能力，绕过丈夫可以增加女性对避孕药具的采用[@doepke2018women]。
> 3.  丈夫参与对计划生育有正向作用，由于更多计划生育相关的信息、男性态度的改变以及更好的夫妻沟通[@mccarthy2019intimate]。

### 研究结论

> 本文研究发现丈夫参与增加了选择计划生育服务的可能性，并讨论了三种不同的机制来解释这个结果：
>
> 1.  我们没有发现丈夫比妻子更喜欢 FPS 的证据。
>
> 2.  丈夫参与的正向作用是由于认为丈夫不赞成夫妇使用避孕药具的妻子造成，表明关于配偶偏好的信息是不完整的，这使得丈夫参与的影响取决于女性对其丈夫偏好的看法。
>
> 3.  当丈夫不参与决策时，妻子不太确定参加 FP 会议的计划是否会成功执行，当她单独做出决定时，这会降低他出席预期价值，从而降低其吸引力。

## [Employee output response to stock market wealth shocks](https://doi.org/10.1016/j.jfineco.2021.11.005)

### 摘要

> 本文使用个体层面的数据把股票投资与工作绩效连接起来，研究了股市财富的变化如何影响工人的产出。研究结果表明，股票市场投资的月收入增加10%，投资者下个月工作产出减少3.8%。这种负产出效应不是由当前的经济状况驱动，也无法用投资者的流动性需求来解释。与参考依赖解释一致，反应是短暂的，当总收入达到参考收入时，效果更强。总的来说，我们的研究结果突出了一个新的渠道，通过劳动力供给传递股市波动。

### 研究思路

> 这篇文章在个体层面研究了股票市场财富变动对劳动供给的影响。家庭消费包括市场商品和闲暇，在股票市场财富增加后，家庭会通过选择提供更少的劳动给来享受更多的闲暇。因此，解释休闲效应不仅可以更全面地了解家庭对股票市场财富效应的反应，而且对劳动力市场有重要意义。

> 参照依赖理论认为，当个人拥有短期心理账户时，当他们的收入达到一个参照点时，他们会在短期内减少劳动供给。本文主要研究了以下几个问题：

> 1.股票财富变化对劳动力供给的影响？
> 2.  股票财富变化对劳动力的影响是否是宏观经济驱动的结果。
> 3.  股票财富对劳动力供给影响的机制是什么？

### 研究意义

股票持有构成了大部分家庭金融资产，股票市场的波动对家庭财富积累有很大影响。家庭是连接实体经济和股票市场的重要渠道，股票财富的变化直接影响总税收，间接地影响了家庭决策。

### 文献思路

> 1.  股票市场的波动对家庭财务有显著的影响[@poterba2000stock]。
> 2.  随着时间的推移，个人会调整其劳动力供给，以应对收入冲击，从而产生持续的反应[@imbens2001estimating; @cesarini2017effect]。
> 3.  个人有一个短期心理账户，当他们的收入达到参考点时，他们会在短期内显著减少劳动力供给[@camerer1997labor; @farber2008reference; @agarwal2015composition]。
> 4.  本地居民的需求亦可能由保险产品（具储蓄功能）转向直接投资股票市场[@previtero2014stock]。

### 研究结论

> 本文提供了工人产出对股市财富变化的微观证据。将个人层面的员工绩效数据与股票投资信息联系起来，我们发现股票投资收益对员工随后的销售佣金有显著的负向影响。具体而言，每月股票投资收益增加10%，与随后一个月保险销售佣金减少3.8%相关。我们提供了一系列证据来支持劳动力供给反应的因果解释;股票投资回报与后续销售佣金之间的关系不太可能由遗漏的变量驱动，包括共同的宏观或当地经济因素或个人特定的流动性需求。股票投资回报率与后续销售佣金之间的负相关关系是短暂的：只有最后一个月的股票投资回报对当月销售佣金表现出统计上和经济上的显著影响。这些发现与参照依赖理论相一致：劳动者有一个短期心理账户，在达到参考收入时选择享受更多的闲暇，减少劳动力供给。总的来说，我们的研究结果突出了一个新的渠道，通过劳动力供给传递股市波动到真实的经济。

### 参考文献
