---
title: 共同所有权、持股网络影响上市公司经营的相关文献
author: 薛英杰
date: '2022-12-01'
slug: ownership network and firm mangement
categories:
  - research
tags:
  - research
bibliography: [one.bib]
link-citations: TRUE
bilbio-style: "biomed-central.csl"
---

## [共同机构所有权与企业盈余管理](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2021&filename=GGYY202106010&uniplatform=NZKPT&v=O_1bdOGYPcq6OqeXCks02HWCsOYnb5kE-LAFQzuPgU_OYZ3fvZxKnEmJAKZeS0BH)

### 摘要

> 随着资本市场中共同机构所有权现象越来越普遍，学术界对共同机构所有权影响微观企业 行为的探讨逐渐深入。在近年来盈余操纵事件愈演愈烈的背景下，本文实证检验了共同机构 所有权对企业盈余管理的协同治理效应和合谋舞弊效应。具体而言，本文基于2007---2019 年中国上市公司数据，考察共同机构所有权对企业盈余管理的影响。 研究发现： 共同机构 所有权发挥了协同治理效应， 改善了上市公司盈余信息质量。 采用 Heckman 二阶段回归、 工具变量法、倾向得分匹配（PSM）等方法检验后结论依然成立。同行业势力和行业内竞争 加强了机构协同效应，退出威胁和规模效应使得共同机构所有权的监督治理更加有效；具体 途径探寻发现，共同机构所有权的协同和治理通过委派管理层实现。共同机构所有权的协同 治理效应在经济增速较快、国有企业以及有长期共同机构投 资者的样本中更为明显，同时 发现共同机构所有权的协同治理得到了权威机构认可并降低了审计收费。本文的研究为共同 机构所有权协同治理效应提供了新的证据，拓展了机构投资者信息网络的研究，也为监管部 门制定符合中国现实情境的监管措施提供了参考。

### 研究问题

> 共同所有权是指同一机构投资者共同持有多家企业股份。共同机构所有权为上市公司间信 息交流和资源共享提供了便利，但也可能导致共同持股上市公司合谋舞弊，**在中国现实的情 景下，特别在当前中国的机构投资者并不活跃、主要以散户为主的背景下，共同机构所有权 对其共同持股的企业会发挥什么效应，其影响机制如何？**

### 共同机构所有权拥

> 1、整合效应。指共同机构所有权在组合价值最大化的投资目标驱使下，整合和协调组 合 内同行业企业行动的行为。

> 2、行业枢纽。指共同机构所有权在同行业传递信息、积累经验、学习决策中拥有更丰富 的行业经验和信息资源。

> 3、规模经济。指同行业企业间相似特征降低了共同机构所 有权的信息搜寻和处理成本， 由此形成的信息规模经济。

### 相关文献

> 1、共同机构所有权通过发挥整合效应，提高了上市公司市场份额和专利申请数 [@gao2019power; @he2017product]，并可以降低融资成本 、减少并购交易成本，以及提升并购绩效[@brooks2018institutional; @chen2018institutional]。

> 2、因行业枢纽作用，有共同机构所有权 的上市公司具有更好的治理效果 [@kang2018institutional]， 使得共同机构投资者能够更好履行监督职 能，在股东大会中对管理层提案持否定意见[@he2019internalizing]。

> 3、规模经济效应提高了监督效率，使 得 共 同 机 构 所 有 权 增 强 了 企 业 披 露 意 愿 [@park2019disclosure]、减 少 了 盈 余 管 理 [@ramalingegowda2021common]。
>
> 4、共同机构所有权追求组合价值最大化目标，会促使同 行业企业串联合谋，提高同行业上市公司在产品市场上的定价能力[@azar2022ultimate; @azar2018anticompetitive]。
>
> 5、为避免 在激烈的同行业竞争中被淘汰， 企业会在财务报告过程中运用构造交易等方式来影响竞争对手对 企业生产经营活动的理解[@healy1999review]，从而隐藏自身真实会计信息[@he2017product]，进而达到扭曲同行投资决策的目的[@ramalingegowda2021common]。
>
> 6、企业出于行业竞争动机进行的 盈余管理扭曲了同行业企业的投资决策[@beatty2013spillover]，而出于追逐私利动机进行的盈余管理 损害了企业自身价值并增加股东成本[@healy1999review]。
>
> 7、企业披露高质量信息将会对 同行业其他企业资本成本产生溢出效应[@shroff2017does]。 相反，如果企业通过盈余管理披露低 质量信息，将会扭曲同行业其他企业的投资决策，降低同行业公司价值。
>
> 8、共同机构所有 权能够通过信息共享产生规模效应[@kacperczyk2005industry]，由此产生更有效的监督[@kang2018institutional]。
>
> 9、共同机构投资者拥有全行 业经验的优势，具有更大的话语权[@edmans2019governance]，增加了其对管理层提交股东大会提案中 投反对票的可能[@he2019internalizing]，从而提升财务报告质量[@park2019disclosure]。
>
> 10、上市公司的行为在一定程度上会受到宏观经济周期性波动的影响，当经济发展较快时，上市公 司迫于市场竞争压力，具有操纵盈余质量的动机[@maffett2012financial]。

### 研究结论

> 本文的研究支持协同治理效应， 发现共同机构所有权拥有的整合效 应、行业枢纽和规模经济等特征有助于内化盈余管理对同行公司的负外部性，提高了机构投资者的 监督能力和监督效率。具体结论如下：
>
> ①资本市场中普遍存在的共同机构所有权能够减少企业盈余管理， 发挥了机构协同效应和监督治理效 应，在资本市场中扮演治理角色。
>
> ②机制检验表明，同行业势力和行业内竞争加强了机构协 同效应，退出威胁和规模效应使得共同机构所有权的监督治理更加有效，探寻具体途径发现共同机 构所有权的协同和治理效应通过委派管理层实现。
>
> ③共同机构所有权的协同治理效应在经济增速 较快、国有企业以及有长期共同机构投资者的样本中更为明显，与此同时，发现共同机构所有权对 盈余管理的协同治理得到了权威机构认可并减少了审计收费。

## [连锁股东与企业投资效率：治理协同还是 竞争合谋](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2020&filename=GGYY202002009&uniplatform=NZKPT&v=iD_WqMyZ0GffH0bC-xgs5V3AnX1O8QbgsAlsy_31PbwvE0Ls8QkqvYPsYldrw-3f)

### 摘要

> 企业间通过连锁股东形成的经济关联在资本市场中尤为常见，但学术界关于 连锁股东对企业发展的影响仍然存在"治理协同"和"竞争合谋"的意见分歧。 本文以企业 的投资效率为研究视角，考察连锁股东对于企业行为的影响。 研究发现：①在企业的投资 活动中，连锁股东的影响主要体现为"竞争合谋"，并导致同行业企业出现投资不足；②行 业集中度和地区市场分割加强了连锁股东的影响， 而中国对外反倾销事件带来的市场机 遇弱化了这一作用，说明取得合谋收益是连锁股东干预企业投资的根本原因；③向企业委 派董事以及更少实施股权激励计划是两条潜在的作用渠道；④在非国有企业中，连锁股东 对投资不足的影响更为明显，同时连锁股东引发的合谋行为减少了企业的固定资产、无形 资产与并购投资，并降低了企业的市场价值。 本文不仅丰富了连锁股东这一新兴学术前沿 的学术认知， 也为理解中国当前市场中企业的低效率投资活动提供了来自竞争合谋视角 的新证据，对于决策部门针对性地制定促进企业投资、提高市场资源配置效率的政策方案 具有很好的参考价值。

### 研究问题

> 同时持有多家企业股权的股东即为连锁股东[@he2019internalizing]，连锁股东在为企业间的信息与资源流动提供便利的同时，也为企业间形成利 益集团提供了一条隐蔽途径，进而影响市场正常的运行秩序。企业的投资行为是创造股东财富并促进经济增长的重要一环， 如何提高投资环节的资源配置 效率一直是学术界和实务界共同关注的重要话题。一方面，从公司治理的视角看，连锁股东为同行业企业间共享专业信息、管理经验等提供了低成本的传递渠道，这将有 助于提高企业的投资效率，即存在协同效应；另一方面，连锁股东的利润最大化目标也内生地使其 具有游说同行业内的企业进行合谋的经济激励，使得同行业的企业之间竞争程度下降，进而抑制企 业的投资活动，导致企业出现投资不足。那么，连锁股东到底通过哪种渠道影响企业的投资效率？

### 相关文献

> 1、对于同时持有多家企业股份的连锁股东而言，其经济目标是最大化投资组合的价值 ，而不是追求单个企业的高额回报[@hart1979shareholder]，由此激发 了连锁股东推动企业间合谋的经济动机[@hansen1996externalities]。
>
> 2、与交易对手拥有连锁股东能够有效缓解信息不对称，从而 有利于企业维系更加稳定的供应链关系、降低融资成本、提高并 购绩效[@brooks2018institutional]（。
>
> 3、连锁股东长期参与多家同行业企业的经营，因而相比于其他投资者，其在获取 行业发展机会相关的信息方面具有明显的优势[@he2019internalizing]。
>
> 4、积累了丰富治理经验的连锁股东还能够对管理者的经营决策实施更加有效的监督[@brooks2018institutional; @kang2018institutional]，进而帮助改善企业的投资效率。
>
> 5、对于连锁股东来说，促使其 投资组合中的同行业企业集体行动， 减少竞争和冲突， 无疑是最大化其投资价值的有效手段之一 [@hansen1996externalities]。
>
> 6、在一个竞争程度较低的市场中，企业在投资过程中更可能安于现状，缺少 开展投资活动的激励[@akdougu2008investment]。

### 研究结论

> 企业间通过连锁股东形成经济关联在资本市场中尤为常见， 目前学术界关于连锁股东对于企 业发展的影响尚未形成一致的认知，主要存在"竞争合谋"和"治理协同"两种不同观点，本文考察连锁股东对于同行业企业的投资效率的影 响，结果发现，连锁股东并未提高企业的投资效率，反而导致企业出现投资不足，支持了"竞争合谋"这一既有观点。 机制分析显示，当企业所在行业集中度越高，或者地区的市场分割程度更高时，连锁 股东越有动机促成同行业企业间的市场合谋， 并且当市场因中国对外反倾销而出现新的投资机会 时，连锁股东对企业投资的抑制作用遭到削弱。 渠道分析显示，连锁股东一般通过委派董事、减少对 高管的激励等治理途径对企业的投资决策施加影响。 在扩展性讨论中，本文发现连锁股东的影响主 要存在于非国有企业之中， 对于公司治理受政府影响、 承担较多政策性任务的国有企业的影响较 小。 最后，经济后果的检验显示，"合谋"减少了企业的固定资产、无形资产与并购投资，不利于企业 价值的提升。

## 

## [董事网络关系、信息桥与投资趋同](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2017&filename=LKGP201703015&uniplatform=NZKPT&v=XAA8JIrIuWArHmuuOk2l9jU-nNEhAibf9ettUZcsooWnErOXEXc3Sf5O3uxdntIj)

### 摘要

> 与以往社会网络研究大都基于公司个体视角不 同，本文检验社会网络的公司间效应。结合董事直接连 锁关系和间接连锁关系，利用对偶模型将所有公司进行 两两配对，本文检验了董事连锁网络对公司间投资趋同的 影响。结果发现，如果两个公司之间存在董事连锁网络 关系， 公司间的投资 水平 和 投资变化 都更 加 趋同， 而且 该趋同效应随着董事连锁网络的强度增加而加强 ；此外， 公司的信息环境越差，对董事连锁网络关系这一非正式 信息传递渠道的需求就越高，董事连锁网络关系对公司 间投资趋同的作用越明显 ；进一步看， 当两个公司处于同 一行业时，董事连锁网络关系对公司间投资趋同的作用越 明显 ；非独立董事连锁网络关系对公司间投资趋同的作用 强于独立董事连锁网络关系。为控制潜在的内生性研究， 本文还以董事死亡的外生事 件 作为自然实验 进行了双重差 分检验。结果显示，公司间的董事连锁网络成为政策制 定信息的非正式获取渠道和重要信息桥梁，为"社会网 络和公司财务"交叉研究提供了进一步的证据。

### 研究问题

> 董事网络是公司常见的社会网络之 一，中国上市公司的董事兼任现象在全球资本市场 都十分突出，据我们统计，中国上市公司 兼任现象在 2003-2012 年的 10 年间平均比例为 83%， 比美国高出 8%。更重要的是，2012 年度这一比例达到 90%，远远超过美国等主要资本市场，说明在中国资本市场研究董事的网络关系具有其独特性和迫切性。那么，董事之间构建 的社会网络关系渠道是否会成为公司决策的信息传递桥梁？

### 研究相关文献

> 1、[@leary2014peer] 发 现，公司融资政策显著受到同行业其他公司的影响，存 在显著的"同群效应"。
>
> 2、[@parsons2018geography]发现，公司的财务违规行为也存在着地域"同群效应"。
>
> 3、[@rogers2014diffusion]指出，信息传递是指通过社会系统里的某些 渠道实现成员之间沟通的过程，而在信息传递的过程 中，这些沟通渠道既可能促进信息传递也可能妨碍信息 传递。
>
> 4、[@barnea2009director] 认 为 ，公 司董事在做决策时会将他们所观察到的其他公司的类似 情况作为参照系。
>
> 5、[@larcker2006director]曾用任意两个董 事之间是否存在间接关系及此关系远近来衡量间接关 联关系。

### 研究结论

> 本文在分析董事连锁网络关系对信息 传递的可能性和机理的基础上，研究董事连锁网络关系 对公司间投资趋同的影响。本文认为，董事连锁网络和 公司间政策趋同的作用机理如下 ：董事做决策的时候会 将他们所观察到所有公司的信息作为参照系，将其在各 个公司的所接触信息和事项转化为自身的经验，进而影 响其所在公司的各类决策，促进公司间政策的趋同。实 证结果发现，如果两个公司之间存在董事连锁网络关系， 两个公司可以通过董事连锁网络关系进行与投资相关的 信息传递，促进公司间投资的趋同。公司正式的信息传 递渠道越好，对董事连锁网络关系这一非正式信息传递 渠道的需求降低，董事连锁网络关系对公司间投资趋同 的影响能力越弱 ；正式信息传递渠道越差，对董事连锁 网络关系这一非正式信息传递渠道的需求越高，董事连 锁网络关系对公司间投资趋同的影响能力越强，公司董 事连锁网络关系这一非正式信息传递渠道与分析师等正 式信息传递渠道呈现的是替代的关系而非互补的关系。

# [Product Market Competition in a World of Cross-Ownership: Evidence from Institutional Blockholdings](https://doi.org/10.1093/rfs/hhx028)

### 摘要

> 我们分析了相同行业公司的机构交叉持股对产品市场业绩和行为的影响，结果表明交叉持股公司经历了显著的市场份额增长，并基于金融机构合并的拟自然实验通过双重差分法检验了该因果关系。同时，我们发现机构交叉持股有助于明确的产品市场合作形式，并提高创新效率和运营盈利能力。总之，我们的证据表明机构投资者交叉持股通过产品市场协调提供策略利益。

### 研究问题

> 相同行业的机构交叉持股不在能够捕获公司间的战略交互，越来越多的研究表明大股东通过交叉持股对公司决策和产品市场战略发挥作用，但他们多数通过同行业公司研究了大股东直接交叉持股，很少关注到大股东间接持股对公司决策和产品市场运营的影响。因此，本文研究了机构交叉持股对产品市场业绩和行为有何影响？

### 相关文献

> 1、机构交叉持股最重要的益处在于信息生产的规模经济[@kacperczyk2005industry]。
>
> 2、现存的产业组织理论表明竞争公司之间通过股权持有的交叉持有降低了竞争，导致产品价格上升[@gilo2006partial]。
>
> 3、交叉持股安排在产品市场关系中提供了战略收益[@allen2000corporate; @fee2006corporate]，导致持股者结成战略联盟[@parker1997collusive]。
>
> 4、@harford2011institutional 表明交叉持股与目标收购公司盈利正相关，但并没有发现交叉持股显著地影响了投标收益。
>
> 5、@becht2016does 发现交叉持股太小以至于对投票结果没有影响。
>
> 6、交叉控股公司也可能实现更大的市场份额增长，因为它们可以共享技术诀窍并协调研发工作以降低生产成本、提高产品质量并提高创新效率[@grossman1980stockholder]。

### 研究结论

> 在本文中,我们分析了机构交叉持股对产品市场业绩和行为的影响。我们发现交叉持股公司的市场份额增长显著高于非交叉持股公司。我们基于金融机构合并的拟自然实验建立了因果关系。此外，我们探索并讨论了由交叉所有制促进的几种产品市场协作形式：明确的协作（以行业内合资企业、战略联盟或行业内收购的形式）以及创新生产力和营业利润率的提高可能反映隐含的协作活动。总的来说，我们的证据表明，机构股东的交叉所有权通过促进产品市场协作提供战略利益。通过建立交叉所有权与产品市场绩效之间的因果关系并探索可能的经济渠道，我们的研究对研究所有权/组织结构与产品市场行为的相互作用具有重要意义，并建议未来对产品市场竞争的研究应仔细检查公司通过共同股权所有权的相互联系。

# [Anticompetitive Effects of Common Ownership](https://doi.org/10.1111/jofi.12698)

### 摘要

> 许多天然竞争对手由一小部分大型机构投资者共同持有。在美国航空业，考虑到共同所有制意味着市场集中度的增加比反垄断当局"假定可能增强市场力量"大十倍。我们发现共同所有权集中度的路线内变化与机票价格的路线水平变化之间存在很强的相关性，即使我们仅使用由于两个大型投资者的组合而导致的所有权变化。我们的结论是，隐藏的社会成本------减少产品市场竞争------伴随着多元化和良好治理的私人利益。

### 研究问题

> 产业组织理论认为，同一投资者对竞争企业的共同所有权会降低企业的竞争动机，将产品市场推向垄断，导致无谓的经济损失。而实证文献很多认为金融机构共同所有权与公司目标和产品市场没有关系。所以，本文计划通过验证美国航空业产品市场的结果来说明这个问题，具体来讲，回答以下问题：
>
> -   目前的共同所有权水平有多大，对市场集中度有何影响？
>
> -   目前的共同所有权水平对产品市场竞争有什么不理影响？

### 相关文献

> 1、持有多元化组合的股东对组合利润最大化感兴趣，而非关注单个公司的利润，并且多元化可以减少这些公司的产品市场竞争[@hansen1996externalities; @rubin2006diversification; @margotta2010adolf]。
>
> 2、在不完美的市场中，当股东持有多个公司股票时，公司之间可能存在意见分歧[@hart1979shareholder]。
>
> 3、@azar2012new; @azar2017portfolio 建立了寡头垄断公司行为模型，在该模型中，潜在管理者之间争夺股东选票的竞争导致公司合并和内部化股东利益，包括在竞争对手中的持股。
>
> 4、@bresnahan1986quantifying 引入了修改后的 Herfindahl-Hirschman 指数 (MHHI) 来量化横向合资企业的竞争影响。
>
> 5、@azar2012new 提供了一段时间内美国股票共同所有权的度量标准，发现股票共同所有权对利润率有正向影响。
>
> 6、众所周知，"激进主义"投资者会改变高管薪酬、营业额和其他可能影响产品市场的公司决策[@brav2008hedge; @brav2012real]。
>
> 7、@gutierrez2016investment 发现在美国公司中，共同所有权与公司投资高盈利和Q的倾向负相关。
>
> 8、"懒惰的投资者"可能不会坚持实施这种扩张策略，而是让管理者摆脱选择次优数量带来的"平静生活"[@hicks1935annual]
>
> 9、**最近的研究证实，共同基金家族确实像其他投资者一样参与，尽管更多时候是"幕后"**[@mccahery2016behind; @dimson2015active; @appel2016passive; @mullins2014governance; @boone2015effect]，并且有时在秘密进行（Foley and McLannahan, 2016）。
>
> 10、大型被动资产管理公司在多数公司治理中发挥着决定性作用（Krouse, Benoit, and McGinty, 2016）。
>
> 11、主动管理的基金可能会威胁管理层出售股票，以防管理层不遵守他们期望的产品市场战略，这可能明确表示不进入竞争对手的市场（Reuters, 2008）。

### 研究结论

> 本文提供了由于市场层面的共同所有权联系而产生的大量反竞争激励的证据，表明共同所有权与较高产品价格之间存在因果关系。特别是在美国航空业，一个修正的市场集中度指数度量了竞争对手在多大程度上由同一投资者共同持有，意味着市场集中度水平远远超过传统的市场集中度衡量标准。根据美国反垄断机构的横向合并指南，在传统合并的情况下，平均路径的共同所有权集中度是假定"可能增强市场力量"的十倍以上。从理论上讲，由许多小的共同所有权权益累积而导致的额外集中度应该反映在更高的价格上。
>
> 我们发现，当公司因共同所有权而减少竞争激励时，价格会更高，产量会更低。具体来说，使用十四年的市场公司层面的季度面板数据，我们发现与独立持股或完全忽略共同所有权影响的公司相比，共同所有权导致机票价格高出 3-7%。然后，我们利用两家大型资产管理公司的合并导致的共同所有权集中度的变化作为工具变量（这与美国机票价格的预期航线水平差异无关，而导致共同持股发生变化），发现共同所有权导致产品价格高出 10-12% .这些结果表明，巨大的无谓损失（即经济效率下降）和共同所有权导致的损失从消费者向生产者大量转移。



### 参考文献
